### ISSUE TITLE
scoring issues

### ISSUE THREAD

**Issue by pw31** [gcp/leela-zero#1051]
I'm sure you have all watched the game of Leela Zero against Haylee[4p], where there was an issue with the scoring in the final position: 
On OGS:  LizzieBot[B] -HayleeW], game scored B+2.5, but should be B+5.5 I think, see  
https://online-go.com/game/12063810. There is an issue with seki in upper right corner, which fortunately didn't change the outcome of the game.

However, in this game, it did:
On KGS:  zjcxsaq1[W] - petgo3[B], game scored W+6.5, but should be B+1.5 
http://files.gokgs.com/games/2018/3/17/zjcxsaq1-petgo3.sgf
Not clear what the issue is, did the player made an error (or trick LZ?) in the final game scoring phase?

A counterexample is this one:
On OGS: RoyalZeroSlow[B] - marksim[W], game was correctly scored W+0.5
https://online-go.com/game/12095491
This game is super interesting. LZ makes another huge self-atari, but looking at the winprob, I think it did so out of desperation and saw this all coming well before. Just great play by W it seems. Super strong endgame from both sides apparently.

Anyway, my question is whether scoring issues might influence the training games and training match results. Does LZ produce the scores itself, or it there some kind of referee, like gnugo or so, which does provide the final score? How could LZ ever learn to score correctly otherwise?

**Comment by luigio** [comment]
As far as I know, scoring is made by the interface, not the bot. I think Leela just considers all stones alive, and passed because counting that way gave it the win. Otherwise it would have kept playing or resigned.

But I'm not an expert, so let's wait till someone confirms this.

**Comment by StanTraykov** [comment]
LZ knows how to score but sometimes cannot or doesn't know how to dispute the result by the server/opponent. In unrated KGS games, for example, the bot lets you have the last word.

**Comment by luigio** [comment]
But LZ doesn't pass if it counts the score as a loss, right?

**Comment by roy7** [comment]
Correct, but LZ scores using TT rules.

**Comment by luigio** [comment]
What I said. :)

**Comment by StanTraykov** [comment]
IIRC, LZ does pass with prisoners on the board, that is why people modify their CGOS clients to use "kgs-genmove_cleanup" instead of plain "genmove" to generate moves. 'kgs-genmove_cleanup' is a KGS extension to GTP for the specific purpose of dispute resolution, asking the bot to take all stones it thinks it can take (used only for area scoring systems--chinese, AGA, NZ).

**Comment by pw31** [comment]
It's not so much a question of when to start passing, I'd say, it's rather the way that sekis are evaluated.

**Comment by StanTraykov** [comment]
The above is a requirement for CGOS, because CGOS does all the scoring itself acc/to TT rules. On KGS, for example, I think it just lets you get away with anything if the game is free, reverts to dispute resolution (kgs-genmove_cleanup) if it's ranked with area-scoring, and lets the bot have the last word if it's ranked with territory-scoring (this is from memory).

**Comment by StanTraykov** [comment]
>It's not so much a question of when to start passing, I'd say, it's rather the way that sekis are evaluated.

Sorry, if it wasn't clear. LZ evaluates them correctly, but it's up to the server to decide at the end of the game if it does scoring all by itself, asks the bot but lets the user override, engages in dispute resolution, etc. In the free KGS game above, it lets the user override. Not sure about OGS. CGOS scores server-side, but requires cleanup for TT.

**Comment by MaxMaki** [comment]
If i've understood correctly then OGS forces server side scoring with all bots so that that humans can't cheat by disputing the score against the bot.
It was also noted in the OGS chat after the Haylee log that OGS scoring handles sekis badly.
So the seki scoring being incorrect in the Haylee has nothing to do with Leela, but is actually a OGS bug.

**Comment by kdbaby1412** [comment]
My leela Zero is also suffer from the same issue while she was ahead in a game with AQ. 

But she filled in her own eyes, and lost.
