### ISSUE TITLE
There are (2*BlockNumber+1) layers zeros, and each layer has FilterNumber zeros in weight files

### ISSUE THREAD

**Issue by bjiyxo** [gcp/leela-zero#1137]
As title, I found that there are (2*BlockNumber+1) layers zeros, and each layer has FilterNumber zeros in weight files.
For example,
5b64f, ->11 layers zeros, each layer has 64 zeors.
6b128f-> 13 layers zeros, each layer has 128 zeros.
10b128f-> 21 layers zeros, each layer has 128 zeros.

And most importantly, swa will change those zeros. I think there is definitely some problems here.

**Comment by hydrogenpi** [comment]
this is def not good....

**Comment by alreadydone** [comment]
https://github.com/gcp/leela-zero/pull/1112 https://github.com/gcp/leela-zero/pull/1099

**Comment by bjiyxo** [comment]
Maybe both of methods (including swa or not) are OK. But I need to point out that we're going to train a new weight files that cannot be trained in old methods.

**Comment by hydrogenpi** [comment]
ok so you will do it?

**Comment by bjiyxo** [comment]
I will train with swa and observe it.

**Comment by pangafu** [comment]
Yes, (2*BlockNumber+1) layers zeros is really a big problem, it seems like sgd not influence these filter blocks.

**Comment by Ttl** [comment]
They are convolution bias terms and they were set to zero on purpose because they would be canceled by the batch normalization layer after them that tries to set the bias to zero so there was no point in training them.

A while ago I added a support for training bias terms after the batch normalization layer (batch norm beta term) and moving them before the batch normalization when exporting the weights (#1112 #1099) to maintain the backwards compatibility in the weight files. That is why you see the latest code with SWA setting them to non-zero values.

**Comment by bjiyxo** [comment]
Thx for the detail explanation.
