### ISSUE TITLE
Suggestions to improve the efficiency of MCTS

### ISSUE THREAD

**Issue by zyg1968** [gcp/leela-zero#1157]
It is recommended to get the network results of all possible situations in a situation in batches, so that the search efficiency of MCTS should be increased more efficiently.

**Comment by ihavnoid** [comment]
Can you elaborate a bit more?
- Define "all possible situations in a situation" because it's impossible to exhaustively evaluate everything.  
- Why does the search efficiently improve?

Is what you are suggesting similar to #410?

**Comment by zyg1968** [comment]
I'm sorry, I'm not good at English. 
I mean that when searching for an extended sub node in a situation, all legal movements formed in a situation that can be calculated in batch, more efficient than expanding a node at a time.

**Comment by zyg1968** [comment]
I look at #410, a bit similar, the training of batch size can go to 512, I feel that should be able, I do not consider the problem of multi thread parallel search, I am not good at this. Just now 10 block ascension is very slow, need to increase block and filter, which requires MCTS computing more efficient and faster. I just want to make a suggestion.

**Comment by joseph-ireland** [comment]
You can't do large evaluation batches because most strength comes from search *depth*, and you need to finish the current evals before going deeper in the search, so with large batches a lot of the evals will be wasted.

Also, bigger networks actually *reduce* the effect of batching, since the GPU already has a big chunk of work to do. 

Small batches of 2-16 could be beneficial, it's hard to say, but the gains with large networks + winograd will likely be much smaller than was seen in that pull request.
