### ISSUE TITLE
NNCache is maximum size when not using -p

### ISSUE THREAD

**Issue by Hersmunch** [gcp/leela-zero#1193]
When `-p` isn't used `cfg_max_playouts` is left defaulted to:
`    cfg_max_playouts = std::numeric_limits<decltype(cfg_max_playouts)>::max();`
Which means when the NNCache size is set in `init_global_objects()`
`    NNCache::get_NNCache().set_size_from_playouts(cfg_max_playouts);`
```
void NNCache::set_size_from_playouts(int max_playouts) {
    // cache hits are generally from last several moves so setting cache
    // size based on playouts increases the hit rate while balancing memory
    // usage for low playout instances. 50'000 cache entries is ~250 MB
    auto max_size = std::min(50'000, std::max(6'000, 3 * max_playouts));
    NNCache::get_NNCache().resize(max_size);
}
```
will result in:
* the multiply by 3 wrapping to 0x7FFFFFD
* the cache being maximum allowed size

From the comment this doesn't sound like the intention. Of course reducing the size probably will make games take a bit longer..
I know they are not directly comparable but in this case would a simple min(cfg_max_playouts, cfg_max_visits) suffice? Should the maximum size be used when neither `-p` or `-v` are specified, regardless of the time settings? Though I suppose if time is short, a larger cache would be more helpful.

For reference I ran a few games with `-v 3200` and observed the cache being full around move 83ish. With a cache size forced to be 6000 it is full on move 4.

**Comment by sethtroisi** [comment]
I worked on some of this code. This isn't likely to have a big impact now that tree-reuse is turned on.
AFAIK (it's been a while) NNCache only has a hit when there's a transposition more than 8 moves in the past. There's some small slowdown from using more memory (300 MB vs 40MB) but I don't think it should be huge.

**Comment by killerducky** [comment]
@sethtroisi NNCache ignores the 8 move history for hits, sacrificing accuracy for speed.

**Comment by ihavnoid** [comment]
I did notice that it is very unlikely to hit anything on the cache on a different move.  That is, a NN evaluated on move N is very unlikely to be reused on move N+2.  Less than 0.1% unlikely.

(Basically, what I did was just dumped all NNCache accesses to a file and measured the reuse distance for a -v 500000 game.)

That said, I did have some concerns where we used time-based settings, since with multiple big GPUs a 30 second play time means hundreds of thousands of playouts.  Either we can increase the NNCache max size or we have to come up with a better NNCache replacement policy.  I'm planning to experiment a couple of replacement policies but nothing at this point yet...
