### ISSUE TITLE
I improved the ladder ability by oversampling

### ISSUE THREAD

**Issue by johnhuang-cn** [gcp/leela-zero#1200]
In my Go AI project, I tried solving ladder by oversampling, it seems work, maybe leelazero can have a try. 

https://github.com/johnhuang-cn/FancyBing#what-improvements-i-did

Thanks,
John Huang

**Comment by l1t1** [comment]
nice job

**Comment by Cabu** [comment]
Could feeding the learning pipline multiple times with the games where there was a ladder would help leela? I think so, because the learning process will have more chances to see the ladder problem and learn from it.

In that case, Are we still learning without human knowledge? I don't think so because we hand pick some games to feed the learning process multiple times with them...

**Comment by Cabu** [comment]
Yes, it come from self play matches. But some of these matches are 'hand picked' to go through the learning process more than once. And that 'hand picking' imply human knowledge.

**Comment by Ishinoshita** [comment]
@Cabu "In that case, Are we still learning without human knowledge? I don't think so because we hand pick some games to feed the learning process multiple times with them..."

Could be done without breaching the Zeroth Law by having an oversampling based on cross-entropy loss of the policy head on the positions. If it is above some threshold, the position is put back in the training bucket, up to a max turn limit. Misjudged (by the the NN) ladders, semeai, etc... are lilely to be captured, provided the tree search (+ dirichlet noise to help) is deep enough to get the 'right' answer...

**Comment by Ishinoshita** [comment]
@johnhuang "After about 200,00 steps (batch: 128) extra training, the ladder reading improve obviously, it can solve most ladder problem after 5,000-20,000 playouts."

The 'problem' with LZ is that targets derived from self-play game played with 1000 visits cannot solve the 'most ladders problems' you mention. Hence the (initially) slow progress in this area, when just looking at the self-play games or even the match games, all played with limited number of playouts/visits. Hence my comment here:
https://github.com/gcp/leela-zero/issues/1197#comment-381179089

BTW, cool to see experimental data now pouring from so many directions!

**Comment by alreadydone** [comment]
Just realized, nice name! ("Fan Xiping")
Am I right that the network is 128x8?

**Comment by yufanyufan** [comment]
A general approach without hand pick to oversample from games that win rate has huge fluctuation.

**Comment by Mardak** [comment]
At what point is go-specific knowledge acceptable? At a high level, there's various components: network architecture, move search algorithm, self-play generation, training procedure, network evaluation; and each of those can have slight adjustments that are go-specific:

network architecture: how many layers and filters are enough to handle 19x19 board, ko, etc.
move search algorithm: 8-way rotational symmetry for go
self-play generation: enough visit count to search, randomness added to the first 30 moves / first ~15% of an average go game
training procedure: also uses rotational symmetry when shuffling

John's suggestion is for the training procedure in picking out ladder games, but more generally, it's picking out problematic game situations that could dynamically found without go-specific knowledge of ladders being tricky.

Similarly, this proposal could be morphed into adjusting the self-play generation where instead of starting from an empty board, jump straight to the start of a ladder. Similarly, it could be generalized as problematic game states that could use more self-play games to explore from.

Another related tweak is to adjust network evaluation, where instead of only playing full matches, it could start from a ladder game and see if it plays correctly. There's a bunch of these "unit / regression test games" to make sure learning isn't lost.

For each of these 3 ladder tweaks in self-play generation, training procedure, and network evaluation; the go-specific knowledge is that ladders have a set of forced moves, i.e., clearly good/bad. But generalizing it to "problematic game state" could be tricky as how would tabula rasa know there's supposed to be a "correct" sequence.

At least from the rotational symmetry analysis of "one bad rotation" game failures, there's a sudden drop in win rate because a move was not expected from one rotation but the 7 other rotations would have noticed it. Although using this particular heuristic to find "problematic game state" to be more tabula rasa is hinged on the fact that one knows go has symmetry…

**Comment by johnhuang-cn** [comment]
@alreadydone  Yes, it is 128x8

**Comment by alreadydone** [comment]
https://github.com/gcp/leela-zero/issues/1129 also uses three nets for opening, mid-game and endgame.

**Comment by johnhuang-cn** [comment]
It seems great idea think alike :)

**Comment by godmoves** [comment]
>A general approach without hand pick to oversample from games that win rate has huge fluctuation.
Maybe this is a better idea, and can handle more situations. But we need to record the win rate in self-play games.

**Comment by Ishinoshita** [comment]
Recording root evaluation (either win rate or value) during self-play game would be great anyway, for the sake of future experimentations. Only very marginal cost in terms of data size.

**Comment by Ishinoshita** [comment]
Regarding current thread subject, oversampling without infringing Zeroth principle should be possible by oversampling /multiple time sampling positions based on the difference between value head NN evaluation on the position and the value estimated at root by tree search on that position. Or regarding policy head NN, on the divergence between policy head prior and exponantiated visits count found by tree search. Or on both criteria to oversample only positions badly evaluated by both heads.
