### ISSUE TITLE
looks like bad person uploading bad game

### ISSUE THREAD

**Issue by Tsun-hung** [gcp/leela-zero#1210]
http://zero.sjeng.org/viewmatch/c75974eb0004da64e9bbcb8d36f89c560d3e4f80ab83d1a13660890b5447dc53?viewer=wgo
this match end at 61st move.And it begins with handicap
what is wrong with the server?

**Comment by isty2e** [comment]
[Another one](http://zero.sjeng.org/viewmatch/ae0977358d79a9ae840e8bdd00c8aaaf58a18c02a39464877cd92b6fc735811b?viewer=wgo) here.

**Comment by godmoves** [comment]
🤔Maybe someone compiled a bug version of autogtp.

**Comment by Tsun-hung** [comment]
http://zero.sjeng.org/viewmatch/ae0977358d79a9ae840e8bdd00c8aaaf58a18c02a39464877cd92b6fc735811b?viewer=wgo
this match is similar, both come from 1 client.

**Comment by marcocalignano** [comment]
It seems the moves are the same just rotated. I would like to see the SGF file and the training file to see if autogtp could be responsible (I doubt it). The fast that it starts from a predefined position with two stones for each player is suspect already. Of cource if you modify the autogtp code then it is possible. (It is opensource after all.

**Comment by godmoves** [comment]
It seems that this is a modified version of leelazero for traditional Chinese ruleset. So I think this is an accident that it got a match job. 🤔

**Comment by OmnipotentEntity** [comment]
That won't work, because most of us compile our own binaries.

**Comment by ryouiki** [comment]
To avoid bad results from broken clients, it may be easier to implement server-side filter based on certain rule set :

a sgf is invalid if,
- move count < 90
- pass before move 10
- ...

**Comment by afalturki** [comment]
http://zero.sjeng.org/viewmatch/b951051ad38097466be3c05fee02f9ff891b0a55aebd01930a6f626e7f1a8102?viewer=wgo

**Comment by Mardak** [comment]
Each of those match games have a sgf with wrong komi, handicap, and added black and white stones:

```sgf
KM[0.0]
HA[2]
AW[dd][pp]
AB[dp][pd]
```

The comment seems to indicate it was run via autogtp, but likely there's a custom autogtp/leelaz running additional GTP commands to set the komi, etc or loading a sgf to start from.

**Comment by Hersmunch** [comment]
See discussion in #458. @gcp already is doing statistical analysis to filter uploaded self play games so they aren’t used for training and some IPs were blocked. This time it looks like matches are being affected and I’m assuming the analysis isn’t automatically applied when determining the wins/losses. I haven’t checked but hopefully these bad games give wins equally to the two networks and doesn’t upset the match result since white always wins.

**Comment by Mardak** [comment]
leelaz normally doesn't know how to printsgf of added white stones:
https://github.com/gcp/leela-zero/blob/97c2f8137a3ea24938116bfbb2b0ff05c83903f0/src/SGFTree.cpp#L439-L468

Notice that the header appends HA then RE with no "AW". This is output of loading in a bad match game and printing it out: `HA[2]RE[W+53.0]C[Leela Zero options: …]AB[dp][pd]`

Whereas the bad match game has `HA[2]AW[dd][pp]RE[W+53.0]C[Leela Zero options: …]AB[dp][pd]`

**Comment by Friday9i** [comment]
It is still ongoing: see match games from client 5 for network 1cf75770

**Comment by Mardak** [comment]
Given that someone changed SGFTree to output added white stones, I would guess someone modified leelaz for some other reason / experiment and forgot to recompile with master or next branch when wanting to contribute resources via autogtp.

If it were actually malicious, changing SGFTree is quite a roundabout way to do it.

**Comment by iteachcs** [comment]
I think simple filters such as those suggested by @ryouiki can be implemented.  I do not have the ability to program it for now but it would be nice if SGFs can be filtered.  More sophisticated attacks are hard to deal with but they are less likely and also unlikely to last long.

**Comment by wushanyun68** [comment]
![image](https://user-images.githubusercontent.com/35222250/38793886-9ba71f38-4185-11e8-8f2b-40249ba0bee1.png)

**Comment by grolich** [comment]
Some of the filters remove conditions that could, in theory actually occur and might indicate a problem we would like to know of in LZ; However, I think handicap > 0, komi != 7.5 and added white or black stones could be used to avoid games that have no reason to be there for sure.

**Comment by Tsun-hung** [comment]
client 11
http://zero.sjeng.org/viewmatch/e8a0d9e5f47c0e0396455cec1771cd774728621bf4a2ab6188fb5b55cbbe5a92?viewer=wgo

**Comment by ryouiki** [comment]
About 4% of matches for testing 07b1c9cd infected by client 11 till now.
http://zero.sjeng.org/match-games/5ad45195a679501dfd1200fe

**Comment by Friday9i** [comment]
Yeah, and it probably infects also around 4% of selfplay games for 1 day now... Something must be done to filter theses games out!

**Comment by lp200** [comment]
I found an illegal selfplay game.
I'm worried.

http://zero.sjeng.org/view/860b80feed87e22e17190fdb5626c2b7eca0e5ecbd8431f89296014e600b9645?viewer=wgo

**Comment by genleung** [comment]
@gcp @marcocalignano  @ttl @sethtroisi  
Please do something to prevent someone from destroying leelazero !

**Comment by hydrogenpi** [comment]
Is there a way to track the IP address of where these malicious clients came from and send to Interpol for prosecution?

**Comment by hydrogenpi** [comment]
The fact that fd6 should have and could have and would have passed where it not for these intentional bad games means that whomever is doing this has caused real and provable harm and should be punished to the fullest extent of the law.

**Comment by Friday9i** [comment]
lol hydrogenpi... I just share your conclusion: "Something needs to be done! this is bad". Theses games should be blocked, as well as the faulty client (ideally through a dynamic filtering of submitted games based on handicap, early passes, very short games, ...).
And if possible, to change the status of the last network to a PASS, as it would have passed without buggy games.

**Comment by Alderi-Tokori** [comment]
@hydrogenpi You've seriously got to watch less action movies.

**Comment by hydrogenpi** [comment]
@Friday9i if the analysis is correct and that fd6 would have actually in fact PASS had the bad games not occurred either way, then it is matter of policy whether or not roy and gcp will manually set it to pass, since that  can be manual overrided. if so, there should not give these cyber terrorists a win by refusing to pass otherwise they will see this as a win and this is set a bad legal precedent to all projects of this nature that one bad apple can affect the course and outcome of an entire project like this.

**Comment by kuba97531** [comment]
I think you have to calm down and stop telling everyone what to do. It's quite clear that there is some bad client / faulty build and not intended damage. Actually if you are running the autogtp yourself you should probably check if you are by any chance not producing the faulty games - as should anyone who is running autogtp right now - especially local builds with modifications.

**Comment by hydrogenpi** [comment]
kuba Im on windows and always run vanilla autogtp i never compilef my own

**Comment by hilbertcao** [comment]
i think ,after sgf upload,we can assign random three to check the sgf,if more than two clients 80% judge matchs,then the sgf is valid

**Comment by hilbertcao** [comment]
i think ,after sgf upload,we can assign random three to check the sgf,random pick some move of the sgf,if more than two clients 80% judge the rate matches,then the sgf is valid

**Comment by hilbertcao** [comment]
i think ,after sgf upload,we can assign random three clients to check the sgf,random pick some move of the sgf,if more than two clients 80% judge the rate matches,then the sgf is valid,or simply we can check only by the upload server

**Comment by MaxMaki** [comment]
I think some calm is a good idea here. From earlier posted screenshots and information it seems like it's 1 client. Whether this is a bugged client due to someone using a modified client, or someone doing it on purpose, who knows.

Regarding matches the server already randomly assigns white and black randomly afaik, and since it's only 1 client and this client always gives the win to white, it basicaly evens out the wins/losses that are incorrect. Of couse this creates some skew, and might just put a network over or under promotion, in the long run it's not something that's going to stop a clearly stronger network from promoting.

Last time there were bugged games due to bad OpenGL drivers it was worse, and back then it was also clear the the self-play and training procedure was quite robust against such noise. It didn't stall the project. Last time i think it was deemed that we shouldn't worry about small amounts of wrong games, since they won't really hurt the project in reality, and overreacting with triple checks for example would grind us to an halt much quicker than a few bugged games by a few bugged clients.

I'm sure GCP or Roy will take a look when they can and ban IPs if they deem necessary.

**Comment by Ka-zam** [comment]
Nothing to worry about, just someone who forgot that they made some code changes and then ran autogtp from the wrong source dir. I have 6 or 7 builds myself and it's easy to miss. We should probably focus on getting the subtle pointer issues sorted out since that's really irritating. Next branch crashes occasionally with assertion fails.

**Comment by gcp** [comment]
We're aware of this and deleting the buggered's clients games.

It looks like someone modified the client and forgot to switch back when launching autogtp or something.

While the self-play games are rather robust to noise or bad data, it's easy to tip over a close match. (No real big deal either, if the next net gains more Elo it will just pass...)

>We should probably focus on getting the subtle pointer issues sorted out since that's really irritating. Next branch crashes occasionally with assertion fails.

Use the master branch, the next branch can definitely be buggy as it's used for development.

**Comment by 2ji3150** [comment]
Maybe we can check crc of the client instead the version for preventing modified client to accept the task?

**Comment by roy7** [comment]
Many people compile /next themselves though.

**Comment by higherdim** [comment]
LoL Hydrogenpi. Don't forget the possibility that DeepMind may want to destroy LZ before it surpasses AGZ...

**Comment by herazul** [comment]
> (No real big deal either, if the next net gains more Elo it will just pass...)

Couldn't be more on point, Mr Prophet. Seems like the very next one is a monster !

**Comment by Ka-zam** [comment]
What's the big rush with calendar time? It'll get there and AGZ was already first and now several other bots are proving very strong as well. No prize to win there. The big thing with LZ is that both source and networks are open so we can look forward to some really nice teaching tools. It has already changed the way I play the game.

**Comment by hydrogenpi** [comment]
@higherdim I know you were maybe being sarcastic, since no one expects LZ to reach AGZ levels, but to answer @Ka-zam on calendar time, I think it shouldn't be the only metric, but it should be a metric nonetheless. The issue at stake is that none of the other bots, FineArt, DeepZen, Alpha, and now Golaxy have open sourced or open weighted, if you will, and other than Leela zero, it seems increasingly unlikely that any other stronger bot (AQ is open source, but arguable LZ has passed AQ so I wouldn't really call it a strong bot at this point) will ever open up in the manner that LZ has done. Many will prob go the way of Deep Blue and never to be seen from again. So why time factor could play a role is imagine people losing interest if other (non-Google) bots are stronger, (and the public gets to witness a proliferation of strong but not open bots and gets desensitized to it all and etc)_ and because LZ is essentially at the mercy of volunteer clients, if the masses lose interest in the whole bot trump bot scene, then LZ is basically not going to make further improvements. 

BTW the recent Golaxy thing didn't exact boost LZ popularity in terms of getting more volunteer clients. For one, the LZ team (not to be confused with the official LZ gcp etc) was horribly UNprepared, they keep changing networks, used a buggy compile, changed time, dithering back and forth and just in general didn't represent neary as well as some would have hoped... and its not fair that Golaxy, being the stronger network bot, got to use TWICE the hardware specs as the LZ team. Then they had home advantage of LZ being open weight, open source, and they are closed everything... I mean in no sense of the word was it even a fair match, not even by pretense.

**Comment by cdqz2014** [comment]
The man who wanted to train a Zero type AI with Chinese ancient rules, namely, cross handicap and zero komi,  just show up on China's reddit, [贴吧](https://tieba.baidu.com/p/5650641888?pn=2). 

He confessed that he modified the source code just want to train an Ancient China Go AI himself (Frankly, in China there are many people zealous for that...), and deeply apologized for not modifying the code that will automatically upload bug games to LZ's server since he is a novice to LZ's source code, LOL. The bug autogtp has also been killed.

**Comment by alreadydone** [comment]
You forgot to mention the most important feature of the ancient Chinese rule, namely the presence of [group tax](https://senseis.xmp.net/?GroupTax) (not counting any empty space in Tromp-Taylor rule)

**Comment by roy7** [comment]
@cdqz2014 Thanks! Mystery solved. I'll remove the special code to block him. :) He just needs to be sure to only run the normal leela with autogtp if he wants to give us GPU in between his own experiments. Or like you say, turn off the uploading/etc so it just generates games for his own use and not send them our way.

**Comment by Tsun-hung** [comment]
![22](https://user-images.githubusercontent.com/33803485/42914157-5569e4ca-8b2b-11e8-8d2e-c5b188358ad0.JPG)
Is there any obsessive who uploaded the chosen game?
@roy7  Any abnormity occur to the server?

**Comment by kuba97531** [comment]
![test](https://user-images.githubusercontent.com/133693/42929467-73451f28-8b3a-11e8-99a5-3bf166197dbc.png)

This is normal when one stops autogtp during a match and restarts it later.
