### ISSUE TITLE
How does leelaz count? Must it learn to count?

### ISSUE THREAD

**Issue by emdio** [gcp/leela-zero#122]
So I was taking a look at some of the games played on my computer and found this final position, with the scoring "B+1.5"

[https://imgur.com/a/vooNF](url)

So evidently the white group at A19 is considered to be alive.

So far I hadn't thought about the counting system; I somehow believed that in the code of leelaz a part exists that makes the counting, using the rules for death, seki, etc.

But after seeing this result I wonder how the counting is done. And even more, is leela supposed to learn how to count (i. e., will leelaz eventually take the A19 group as death)?

**Comment by gcp** [comment]
The engine scores using Tromp Taylor rules: everything left on the board is considered alive. This means that in order to win, it has to learn how to actually kill dead groups (which in turn learns it how they can be kept alive in a ko fight etc). There most definitely isn't any hard-coded knowledge about dead shapes etc. The engine has to learn that by itself. There also isn't any "rules for death, seki, etc" Those don't exist! Life and death is in general not a "solvable" problem.

In the example you gave, black wins regardless if he cleans up or not. So it just doesn't bother.

There is a command, kgs-genmove_cleanup, which can force the engine to play out and clean up the board. But this command is there for "human convenience" only.

**Comment by jkiliani** [comment]
I have also seen games like this, and by the winning player actually does play rationally in these situations by refusing to clean up: The losing player plays anywhere legal, until the only allowed move is to pass. The winning player doesn't capture these groups if not necessary, since capturing would create further legal moves and postpone the forced pass.

**Comment by emdio** [comment]
Many thanks for your answers.
This "everything on the board is alive" system makes a lot of sense, but a new question arises; say we have a pretty strong leelaz playing (maybe 4dan just to say a number) and the above position happens, but switching a couple black and white stones so black is losing by a couple points. In this case, black would capture the white group at A19 before passing, all right?
My point is, isn't a bit weird having a 4000Elo engine that captures a death group before passing? Is that the way AlphaGo-Zero behaves?

**Comment by jkiliani** [comment]
As I understand it, Alphago will always resign when the situation is hopeless, so no. However, 10 % of self play games are played to the end (to test false resignation rate), and in those I would expect the networks to play until a win by Tromp Taylor scoring is forced. 

For LeelaZ, I guess it will depend on whether we stick with the "No resign policy" or adopt a system like Deepmind, with resignation disabled only for a small number of games to test false positives.

**Comment by gcp** [comment]
>In this case, black would capture the white group at A19 before passing, all right?

Yes. It understands the difference between winning and losing.

>My point is, isn't a bit weird having a 4000Elo engine that captures a death group before passing? 

Only to humans.

>Is that the way AlphaGo-Zero behaves?

Yes, the implementation is exactly as in the paper.

"AlphaGo Zero uses Tromp-Taylor scoring 66 during MCTS simulations and self-play training. This is because human scores (Chinese, Japanese or Korean rules) are not well-defined if the game terminates before territorial boundaries are resolved. However, all tournament and evaluation games were scored using Chinese rules."

They do not explain what they really mean by "scored using Chinese rules". But one thing you can do is to let the engine play out the game at a very fast level, and then remove the groups that end up dying.

**Comment by gcp** [comment]
>For LeelaZ, I guess it will depend on whether we stick with the "No resign policy" or adopt a system like Deepmind, with resignation disabled only for a small number of games to test false positives.

I have not really done much about this because the engine must have a fairly reasonable idea about who is better before it makes sense, but one suggestion on the computer-go mailing list was to simply disable resigning in a fixed percentage of games, and make the thresholds not too small.

**Comment by billyswong** [comment]
Tromp-Taylor Rule, in its full set, allows suicidal moves as long as it doesn't violate superko. Chinese Rule disallows that so I guess they feed a different legal moves map to AlphaGo when playing evaluation/tournament games.

Another possible factor is the [Chinese Superko](https://senseis.xmp.net/?ChineseSuperko) rule, which if implemented will generate further legal moves map difference.

On the other hand, it may be they really do a manual dead stones removal for evaluation games of early iterations of AGZ, when both sides passed prematurely?

**Comment by gcp** [comment]
They talk about Tromp Taylor scoring, not playing with the ruleset. I both forbid suicide and use Chinese Superko in Leela Zero. Without some kind of ko rule you will get problems.

>On the other hand, it may be they really do a manual dead stones removal for evaluation games of early iterations of AGZ, when both sides passed prematurely?

Extremely unlikely for multiple reasons: the program needs to learn how the scoring works, they most certainly don't do "manual intervention", and automatically removing dead stones is not possible in the general case. There is no easy or fool proof procedure to identify life and death, seki, etc. These things are as hard as go itself.

**Comment by billyswong** [comment]
> Trump Taylor has Chinese-style superko

Trump Taylor Rule in its full set uses Positional Superko, which prevent all cycles. Chinese Superko as described in Sensei's Library prevent common cycles but not all cycles. If Deepmind didn't do manual dead stones removal for evaluation games, then it is strange when they say they use Chinese scoring in evaluation games. Trump Taylor Rule and Chinese Rule, if dead stones removal skipped, is no different in scoring. This is why I have assumed they used a full set Trump Taylor for self-play, or at least adopted positional superko, when I was reading the paper. It has to be this, or manual dead stone removal for evaluation games, or what the paper wrote makes no sense.

**Comment by gcp** [comment]
Ok, I thought Chinese rules used Positional Superko (as opposed to Situational), wasn't aware there are further differences, which is why I made the equivalence. I use Positional Superko.

The other difference is suicide, which is allowed in Trump-Taylor (though single-stone is forbidden due to the superko rule), but AFAIK not in Chinese rules. I disallow it. It think it is not explicitly spelled out what AGZ did, but if they have the program play under both Chinese an TT rules, it makes sense to just disallowed it, IMHO.
