### ISSUE TITLE
The Komi parameter is ignored.

### ISSUE THREAD

**Issue by FeoDoT90** [gcp/leela-zero#1221]
LZ not a bad play in games with handicap, but ignoring the parameter Komi, gives the error in the result. The evaluation network trained on the results of the games, with a preinstalled Komi 7.5, and now roughly ignores other values. As far as I understand, the network does not have a clear understanding about Komi and scoring rules. When training LZ got only intuition about how much you need to capture the territory, and now she has no idea why white need to capture less territory to win. And that's the problem. She loses 2.5 points and believes that it is enough to pass to win, because she ignores the Komi size of 0.5, since the internal evaluation network still believes that her Komi, like the rules of the game are unchanged, and Komi probably matters about ~7.5 and she probably wins with a score of ~4.5 points. LZ does not calculate anything-it's just ridiculous intuition of the network. If the network tried to maximize the result, then ignoring the Komi size would be acceptable, but it looks like LZ, like AlphaZero, does not. Maybe there's some way to fix this without re-training the network?
![screen1](https://user-images.githubusercontent.com/37275407/38952802-7a5db838-4355-11e8-9f0e-e651dddfa560.jpg)

**Comment by isty2e** [comment]
Setting any komi value other than 7.5 is just invalid and will be ignored no matter what you do. Retraining is a must if you want to change that.

**Comment by FeoDoT90** [comment]
I suppose there would be no need to retrain the network, if the evaluation network initially would give an indicative assessment of the position in the potential points, rather than from 0.00 to 1.00, it would also facilitate the task of choosing the client's best course to maximize the result. But perhaps it is really another project. Also with handicap is not required to retrain the network because the network must rely on a reasonable game, and even if there are odds to consider it equal in strength to himself. Imagine if Stockfish had a rook taken away at the beginning of the game, and he would show the score equal, because he would assume that the opponent plays badly and play without rook is normal, and would start playing differently than to maximize the result of the game.
We will wait for such functionality in Leela Omega :)
Thanks to all!

**Comment by isty2e** [comment]
Evaluating the board state with something like expectation value of points is not a good idea, since you lose the direct mapping from the board state to the winrate, leading to a very crude approximation. You need a probability distribution of scores to do it in a sensible way, but this is anyway not the present goal of this project.

**Comment by petgo3** [comment]
only way i know is inverting the net. then lz play with -7.5 komi. no perfect solution, but better than loosing by a few points while having nice results from the net ...

**Comment by TFiFiE** [comment]
The network being hardwired with a komi of 7.5 notwithstanding, the shown image is suspect, since it implies a state in which the engine would have taken any set komi into account as it was determining the wisdom of passing. Proof:
https://github.com/gcp/leela-zero/blob/5b2460cbce91142a715b96138b6bc073afdadca7/src/UCTSearch.cpp#L387-L391 https://github.com/gcp/leela-zero/blob/5b2460cbce91142a715b96138b6bc073afdadca7/src/UCTSearch.cpp#L406-L407 https://github.com/gcp/leela-zero/blob/5b2460cbce91142a715b96138b6bc073afdadca7/src/FastState.cpp#L150-L155 https://github.com/gcp/leela-zero/blob/5b2460cbce91142a715b96138b6bc073afdadca7/src/FastState.cpp#L46-L47 https://github.com/gcp/leela-zero/blob/5b2460cbce91142a715b96138b6bc073afdadca7/src/GTP.cpp#L298-L309 (To those not versed in C++, don't be fooled by line 301; that variable gets the new value in line 305.)

Maybe what happened here is that this GUI doesn't also give White an extra point for each handicap stone (see line 151 above).

**Comment by Hersmunch** [comment]
> @petgo3 only way i know is inverting the net. then lz play with -7.5 komi. no perfect solution, but better than loosing by a few points while having nice results from the net ...

I may be talking utter nonsense but could any komi between -7.5 and 7.5 be achieved by taking a weighted average of the networks' outputs when running one with the correct colour inputs and one with the opposite? I seem to remember someone posting about running multiple networks at the same time previously so perhaps it could be tested using that approach.
Anyone got ideas on how to measure what a network thinks komi is? (I'm lacking sleep so my brain isn't working so well)

**Comment by alreadydone** [comment]
Curious experiments about weighted average interpolation at https://github.com/Chicoryn/dream-go/issues/25#issuecomment-381417656

**Comment by FeoDoT90** [comment]
I'm probably gonna say something stupid right now, but I'll try. If the Komi value is really fed to the network input (which I'm not sure), maybe it is worth re-evaluating the played game several times, taking into account the different Komi value, so that the network itself determines the purpose of this parameter? But until either the input network does not support the value of the Komi, or the network safely ignore this value as the output the probability of winning does not correlate with Komi.

**Comment by gcp** [comment]
There is no input for komi and the optimal policy strategies are komi dependent, so any solution pretending to be optimal has to sample complete games played at various komis. Which as said before, is not going to be done here.

**Comment by gcp** [comment]
>The network being hardwired with a komi of 7.5 notwithstanding, the shown image is suspect, since it implies a state in which the engine would have taken any set komi into account as it was determining the wisdom of passing. 

This is correct. The problem is that Leela plays by Tromp Taylor rules under which white has easily won because all of black's central territory is void. Thus, she is correct to pass as the game is won and the GUI has scored it incorrectly.

**Comment by FeoDoT90** [comment]
Yes, I had to fill up the Board with stones, so that LZ realized that he lost the game. I guess it's either a realization flaw or the failure of the Tromp – Taylor rules themselves. Probably, LZ takes into account only the potential number of installed stones on the Board, and finds it out very late.
![screen2](https://user-images.githubusercontent.com/37275407/38964397-4d5998be-437f-11e8-9533-4ae339680c3f.jpg)

**Comment by FeoDoT90** [comment]
Attach the original SGF file of the game
[LeelaVsLeelaZero.txt](https://github.com/gcp/leela-zero/files/1926201/LeelaVsLeelaZero.txt)

**Comment by gcp** [comment]
It has nothing to do with calculating the moves deeply, it's because as was pointed out several times, she only knows about 7.5 komi.

I pointed out Tromp Taylor rules because there was a claim she was wrong in passing. She was not. But the heuristic about passing (which knows about komi) doesn't magically make the program actually able to play at different komi.

**Comment by fishcu** [comment]
For playing handicap games, training a second network with komi 0.5 would be sufficient.
Covering the standard komi of 7.5 and additionally 0.5 would already cover 99% of usage scenarios.

Just asking about the theoretical feasibility: Could this be done with the available games that did not end in a resign, where a score can be reconstructed?
Or would the available data likely not be enough to train a network of similar strength to the current one that plays with komi 0.5?

**Comment by gcp** [comment]
As pointed out before, not at full strength, because the optimal policy moves depend on whether you are winning or losing, and this changes if you change komi.

**Comment by dmicsa** [comment]
sorry I didn't read everything. A simple solution is to keep during training not only the Average or Winning rate but the Standard Deviation of the wins too. This could help to compensate and report more accurate winning rate in the presence of komi using a small constant storage two floats instead of one. A more accurate method is with linear storage and is more involving.

**Comment by roy7** [comment]
If someone were to train a new network, I'd suggest going with 0.5. komi. That's the default for Chinese with any handicap right? Then LZ could play any # of handicap stones, or a handicap of 1 with no komi, properly. Weird komi doesn't really need to be supported since the majority of people will only ever play 'normal' matches.

**Comment by gcp** [comment]
If you are talking about 6.5 komi, you are likely playing under territory scoring rules, and believe me, if you do, you have far worse problems than just the komi because Leela doesn't support those rulesets at all.

I did notice this isn't mentioned in the README. It probably should.

(And Leela should probably warn you about the komi)

**Comment by ProLeela** [comment]
Of course I am playing with the Japanese rules ! I am European. I have played 30 years with these rules, but we don't speak about the rules. It's not about playing cu LeelaZero, but about studying with it. LZ can use any rules it wants. But the komi IS/CAN BE. variable. Not in the the Japanese rules ("territory scoring" as you "politically correct" call it). In every Go rules. And the main use for the AI is as a teacher. Just my two cents.

**Comment by gcp** [comment]
If you think the difference between 7.5 komi and 6.5 komi is relevant, I have no idea why you think the difference between Japanese and Chinese rules is not relevant, because it leads exactly to the same 1 point score differences in practice.

Leela Zero only supports Chinese rules with 7.5 komi, and this is unlikely to change any time soon.

**Comment by petgo3** [comment]
There is a possibilitty to let play lz with -7,5 komi. I use it on handicap games on Kgs. But this is for teaching purpose quite far from real games.
