### ISSUE TITLE
Opening Book

### ISSUE THREAD

**Issue by Cabu** [gcp/leela-zero#1234]
Like for most chess engines and some Go engines (eg: Pachi), it would be interesting to allow an optional opening book (like the alphago one https://alphagoteach.deepmind.com/dist/files/book.sgf) to take over the engine for the first moves of the game. This way, Leela will offer a better user experience for the human player by having a more responsive/faster game beginning.

**Comment by Splee99** [comment]
From my experience with Levels 0.11, the opening book only saves think time and actually makes Levels weaker.

**Comment by roy7** [comment]
An idea for an opening book behavior for LZ might be an option to move super fast for the first N moves (maybe a command line parameter). It could either move instantly to the heatmap highest value space, or just do a limited (few hundred?) playouts/visits during these N moves.

This way the book isn't static and the opening would change if the network's preferred moves change. But you can still have the first few moves be lightning fast.

**Comment by tterava** [comment]
Forcing LZ to play openings it doesn't usually play certainly makes it weaker. I believe the reason why it always plays the same type of opening is because:
- It's simple
- There's no obvious way to exploit it
- It's easy for the network to remember
- It knows exactly how it behaves.

If you switch up the opening, it makes all kinds of mistakes like not checking if a ladder works and generally being a lot weaker.

I believe this will change once the network is large enough and it can afford to find advantages in fuseki without losing mid-late game strenght.

**Comment by gcp** [comment]
Feel free to do this kind of thing in a fork or whatever but obviously not something for Zero.
