### ISSUE TITLE
is LZ growing weaker in actual play?

### ISSUE THREAD

**Issue by pilhon** [gcp/leela-zero#1255]
Hi, occasional GPU contributor here. From the graph at zero.sjeng.org, it seems LZ is getting consistently stronger over time, gaining what looks like 900 Elo since moving to 192x15. But even if it is exaggerated, and is actually 'only' 300 Elo stronger, how comes Roy7's bot RoyalZero has _lost_ 300 Elo over the same period? As far as I know he updates the network regularly, and since reaching a peak with the last 128x10, it has been going consistently downhill... Was that somehow expected? (Not trying to disparage, just to get some insight.)

**Comment by roy7** [comment]
RoyalZero doesn't get a ton of ranked games, so it isn't a super good benchmark of our true strength. Plus it's possible a low ranked person might use LZ themselves to cheat in a ranked match, winning way above their strength but the scoring system can't know that, so RZ loses a lot of rank in those losses.

Ultimately the best way to know if we're really losing or gaining strength is to see how the most recent networks are doing on CGOS vs a variety of other bots.

**Comment by hydrogenpi** [comment]
From network 117 to 127 it has definitely gotten stronger, not weaker. But no where near a 300 Elo boost. I'm not sure where you got the 900 Elo from, because since moving to 15 blocks its only gotten about 300 internal ELO stronger and 100 CGOS Elo stronger... The sudden "jump" from `10 block to 15 block doesn't count since its not taking into account the strength loss in time, that 15 blocks takes about 2.5 times slower to think than a 10 block. So the discontuiity jump is an illusion.

**Comment by ashinpan** [comment]
> Plus it's possible a low ranked person might use LZ themselves to cheat in a ranked match, winning way above their strength but the scoring system can't know that, so RZ loses a lot of rank in those losses. (roy7) 

I agree. If the cheater uses a very powerful configuration with LZ, it would be easy for him/her to defeat RoyalZero, which can afford only 3200 visits.

**Comment by odeint** [comment]
Counterpoint is petgo3 on KGS, which is still ranking up. Pet also updates the nets regularly.

https://www.gokgs.com/graphPage.jsp?user=petgo3
http://kgs.gosquares.net/index.rhtml.en?id=petgo3&y=2018&m=4&d=16&r=1

**Comment by gcp** [comment]
Answer is no.
