### ISSUE TITLE
what is the standard of games number of a match

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1257]
I saw 

2018-04-22 17:19 | 3f6c8dd8  VS  e8601c38 | 243 : 194 (55.61%) | 437 / 400 | PASS
-- | -- | -- | -- | --

and

2018-04-24 11:05 | b908a080  VS  3f6c8dd8 | 227 : 190 (54.44%) | 417 / 400 | fail
-- | -- | -- | -- | --

and

2018-04-24 21:47 | 2f04312d  VS  3f6c8dd8 | 216 : 189 (53.33%) | 405 / 400 | fail
-- | -- | -- | -- | --

in theorical, the later two also could reach the result of first one if give them more chances.

**Comment by hydrogenpi** [comment]
The whole 400 matches is an estimation in the first place so th at one doesn't have to do 1000 matches. 

Lets say the b908a080  VS  3f6c8dd8 played out to 437 matches. It would need 14 additional wins against 6 additional loses in order to make the 55% mark. Possible, but given its already 54%, not probably, esp since the easy wins come in first.

**Comment by gcp** [comment]
The server overcommits matches because some clients will never reply.

**Comment by l1t1** [comment]
maybe the first 0.55 pass at 400.

Test Matches (100 Most Recent)
Start Date	Network Hashes	Wins / Losses	Games	SPRT
2018-04-25 09:44	4183dce9
 VS  158603eb
0 : 0	0 / 400	
 
2018-04-25 07:23	158603eb
 VS  3f6c8dd8
220 : 180 (55.00%)	400 / 400	PASS
