### ISSUE TITLE
why the right side table on web page keep constant?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1260]
but the left side table is changing. only self-play game is send, no match task is sent?

two minute ago
![2018-04-25_182211](https://user-images.githubusercontent.com/23301704/39240271-d6b075fe-4872-11e8-8b99-1b284db240dd.png)

now
![2018-04-25_182403](https://user-images.githubusercontent.com/23301704/39240300-e3268170-4872-11e8-9697-f75ccfe772c4.png)

**Comment by gcp** [comment]
It does look like matches have locked up @roy7.

**Comment by gcp** [comment]
Actually, the matches are being played: http://zero.sjeng.org/match-games/5ae03ff1eb7c9575993a952b

But the website isn't updating?

**Comment by Tsun-hung** [comment]
Has the server been attacked?

**Comment by kityanhem** [comment]
158603eb VS  3f6c8dd8 236:198 (54.37%)

**Comment by gcp** [comment]
>158603eb VS 3f6c8dd8 236:198 (54.37%)

Normal result given that the PASS was exactly at 55%.

**Comment by l1t1** [comment]
again the weaker network is promoted
2018-04-24 11:05 
b908a080
VS 
3f6c8dd8
227 : 190 (54.44%) 417 / 400 fail

**Comment by roy7** [comment]
Was a bug in the submit-match overhaul. Fixed.

**Comment by l1t1** [comment]
in a sense of historical winrate ,gcp is right,
 b908a080 reached 0.55 about 260 games, then it never reach again.
158603eb reached 0.55 exactlly on 400 games, then it drops.

**Comment by hydrogenpi** [comment]
In this instance and other similar ones like it, to get to the actual 'truth' of which network is slightly the ever more stronger than the other would require both to be played out to at least 1000 match, and that is likely too time intensive esp. given the larger 15 blocks to be worth the while in terms of ROI. 

However what we do know for sure in instances like these is often there is two, three or even more days of time lost waiting for a final network that arguably may or may not even have a higher winrate. What we do know for sure, is that in these similar situations, the officially promoted network is actually SIGNIFICANTLY weaker in terms of the time-progression scale.  For example, the difference between a 55.00% and 54.64% is just 0.36%, I don't think anyone believes that on average the LZ project is only progressing at a rate of 0.12% or less per day. So to wait two or three days and end up with a nominal by the numbers same, weaker or even if ever so slightly stronger official network, is by the standards of time progression in the project, a significant net loss, this much is "for sure" in these and many other similar instances that have already repeatedly happened as of late (since LZ has gotten so much stronger and now is at that phrase of its progression curve etc) 

In everything else "time" is taken into account but it seems not here. For example when comparing 10b to 20b, it isn't enough for the 20b to get a 80%wr against the 10b, the time factor of the 20b being 5x slower has to be taken into account when deciding whether or not to promote it over the 10b. Another thing that could be seen as a compromise from the AGZ paper is the usage of smaller networks and then net2net bootstrapping to ever larger sizes on the way up. The downside of course is that its not a pure experiment and there could be complications, but the upside is that it saves a lot of "time" in the progression of the total pace of the project itself, which was the only plausible reason that it was implemented in the first place. Otherwise if "time progression curve" wasn't an issue, if how long it takes to get strong wasn't a factor, then no doubt we would have started with a 40 block in the first place from the very first game just like DeepMind did with AGZ!

Yet here we are missing the glaringly obvious thing, is that we are comparing fraction of a fraction of a percent yet don't realize or don't want to accept that the real truth is when days and days are lost, its self evident truth that the later network (if barely 55%) is way weaker!  

"Nothing would happen unless it was significantly stronger" does make sense. But then again, so does the converse. Nothing should happen unless it was significantly weaker either, by the same logic. When there is a 54.5%, what is the point in waiting 3 or more days just to finally get a 55.0%.

**Comment by l1t1** [comment]
[zeromatch.xlsx](https://github.com/gcp/leela-zero/files/1949220/zeromatch.xlsx)
b908a080 and 158603eb  vs 3f6c8dd8 moving winrate

**Comment by l1t1** [comment]
I estimated the winrate and time 's relationship few days ago, but I can't find it now.
simply (1+1/n)^n ‘s max_value in a peroid，depend on n
