### ISSUE TITLE
Big winrate variation in a USE_HALF game

### ISSUE THREAD

**Issue by Splee99** [gcp/leela-zero#1282]
I have downloaded the next branch and compiled in MSVC with the USE_HALF (half precision floating point calculation?) option. The speed is increased for sure which contributes to the playing strength. However, when I run a 3 handicap game of LZ vs Hiratuka, the winrate jumped up and down in the middle of the game from 47% to 5% gradually then back to 63% abruptly. Unfortunately I didn't know how to save the log (now I know). Anyway the game is here:
http://eidogo.com/#4eiV2XZB

The winrate variation starts after move 171. Also when I reviewed the game with the released version I didn't see big winrate variation for the same game. I'll try to run more games and see if such situation appears again.

**Comment by MartinDevelopment** [comment]
Was it something comparable to this or was it even worse? I've seen this quite often under 15k visits.

![log1](https://user-images.githubusercontent.com/11178682/39401039-9cfbfe1a-4b3c-11e8-92be-f937e8334173.png)

**Comment by Splee99** [comment]
I'm running another game now and will upload the log shortly. The problem in my case is that the winrate drops to single digit and could be below the resign threshold. It would be unfortunate if it was caused by the quantization noise.

**Comment by MartinDevelopment** [comment]
@Splee99 Homany playouts did you use at moev 171? I am currently running a test on CPU-Only and the winrate at move 191 just keeps dropping from ~50% at 3k playouts to ~21% at 35k playouts and it is still dropping slowly.

**Comment by Splee99** [comment]
It's good that you got some hint from this. I think it's hard to understand why the win rate could go from close to 50% to 4% in such short time.

**Comment by hydrogenpi** [comment]
does it have negative impact on actual winrate of a game other than early resign threshold

**Comment by Hersmunch** [comment]
If the `!defined(USE_HALF)` is removed from `#if defined(USE_BLAS) && defined(USE_OPENCL) && !defined(USE_HALF)` in config.h does the self-check report an OpenCL calculation error?
The checking isn't performed often so it may take a lot of playouts before any issue is seen.

**Comment by Splee99** [comment]
@hydrogenpi I would think the best move chosen by LZ is based somehow on the winrate. If the winrate calculation is not that accurate it may affect the move selection.
@WesleyDeng I didn't observe such delusion for the similar game setting when using the normal precision (released) LZ.
@Hersmunch I will try to remove that and see what happens.

**Comment by Splee99** [comment]
@Hersmunch I got a compiler error:
```text
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'void Network::forward_cpu(const std::vector<float,std::allocator<_Ty>> &,std::vector<_Ty,std::allocator<_Ty>> &,std::vector<_Ty,std::allocator<_Ty>> &)': cannot convert argument 1 from 'std::vector<net_t,std::allocator<_Ty>>' to 'const std::vector<float,std::allocator<_Ty>> &'	leela-zero	G:\leelaZ0.13\leela-zero-next\src\Network.cpp	935

**Comment by Hersmunch** [comment]
@Splee99, I guess that is why the self-check isn't compiled in :smile:
I'm guessing getting numbers for potential speed-up for `USE_HALF` gives an indication of whether fixing the cpu code is worth doing.

**Comment by Splee99** [comment]
@Hersmunch I'm not familiar with the code. Hope someone can fix that. I'm very confused though. Isn't that piece of code always there and we did check the Opencl somehow?

**Comment by Hersmunch** [comment]
The self-check has been there quite a while but the `USE_HALF` code has only recently been added.

**Comment by TFiFiE** [comment]
The reason self-check is turned off with `USE_HALF` is probably because the CPU code makes use of BLAS functions that take single-precision values.

**Comment by ihavnoid** [comment]
When I developed fp16 I did have a version with self-check half precision.  The thing is, since the CPU code was single precision and GPU being half precision, the self check did fail eventually (with margins like 10+ percents, or 100+ percent when dealing with very small numbers) so I sort of figured out that self check isn't going to really work here if we are comparing with CPU numbers.  Failures were relatively uncommon with a large margin, though, and since the tree search algorithm should be resistant to some errors on some cases I simply thought that the intermittent errors might worth the speed.   (The whole point of neural nets is that it still has a lot of training error, what we need is something typically right, anyway.)

So yes if somebody would want to develop a self-check, I think we have to measure the average errors rather than the worst-case error.

**Comment by Splee99** [comment]
I have deleted the old precompiled headers and did a rebuild. Using the new weight I don't see the big win rate fluctuation any more. I'll keep running the tests. Not sure what exactly happened.

**Comment by gcp** [comment]
It's not entirely clear from this discussion whether the winrate fluctuation was actually related to USE_HALF or just a difficult position for Leela...

**Comment by gcp** [comment]
> I think it is just there for testing purposes currently and not expected for use otherwise.

The benchmark results show a nice speedup on many machines, so it would be nice if it could be enabled. But that does need some way to do a self-check. I think the results from @ihavnoid's initial test show that at fixed playouts strength loss is negligible, and at fixed time it becomes stronger due to speedups.

**Comment by Splee99** [comment]
It appears that the winrate fluctuations in the game above was due to misreading of life and death of the upper black group and has nothing to do with the half precision. Unfortunately the single precision with the latest weight still does the same misreading. So case closed.
