### ISSUE TITLE
Using mini-tournament

### ISSUE THREAD

**Issue by FransFaase** [gcp/leela-zero#1286]
Now that the winning scores are getting close to 50%, I wonder whether it would be a good idea to make use of mini-tournaments between the top n (for example, 4) networks. Whenever a new network is generated, the weakest network is replaced by the new network. This makes it less risky to replace a network which appears only slightly stronger than the current network, while after larger number of games it would appear to be weaker. It also prevents the case where the newer network only slightly wins from the current network, because it hits upon a particular weaknest of the current network, but has a serious weakness in another area.

**Comment by l1t1** [comment]
but the method isn't documented in alphogo paper

**Comment by MaxMaki** [comment]
There's nothing wrong with the current training and gating.  We're getting networks at a rather fast pace, since none of the networks have generated more than 90k games, and most them only around 50k games. 

Getting more stronger networks is not a question of always promote, changing gating, or anything like that. We need to generate new stronger games in order to progress. Didn't the AlphaGo Zero paper say that they tested every 25.000 games?

Self-play games are what makes the strength progress, without games no amount of always promote or tournament promotions or low gating will make any difference. We won't suddenly get a bunch of stronger networks from a Zero approach unless at the same time game generation drastically increases.

**Comment by hydrogenpi** [comment]
so... how to get more volunteer clients

**Comment by tychota** [comment]
@hydrogenpi : promoting https://github.com/gcp/leela-zero/pull/1245/files can help. 

Google Collab as one K80 Gpu available so it is for me around 5s/move, which is 5 times faster that my mac + I can use my mac.

**Comment by hydrogenpi** [comment]
Doesnt Collab throttle and cap after a while? on chess project their went down to only 5000 games per day from 20000 games per day.
