### ISSUE TITLE
LZ 0.14 decides white wins W+7.5 after only 34 moves (self-play bug)

### ISSUE THREAD

**Issue by stephenmartindale** [gcp/leela-zero#1366]
Check out the linked game: [self-play game for 2fb02cfe](http://eidogo.com/#448KQxwV6:0,34)

I'm not sure why the game ended -- perhaps it was just a coincidence caused by noise -- but I'm pretty impressed that Leela Zero can count it so accurately at such an early stage. W+7.5, apparently.

Most professional players probably couldn't count like that.

Is it a bug or just noise? If the latter, perhaps allowing noise to end the game by two passes is a little too much.

**Comment by stephenmartindale** [comment]
@gcp Sorry for reporting an *invalid* issue. To educate myself, why is it invalid?

**Comment by jkiliani** [comment]
It's invalid because the same thing was reported many times before, during earlier stages of LZ training. Noise+temperature can sometimes cause black to pass early in the game. White can then immediately pass back and win by komi due to Tromp-Taylor scoring. I hope this makes sense, if not please read up on how Tromp-Taylor works.
