### ISSUE TITLE
why the lz136 vs elf winrate lower than 73a12e72

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1389]
62b5417b VS  b6337c69 94.57%

62b5417b VS  73a12e72 93.27%

**Comment by Matuiss2** [comment]
...the difference from both is too big, these victories are all about luck(to get ladders)

**Comment by l1t1** [comment]
![canvas510](https://user-images.githubusercontent.com/23301704/39844750-4d6feeba-5424-11e8-8d37-dd99a27d020d.png)
one elf network has two different eol

**Comment by hydrogenpi** [comment]
we need to do a match test between latest 15b and ecab network 131 to see that there hasnt been a regression in strength

**Comment by dzhurak** [comment]
As been said the difference in strength is very big and thus you shouldn't make conclusions on the score. 20 games out of 400 is nothing. Pure luck. Let's wait few more promotions and test it again.

**Comment by AlexanderMisel** [comment]
I think we should be more careful at promoting networks. An idea is in my mind that a network beats both the 2 best networks before it can be promoted.

A beats B, and B beats C, doesn't mean A beats C.

**Comment by hydrogenpi** [comment]
Now that we are entering the arena of "unknown unknowns" when there is option to test a known, known, why would it be the case that it is not to be exercised. Taking conservative approach and the lower bound of 55% gating threshold, at five new promotions, that should be a WR% different of between net 131 and net 136 etc... Since these nets are not to far distant in strength, it could be a good transitivity to test to see if they hold up to scrutiny and/or to see whether or not there has been a effective net total regession.
