### ISSUE TITLE
Introduce a new format for networks

### ISSUE THREAD

**Issue by isty2e** [gcp/leela-zero#1406]
With ELF and PheonixGo open sourced, LZ might serve as an easily accessible and easy-to-run client for those networks. However, the input planes, architecture, or the definition of output can differ slightly, and modifying such details every time can be inefficient and sometimes confusing.

Instead, what about defining a new, flexible format for networks which can cover these details? The new format can be designed to include:
* Input planes with ordering
* Architecture specs, including order of layers, barchnorm details (beta, gamma, etc.), and possibly activation (LeakyReLU could've been used for ELF)
* Definition of the outputs (to avoid LZ vs. ELF value output conflict, for example) 
The details of the format is to be discussed, but one might consider using YAML-like syntax for those details, for example:

```
input:
- history_player_-1
- history_player_-2
- history_opponent_-1
- history_opponent_-2
- black_plane
- white_plane
architecture:
- tower
- - policy
  - value
tower:
- conv0
...
```

**Comment by Ka-zam** [comment]
Choosing a standard format should be the first choice.

**Comment by isty2e** [comment]
But for this case, shouldn't the format be self-contained, specifying the input and range of the output, etc.?

**Comment by gcp** [comment]
The main problem here seems to be that you're trying to provide some kind of flexibility without having any idea what you are trying to be flexible towards. Imagine someone implements all this. Then someone releases an improved net and it turns out to be using ELU units. 

Leela Zero is not a general purpose neural net package and this seems completely out of scope. If you want this kind of flexibility it's better to back the engine with PyTorch or TF or whatever.
