### ISSUE TITLE
Mutex stuff

### ISSUE THREAD

**Issue by OmnipotentEntity** [gcp/leela-zero#1431]
I was poking about in the code and I noticed a few things that were a bit weird.

In UTCNode.h `m_nodemutex` is not marked as `mutable`.  Typically, (at least in past projects I've worked on) the mutex is marked as `mutable` so that it can be used without a `const_cast` in a `const` function.  The reasoning is because locking and unlocking a mutex should always be a logically `const` operation, because it does not affect the external behavior of the class.

The mutex is not standard.  I was curious as to the reasoning behind this.  (As `std::mutex` is a thing now.)

Finally, I looked at the implementation of the mutex, and the implementation is TS rather than TTS, is this an intentional design decision because you expect this mutex to experience very short locks with low levels of contention?  Because if this isn't the case, then TTS lowers memory contention.

**Comment by gcp** [comment]
The mutex isn't standard because in many C++ libraries a mutex is a very heavyweight object and we have one per node. At some point hashed locking was proposed as a solution for this, but IMHO that's just worse in terms of complexity than per node spinlocks. I think I didn't use atomic_flag because it's harder to add some debug checks into that, compared to a custom class.

Note that other parts of the code use regular mutexes.

As for mutable, the reason is that you don't need to take the lock if you want to inspect most variables. They're atomics. So if you're going to take the lock, it's typically going to be because you're doing more invasive changes.

**Comment by roy7** [comment]
Part of where this came up is when I added a function to calculate a value and return it and I needed a lock to be sure it was thread safe. No problem. But I was using this value in another function elsewhere that I was trying to lock, so that caused a deadlock situation. So I removed one of the locks but I was also getting conflicts that I can't lock within a 'const'. So I removed the const as well.

The const makes since I'm not changing anything, but I need the lock since I'm reading multiple values that could change.

But I wonder... could I have simply make a single std::atomic struct object? So no lock required and I'd get all of the values I needed at once instead of having multiple separate atomic variables?

**Comment by gcp** [comment]
>a single std::atomic struct object? So no lock required 

No, there's only a few things that are atomic (processor dependent), and the others are emulated with a lock anyway.

**Comment by gcp** [comment]
>I need the lock since I'm reading multiple values that could change.

Do you have a more concrete example?

**Comment by roy7** [comment]
I added `std::atomic<double> m_variance{0.0}` to UCTNode.h. I use that incrementally as we search so I can get real variance at any time without actually storing all of the search results. I replaced update() with:

```Js
void UCTNode::update(float eval) {
    LOCK(get_mutex(), lock);

    if (get_visits()) {
        const auto delta = eval - get_blackevals() / get_visits();
        m_visits++;
        accumulate_eval(eval);
        const auto delta2 = eval - get_blackevals() / get_visits();
        atomic_add(m_variance, delta * delta2);
    } else {
        m_visits++;
        accumulate_eval(eval);
    }
}
```

My wrapper function is:

```Js
double UCTNode::get_variance() {
    LOCK(get_mutex(), lock);

    return get_visits() > 1 ? m_variance / (get_visits() - 1) : 0;
}
```

Because visits and m_variance could change separately in different threads.

In update() if I moved m_blackevals and variance both into an atomic struct in a similar way to `std::atomic<Status> m_status{ACTIVE}` then I could fetch them both, use them as needed, and write them both, thread-safe. Right? Without an actual LOCK call. get_variance() still needs the lock unless I also moved m_visits into the struct, so I could do a single assignment to a temp variance and get both m_visits and m_variance in a thread safe way.

**Comment by gcp** [comment]
update can't be const because it's modifying things, so I assume that isn't the problem.

In get_variance, you can just cache a single get_visits() call (no lock needed) and then use the cached value to decide what to return. No lock needed.

Aside from that, whether you actually need the lock in update() or not is trickier. Note that if you add it, your traversal to the root of the search tree now blocks all threads every time you try to update node statistics, which is bad for scaling. 

The atomic_add's make it unnecessary to lock the m_variance access. You can cache the visit count (or blackevals) at the start if needed to get a consistent view. I think that would allow the calculation to work but I'm not 100% sure (i.e. I think the minor errors from using the cached values won't cause the calculation error to be too large).

>atomic struct in a similar way to std::atomic<Status> m_status{ACTIVE}

Note that that is a enum that maps to an integer, not a struct.

**Comment by roy7** [comment]
> In get_variance, you can just cache a single get_visits() call (no lock needed) and then use the cached value to decide what to return. No lock needed.

Can't another thread update m_visits and m_variance between the time I call get_visits() and calculate my result? I have my cached m_visits, but m_variance isn't cached yet. To cache both with no chance of thread issues, I'd do something like:

struct SearchStats
{
    int m_visits = 0;
    double m_variance = 0.0;
};

std::atomic<SearchStats> m_searchstats;

Then make a cached copy of the struct itself, giving me both values at same time thread-safe?

**Comment by roy7** [comment]
I'm hijacking this issue, sorry. I should stick with what I know and LOCK it and if it ever go to the point of the code being usable by someone, someone with C++ skills could refactor/optimize.

**Comment by gcp** [comment]
>I assume if you have an atomic struct there's a way to thread-safe increment multiple portions of the struct.

No.

**Comment by OmnipotentEntity** [comment]
Another use case that I believe @roy7 was running into was reading from the children of a node (to get statistical information in a `const` manner) and another thread coming along and modifying the vector invalidating his iterator.  This would require locking the mutex while walking the structure (or somehow avoiding the iterator invalidating operation, or keeping that information around in memory to avoid the O(n) walk of the structure, either of which might be better).

However, as it stands, as far as I can tell, there is no use case currently within the code base for making the mutex `mutable`, and if one is needed later just simply adding it isn't a big deal.

**Comment by roy7** [comment]
I solved that issue by no longer sorting in the select() function. I didn't realize when the children are originally set up they are already linked in policy order. So I leave that ordering alone, segfault solved. Thanks to @OmnipotentEntity for debugging that for me.

> No. This requires transactional memory, basically.

Ok so I if I was using an atomic struct I could safely read the info I needed, but when it comes to writing it, I'd need to make a helper function that gets a full lock and increments all 3 numbers. I doubt I'll take it this far, but we'll see.
