### ISSUE TITLE
0.15 release for win64 contains Qt5Core.dll for win32

### ISSUE THREAD

**Issue by Hersmunch** [gcp/leela-zero#1458]
Validation.exe crashes when run alongside the wrong Qt5Core.dll

**Comment by Hersmunch** [comment]
The same is true for win64 cpu only. win32 cpu only is missing quite a few files.

**Comment by l1t1** [comment]
win32 cpu version works well

**Comment by gcp** [comment]
The autogtp and validation binaries are 32-bit as there is no benefit whatsoever to having them 64-bit. (Unlike Leela itself, which can use improved AVX kernels).

>win32 cpu only is missing quite a few files.

This is intentional. If you only have a 32-bit OS and no GPU you are likely way too slow to run AutoGTP in a meaningful manner.

>Validation.exe crashes when run alongside the wrong Qt5Core.dll

I don't understand. The bundled validation crashes with the bundled DLL? Or do you mean something else?

**Comment by Hersmunch** [comment]
Ah. It was because I built validation for 64bit :)
Thanks for the info
