### ISSUE TITLE
Hardware question

### ISSUE THREAD

**Issue by PhilipFRipper** [gcp/leela-zero#1462]
Would specialist mining hardware like the Antminer work as efficiently for AI as it does mining?  Is that an additional hardware option?

**Comment by l1t1** [comment]
my poor gtx 730 also can run

**Comment by roy7** [comment]
Well you can't use Antminers because they are ASICs designed for cryptomining. That means they can only do a single thing, faster than GPU, but no flexibility at all.

In theory one could make neural network ASICs that would be faster than GPUs, but you'd only be able to do exactly what the ASIC was designed for and it could never do something different (like if you wanted to change NN architecture).

I did find an article talking about this idea: https://www.forbes.com/sites/moorinsights/2017/08/04/will-asic-chips-become-the-next-big-thing-in-ai/

**Comment by PhilipFRipper** [comment]
I meant as an alternative to graphics cards.

**Comment by PhilipFRipper** [comment]
Thank you @roy7

**Comment by alreadydone** [comment]
I think TPUs are considered a sort of ASIC.

**Comment by gcp** [comment]
Yes, TPUs, Tensor Cores etc are basically specific hardware for neural networks, though still generic enough to be usable for different network architectures.
