### ISSUE TITLE
Could we train a small board 9*9 leela9zero to a god ?Maybe it will very fast !

### ISSUE THREAD

**Issue by tanguocn** [gcp/leela-zero#147]
Deer leelazero designer：
Could we train a small board 9*9 leela9zero to a god first ?Maybe it will very fast !

And 9 board weiqi is very  popular too.  
Maybe we can train a god of 9*9 board Leela9zero in a few days and we can validate whether the method we used for 19*19 board is right very soon.

**Comment by earthengine** [comment]
Actually, I am thinking something more general. Instead of a tri-state for each board point (black, white, empty), we can make it quasi-state (black, white,empty,out-of-boundry). In this case, the same board will be suitable for both big and small boards. In addition to that, we can parameterize the rules to be inputs, so the neural network can aware of rule variations. The resulting trained network will then be more flexible to rule/board changes.

The only concern is that this will invalidate the currently trained network. So it is a big decision to make whether to start again from scratch.

**Comment by tanguocn** [comment]
It's a good idea to train a general  neural network that can play chess at any size, but as far as I know, the existing technology is not working and it is hard to achieve a general soft purpose. So the best thing about doing this is to train a small checker board neural network by itself. The biggest advantage of doing this is that because of the drastic reduction in computation, the training time that needs to be done is very short, maybe a week or two is needed to complete the neural network training, Verify that this training method is feasible. If you train six months or a year to find the original model design flaws, then start again, will waste a lot of time maybe six months or one year. Only if the training on a small chessboard has succeeded, it shows that this method and direction are roughly correct, and can avoid detours and eliminate major mistakes in advance. And if training out the go-go god on the small chessboard is also a great breakthrough, Google's Alpha zero does not seem to play the small chessboard.

**Comment by gcp** [comment]
There are several people looking at this, one of them has a branch of Leela Zero that works on 9x9.
