### ISSUE TITLE
Wrong winner ?

### ISSUE THREAD

**Issue by wonderingabout** [gcp/leela-zero#1473]
hi everyone,

in this game, it shows b+6.5 : 
http://zero.sjeng.org/viewmatch/cd5bc612e6b6cd0f84540c2ec3619b164d6df49b529c41bae845782b24b6b50f?viewer=wgo

but removing dead stones, the score becomes w+0.5

![lz score](https://user-images.githubusercontent.com/38690718/40417930-4745e348-5e81-11e8-96f0-60cc0b946808.PNG)

so black wins instead of white ?
am i missing something?

**Comment by gcp** [comment]
The games use Tromp Taylor scoring.

**Comment by Eddh** [comment]
It's not dame but a seki. I'm not really sure what the difference between taylor tromp and area scoring should be in that case. Does tromp taylor not lead to a w+0.5 score once dead stones are captured here ?

**Comment by gcp** [comment]
Hmm, true. Could also be a case where t=1 blundered, and resigned, before playing the move. (Maybe in the seki?)

**Comment by grolich** [comment]
> Could also be a case where t=1 blundered, and resigned, before playing the move. (Maybe in the seki?)

Black didn't resign. both players passed. So I guess black's pass was likely a T=1 blunder...

**Comment by gcp** [comment]
Right :-)

**Comment by roy7** [comment]
For cases where there's a resignation after a randomized move, would it be better to do the resign check at the start of the turn or not use the resign check if a move was using noise? My concern is that you might be in a won position, a random move cause you to lose, but the border states still looks one. And so for training targets the win and losses reversed to what the real situation is.

Or maybe a simple approach is the only resign if the best move is less than resign threshold, not the move chosen.

**Comment by grolich** [comment]
hmmm but this game is a match game. No randomness at all from the command line (forgot the -t was "threads" and not temperature for a sec).

with 3200 visits, and passing leads to a 100% loss, how would this happen?

**Comment by gcp** [comment]
>would it be better to do the resign check at the start of the turn or not use the resign check if a move was using noise?

It doesn't really make any difference at all because board positions are randomly sampled, so the "entire game" has the wrong result. Fixing the last move won't affect the 400 or so before it.

**Comment by grolich** [comment]
Also - black was the last one to pass, so he didn't even need to consider white passing to know it's 100% losing. So it even seems stranger for a game with no randomness. Even if training with T=1 made endgame passing suspect, the first visit to the pass node should mark it as the worst possible value...
anything I'm missing here?

**Comment by gcp** [comment]
>black was the last one to pass, so he didn't even need to consider white passing to know it's 100% losing

100% winning.

If black passes, he wins on the spot with B+6.5. Which is the game result.

**Comment by gcp** [comment]
This is white's POV, not necessarily the same network:

```
Leela: genmove w
Thinking at most 90.0 seconds...
NN eval=0.670908
88.8s left, stopping early.

  F4 ->    1496 (V: 93.16%) (N: 48.38%) PV: F4 Q5 E2 P1 F1 R5 D1 Q6 B1 T3 pass pass

  E2 ->     166 (V: 89.81%) (N: 21.24%) PV: E2 P1 F4 Q5 F1 R5 D1 Q6 B1 T3 pass pass
  B1 ->     139 (V: 92.26%) (N:  6.56%) PV: B1 Q5 F4 R5 E2 Q6 D1 P1 F1 T3
  F1 ->      32 (V: 89.46%) (N:  4.43%) PV: F1 Q5 E2 P1 F4 R5 D1
  D1 ->      24 (V: 88.32%) (N:  4.09%) PV: D1 P1 F4 Q5 E2 R5 F1 Q6
pass ->       8 (V: 80.42%) (N:  3.29%) PV: pass Q5 F4 R5 E2
 L18 ->       6 (V: 81.03%) (N:  1.94%) PV: L18 Q5 F4 P1 E2
8.1 average depth, 12 max depth
1284 non leaf nodes, 1.26 average children
1872 visits, 152335 nodes, 1871 playouts, 1613 n/s
```

White did not understand that passing loses.

**Comment by roy7** [comment]
Ok so here's a more extreme idea. A random late game move that loses is no problem if we are losing anyway. But maybe when doing noise check, if our random move has a win rate under resign threshold but best move has a win rate over 50%, we don't take the random resign move?

Then again maybe best to not mess with a working system. And some noise in the value head is maybe why LZ is more open minded to handicap.

**Comment by grolich** [comment]
oh right. so white passed incorrectly.
So T=1 training messes the search sufficiently so that white doesn't even consider black passing after his pass with 3200 visits into that node. 

I guess that's not a problem with big matches on a strong computer (enough nodes and the search would see it), but it might mean this strategy (T=1) makes the pure network and low node search network a lot more error prone while it significantly raises the cap on normal/high node count searches (where noise gets effectively cancelled out or close to it). 

I wonder if a simple idea to use if this problem gets bigger and more troublesome could be to just use T=1 in some games and a lower T (or just in opening as was used originally) in others. Would pull the network values closer to optimal. 
However, it would probably slow down progress as this change may be responsible for the quick progress we've been having,

so ideas like that should probably be kept and stored in a temporarily unreachable closet until the problem becomes too big to accept :)

**Comment by gcp** [comment]
I am not sure why you think this has got anything to do with T=1.

**Comment by grolich** [comment]
> I am not sure why you think this has got anything to do with T=1.

The reason was the recent posts about LZ "forgetting how to pass" (although it's a bit extreme) and the seemingly reasonable arguments about how T=1 could cause problems there. Even though it's different here (the thoughts there were mostly on cases where everything is almost certainly (e.g. ~99.x%) winning (or alternatively, everything loses), even a pass, so with T=1 it becomes harder to avoid selection of certain moves.

This is obviously a different case, since the result itself changes;

For some reason it seemed like T=1 could also insert more randomness into cases such as this one, but I have to admit it might not have anything to do with that at all...

After all, the pure net always was vulnerable to occasional blunders (it sometimes misses inescapable ataris when I force it into (what seems to me like difficult) fights, but even a minimal search of several visits (sometimes as low as 2-4 visits) tends to correct it in most cases),

so I guess there could be rarer situations in which a 3200 visit search wouldn't be able to avoid a blunder as well... 

Apologies for not noticing this is an entirely different case than the ones I referred to.

**Comment by wonderingabout** [comment]
i was afk for a while.

from what i see : 
- until move 252 : the game is normal
- from 253 to 271 : both players start capturing dead stones
- at 272 : white passes instead of capturing the remaining dead stones, and score is alread w+0.5 in chinese rules.

So, white passing at 272 is not a mistake, because white is the winner of the game if we go to scoring.
And black pass is not a mistake either, because score is w+0.5 in chinese rules

However, the scoring doesnt remove dead stones, leading to b+6.5.
So, if both players manually captured all dead stones, the correct winner would be white by w+0.5

Shouldnt bots capture all dead stones in endgame ? Since its chinese rules, the score doesnt change, but it avoids mistakes .

![lz score 2](https://user-images.githubusercontent.com/38690718/40445093-70c13a5c-5ecb-11e8-84a5-fbbbe28bbc72.PNG)
