### ISSUE TITLE
Scored results don't count prisoners on the board

### ISSUE THREAD

**Issue by nutpen85** [gcp/leela-zero#1551]
I looked at some recent match games between d0187996 and e0d2cc1a. I wanted to take a look at close matches, so the ones that have a score instead of a resign. The game 55e570b388059f1f332c0dc2f87de23f was scored W+17.5. First of all I wondered, why B did not resign. So I looked at the result. Actually it is only W+0.5, if you remove dead stones on the board properly. But without removing it is W+17.5. Is this (false) result on purpose as it is or is it a bug?

**Comment by grolich** [comment]
the game hash in your post doesn't work and seems to be only partially pasted, so I will have to guess what you meant, since it seems related to a common question.

Leela scores games according to tromp-taylor rules. In these rules - any stone that has not been physically removed from the board stays. 
as it turns out, knowing who will win in tromp taylor scoring is good enough to know how to play according to Chinese rules (more specifically, computers trained on tt scoring play Chinese scoring just as well).

Leela Zero (like AlphaGo Zero), was trained to only care about winning percentage, not about the final score, so 100% of losing by half a point and 100% of losing by 17.5 points are the same to it. 

If I misunderstood the problem, please try to link the game here again :)

**Comment by nutpen85** [comment]
Thank you for very comprehensive answer and sorry for the short versions of hashes.

I think, I'm aware of the differences between tromp-taylor rules and other types of counting and that only the result in a sense of win or loss is important. Looking at more games it seems, that the winning player simply does not capture remaining stones, if it does not change the result. I assume this was also meant in another issue, which I thought to be different.

STILL, there is one match, where the result seems to change. To make sure, I put the complete link here:
http://zero.sjeng.org/viewmatch/259765f2a6e578fdbbbf4dadec8bbcf5ca9a121650eac0a78c2dca1c275cb3b1?viewer=wgo
The "official" result is W+17.5. But if you go to counting mode and remove all dead stones (lower left is seki) it becomes B+1.5.
However, such a case seems to be very rare and should have a very tiny impact on the winner between the two networks.

**Comment by gcp** [comment]
Sometimes the networks miscount or "blunder" into a pass.
