### ISSUE TITLE
why some resign games have over 360 moves

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1587]
Game | Win Rate | Match Hash | Winner | Score | Move Count | Duration | Download | Client | Version
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
192 | 59.90% | 951ff653b9ddceed7181d12d481be1b6 | c010f034 | B+Resign | 380 | 35.5 minutes | sgf | 52 | 16
301 | 62.46% | 2af5d0d53dca852fca22ff6b9e4df9e4 | c010f034 | W+0.5 | 368 | 15.4 minutes | sgf | 5 | 16
70 | 61.43% | c6c04b94f10626266d6990bf8c834a8e | c010f034 | W+Resign | 363 | 31.8 minutes | sgf | 35 | 16
65 | 61.54% | 7c67922e41893f21c300aeeb58067666 | c010f034 | W+Resign | 361 | 17.1 minutes | sgf | 37 | 16
188 | 59.57% | f53ddfb388e80d487381630c46c8ddaa | c010f034 | W+Resign | 361 | 24.1 minutes | sgf | 8 | 16

**Comment by alreadydone** [comment]
Wow these are interesting games, remarkably close endgames whose results sometimes hinge upon a simple ko (单片劫) or several ko's through the whole game, which is why the games are so long.
Game 301 has two seki's and W+0.5 is the correct result.
Game 70 is W+2.5
Game 65 and 188 are W+0.5
Game 192 is B+1.5

**Comment by alreadydone** [comment]
Just to add one more entertaining and confusing (because of randomness) long **self-play** game with double/quadruple ko, courtesy of discoverer/commentator R2D2, owner of QQ group 163136292 (LZ selfplay appreciation group): http://eidogo.com/#2ASzoqkan (may need to set language = simplified Chinese in MultiGo to view comments)

**Comment by l1t1** [comment]
http://eidogo.com/#2ASzoqkan is good example @alreadydone

**Comment by gcp** [comment]
"why not"
