### ISSUE TITLE
Komi 7.5 is too big

### ISSUE THREAD

**Issue by Nefeste** [gcp/leela-zero#1592]
I think, that komi 7.5 is too big for a game of Go. More likely fair komi should be 4.5 or 5.5. Can we do an investigation using millions of sgf's of self-play of Leela-zero to prove which komi should be considered as a fair and equal position with 50% of winning if both players are an equal strength?
All fuseki and joseki knowledge, developing by Leela-zero, can be wrong due to this critical human-knowledge parameter involved.

**Comment by wonderingabout** [comment]
well with 7.5 komi in chinese rules its known that white has a bit higher winrate, but if you lower it to 6.5 komi in chinese rules then wouldnt black have a higher winrate ?
also 6.5 vs 7.5 doesnt dramatically change the way of playing a game, there are plenty ways to catch or not catch a point, only for highest level players (bots) does it matter that much, but there is still a lot of room even among pro players to catch up that 1 point.
think about how much stronger bots are from top pros, so you can see even at top pro level its not dramatic

**Comment by nutpen85** [comment]
In generell a komi of 7 is considered to be the right Komi under Chinese rules (source: https://senseis.xmp.net/?Komi ). And 7.5 helps avoiding Jigo (draws).
In addition, it is not so easy to simply analyze our set of some million games for perfect Komi. LZ is far from playing on a level, which is sufficient to do this analysis. And many games were even played with a weaker LZ in training mode.

**Comment by gcp** [comment]
Completely irrelevant to this project.

**Comment by y-ich** [comment]
The recent weight (#242) shows that black winrate at the initial position is 42.8%.
And KataGo v1.1 indicates 1 moku of komi corresponds to 3 points of winrate in the opening.
It may be about time that Go AIs suggest 5.5 as fair komi to professionals.

I think that Leela Zero project is going to keep komi 7.5, but if the final result will show huge advantage of white at the initial position, the final weight may be far from ideal.
(because God must like even games.)

I wonder why AlphaGo Master (AlphaGo Teach) shows 46-47% winrate at the initial position.
She is almost as strong as AlphaGo Zero 40b.
And I have no idea what percentage AlphaGo Zero 40b shows at the initial position.

Thanks.

**Comment by Sadaharu2624** [comment]
I think FineArt from China shows that Black's initial percentage is close to 40%, but they still kept the komi at 7.5.

I wonder how low must the percentage be before they will consider changing the official komi...

**Comment by y-ich** [comment]
FineArt's main purpose is now for training Chinese professionals.
I am not sure whether the developers suggested fair komi to professionals but I think that they keep komi 7.5 until Chinese professionals change the rule.
