### ISSUE TITLE
Autogp crash on Windows XP 64

### ISSUE THREAD

**Issue by Cabu** [gcp/leela-zero#1616]
When starting autoGP i receive the following error:
The procedure entry point CancelIoEx could not be located in the dynamic library KERNEL32.dll.

**Comment by l1t1** [comment]
windows 2003 r2 win2018 also error

**Comment by gcp** [comment]
Windows XP support needs a lot of special care these days in all kinds of dependencies because it's not supported by regular toolchains.

Also, the talk about AutoGTP implies that one is trying to connect such a Windows XP machine (long unsupported by security patches!) to the internet, which I can only disrecommend to the utmost.

Maybe someone can build Windows XP binaries but I do not think it is worth our effort to support at this point.
