### ISSUE TITLE
 4f6f0b3d's winrate never down 0.51, but failed

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1619]
http://zero.sjeng.org/match-games/5b4836932f06263c66be95c2

Game | Win Rate | Match Hash | Winner | Score | Move Count | Duration | Download | Client | Version
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
321 | 51.71% | 33ec1fa17b2501f56c4f1c5aef0b742c | 834f35fa | W+Resign | 251 | 7.4 minutes | sgf | 3 | 16
353 | 51.84% | e4aa1d2ce0726743fcbab30a9d854844 | 834f35fa | B+Resign | 210 | 12.8 minutes | sgf | 100 | 16
351 | 51.85% | 7435c7dd0e3bab5c64de2c8528644ef7 | 834f35fa | B+1.5 | 323 | 21.4 minutes | sgf | 93 | 16
322 | 51.86% | 051b283d4202bbf9b5723a58ad382774 | 4f6f0b3d | W+Resign | 289 | 20.3 minutes | sgf | 95 | 16
320 | 51.88% | 10ca0327ed3dae8285508a698dfa0b99 | 834f35fa | B+Resign | 300 | 7.8 minutes | sgf | 43 | 16

**Comment by jkiliani** [comment]
And your point is... ? Of course it failed, since it never reached an SPRT pass, or 55% at 400+ games.

**Comment by gjm11** [comment]
As a general point, I would strongly encourage people submitting issues here to _be clear and explicit_ about what problem they've found or what thing they suggest should be done differently.

"This network's winrate was never below 51% but it didn't pass" isn't, on the face of it, a problem. If you think it's a problem, you need to say why. What did you hope would be different and why?

So, e.g., you could say something like this: "This network had a winrate above 51% for the whole of its match. Surely that should be good enough evidence of its strength and networks that achieve this should be promoted." That's an actual argument that can actually be engaged with. (One answer, for what it's worth, is that how much evidence a given sequence of wins and losses is doesn't depend on what order they come in, so a network that ends up at about 52% having never gone below 51% is not prima facie any stronger than a network that ends up at about 52% having oscillated wildly between 47% and 57%.) But when all you do is to present a table with a few results in it and say "this network failed", you're making readers _guess_ at your intentions and _guess_ at whatever arguments you were trying to make. Please, everyone, don't do that.

**Comment by qzq1** [comment]
Though I trust statistical formulas, I have nonetheless found it instructive to simulate match play, which has illustrated to me that there are many ways to get to a 55% win rate over 400 games.  

I know this has already been thrashed out elsewhere, but my simulations of gating has convinced me that even moving to 54% from 55% would likely increase the rate of improvement substantially.  It all depends on what the true parameters are, of course, but my mock up looks consistent with actual results and suggests that a 55% gate may be passing sub-50% networks on the order of 15% of the time, with a lower bound of around 47% on the 'true' win rate of passed networks.  Moving to 54% would increase the pass rate of sub-50% networks to about 23% of passes, but with almost no change on the lower bound - i.e., you'd get an increase in the number of inferior networks through the gate, but no significant degradation in how bad the erroneously passed networks are.  

But the increased rate of improvement is very large.  I simulated 10,000 progressive matches 100 times for a 55% gate and a 54% gate (as well as others), and the **minimum** improvement across 100 repetitions with a 54% gate was greater than the **maximum** improvement over 100 repetitions with a 55% gate.  Average improvement was 50% greater for a 54% gate than a 55% gate.  Obviously, the simulation parameters can be debated, but in the cases I've run there appears to be no downside at all of using 54% rather than 55% and a large upside.  (There is a further increase in average improvement at 53%, but not as stark, and the outcome range overlaps with that for 54%)

**Comment by PhilipFRipper** [comment]
Please god stop bringing this stupid thing up.  Go put it in the correct thread at minimum.

**Comment by qzq1** [comment]
Please god keep your charming comments to yourself.

**Comment by wonderingabout** [comment]
long story short story : if you want to lower gating, you need to increase number of games to keep statistical significance

for example to have the same significance at 55%/400 games you'd need something like : 
54%/550 games
53% 700 games
52% 1000 games
i didnt do the math but something arround that

**Comment by l1t1** [comment]
050375ce  http://zero.sjeng.org/match-games/5b4b11d52f06263c66c4c197
