### ISSUE TITLE
Chinese pro player says he use leela to review game

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1629]
https://sports.sina.cn/others/qipai/2018-07-18/detail-ihfnsvza2158707.d.html?from=wap

**Comment by diadorak** [comment]
A bit translation would be nice for majority of the readers here who do not read Chinese.

"Zhao Chenyu says during the game he could not decide if a move is good due to time limit. After game, he reviewed it with Leela and found that the move was pretty bad. 
...
With the quick advancement of Go AIs, pro players all review their games using AIs. AIs may not be very accurate in readings of local fights. But they are very useful in assessing the overall win rates." 

I guess the convenience of lizzie and mylizzie https://github.com/aerisnju/mylizzie is the main reason why they are not using Pheonix or ELF.

**Comment by gcp** [comment]
There's also the lack of annoying install dependencies: no TensorFlow, no cuDNN, etc.

**Comment by gcp** [comment]
If you let it think for 1 second on your CPU only it won't fight very well. Most of these pro players are not computer experts and they often don't understand the influence of hardware on the strength.

**Comment by tapsika** [comment]
>> AIs may not be very accurate in readings of local fights.
>
> That's a pretty weird statement. It's hard to argue that they are weak at anything if AI's can give handicap to pros.

Even strong players have weaker and stronger points, and tactical reading is not the strongest point of bots (if a key move gets low policy value it will likely get overlooked even with a lot of search).

Handicap results only show that this effect is not big / frequent enough to compensate the global advantages of bots, especially since humans make a lot of tactical mistakes as well.

**Comment by lephis** [comment]
I am a Chinese and watching nearly everyday Go game videos with commentary by Chinese pro players. I can confirm that nearly all top level Chinese pro players are currently using Leela Zero for their training, and the most of them are using Lizzie interface. (In fact, they are all using Leela/Lizzie at home; and if possible, using Fine Art in the training rooms of the Chinese Go Association as the most important reference, since Fine Art is now the strongest AI after the retirement of AlphaGo.)

**Comment by l1t1** [comment]
and many AI are used by other countries, eg elf, deepzengo and AQ
https://sports.sina.cn/intercept.d.html/?chname=sports&times=1
