### ISSUE TITLE
Game state contains "the 7 previous times"

### ISSUE THREAD

**Issue by bvandenbon** [gcp/leela-zero#1631]
The AlphaGo cheat sheet says that the game state contains the previous "7 times". Does that actually refer to the 7 previous moves/positions? 

Perhaps, the most important lesson to get strong at Go, is to accept/forget what is behind, and to only make decisions on the current state of the board. And it is really hard to learn how to NOT get distracted by what happened in previous moves. (By contrast: "looking back" is for reviews, in a real game you should only look ahead.)

So, I am wondering, is cheat sheet just wrong/unclear ? - Did I miss something ? - Or are we actually hard-coding Zero to be distracted by 14 layers of noise ?

**Comment by gcp** [comment]
The history is required to understand ko situations.

Of course a limited history doesn't handle all possible ko, but 7 moves back seems enough.

**Comment by bvandenbon** [comment]
Thanks  for clarifying that. I totally forgot about ko for a moment.
But, indeed that makes perfect sense.

I do feel tempted to deduct that it could be 2 times faster if it could just skip some of those layers.
But I guess you do need them. Such a pitty.

I will let it go. :-)
Thank you for enlighting me on this one.

**Comment by Ttl** [comment]
Decreasing the number of input planes only affects the speed of the first input convolution which is already the fastest. Even dropping to only 3 input layers wouldn't give even 1% speedup.

The first input convolution has 18 input channels and 192 output channels for 2x18x192x19x19x3x3 FLOPs = 22.4 MFLOps. 15 residual blocks have 2 convolutions each with 192 input and output channels for 2x2x15x192x192x19x19x3x3 FLOPs = 7186 MFLOPs. The number of input channels doesn't really have any measurable effect on the performance since residual blocks take the most of the computation time and the number of input planes doesn't affect the residual block FLOPs.
