### ISSUE TITLE
THIS IS NOT ACCEPTABLE

### ISSUE THREAD

**Issue by praetorian-guard2018** [gcp/leela-zero#1683]
### OR ELSE shutdown the server

**Comment by MartinDevelopment** [comment]
I don't mind if you have a opinion that you would like to express, however nobody is going to listen to your opinion if you do it in such an uncivilized manner.

**Comment by praetorian-guard2018** [comment]
ZERO real progress has been actually made since 

2018-07-18 14:36
--

**Comment by alphaladder** [comment]
Currently we are training elf v2 at 20 x256.Very funny.Where is our lz?

**Comment by BHydden** [comment]
Why don't you start your own server that trains 40 blocks if you feel that strongly about it.

**Comment by MartinDevelopment** [comment]
Leela Zero is not about creating the strongest go AI out there, it's about learning and having fun with creating an AI. If we make a strong AI in the progress of doing that it is just a nice side affect.

**Comment by Ishinoshita** [comment]
Your tone is indeed unacceptable. And immediately disqualify your opinion, whatever merit it may have (hard to say, however. I only hear barking).

**Comment by sheeryjay** [comment]
The progress since 2018-07-18 14:36 has been as follows :
Find out that 15x192 is saturated and probably close to impossible to improve anymore.
Find out that bjiyxo's 20x256 work, but are hard to learn from
Find out that we probably have to high LR
Start thinking that if lowering the LR, we might move to bjiyxo's 40x256.

What have you done in that time? How many pull requests did you code or merge? How many games has your PC generated?

This is about the rudest I have seen in the issues...
