### ISSUE TITLE
Perhaps there should be two main development branches?

### ISSUE THREAD

**Issue by Marcin1960** [gcp/leela-zero#1686]
Perhaps there should be two main development branches?

One focused on competing in net strength, going into 256x40 and further.

Second focused on creative improvements, using already existing best nets 192x15 without trying to make them stronger. 

Leela Zero at 192x15 is already much stronger than most of the strong human players. Branching out from this point like @alreadydone with his work on dynamic komi might be a good start:
https://github.com/alreadydone/lz

Possible objectives:

1. Good handling of handicaps up to 9 stones.
2. Making Leela Zero more human like, putting more weight on territory gain, etc ...
3. Perhaps making LZ stronger through the smarter algorithms as a bonus, **without making it a key objective**.
4. Making the game style more pleasing esthetically and more enjoyable. Many do enjoy playing go.
5. Exploring and discovering new ways, helping research and understanding of AI.

After all, it is what millions of players will love. 

On the other hand, the first branch will satisfy those who prefer to watch the competition.

**Comment by john45678** [comment]
Something similar to what the Leela Chess guys have done?

**Comment by Marcin1960** [comment]
@john45678 

What have they done?

**Comment by arondes** [comment]
Golaxy people said they have make a small trick in the algorithm that the AI is always aggressive even it has won a lot. The trick is to set extra komi penalty for AI if it has already led in the win rate.

**Comment by Marcin1960** [comment]
@arondes "The trick is to set extra komi penalty for AI if it has already led in the win rate."

I like it.

**Comment by gcp** [comment]
Leela Chess has a "main" server and a "test" server. The idea of the "test" server was to do a new from scratch run (with a few clients) with an optimized client, new parameters and net size, etc while still allowing the "main" server to make progress.

Regarding "development branches", the concern is that if they diverge too far without cross-merging, you end up with a branch that plays at high handicap, and one that is faster or stronger or has some GUI/GTP features or whatever, but not both. In this context I hope that at some point there are pull requests for the dynamic komi support, or at least to keep the branches closely in sync?

Leela Zero Chess already has this problem a bit. They have issues about features/bugs that have already been fixed here in Leela Zero, but because they rewrote the client they can no longer pull in the fixes and have to re-develop everything.

**Comment by Marcin1960** [comment]
@gcp "In this context I hope that at some point there are pull requests for the dynamic komi support, or at least to keep the branches closely in sync?"

I am quite sure that developers will borrow new ideas from each other.

Perhaps another branch should be named differently, like "Users Leela"?

**Comment by roy7** [comment]
Getting dynamic komi PR'ed into /next would be fabulous.

**Comment by Marcin1960** [comment]
@roy7: "Getting dynamic komi PR'ed into /next would be fabulous."

As an option, like "--dynamic-komi"? Possibly dynamic below 7.5, if too high winrate leads to slack moves?

**Comment by roy7** [comment]
Yeah. The two main things are better play at extreme win or loss edges, which helps all play. And dealing with handicap with 0.5 komi which basically is the same thing. Lots of people play my bots with handicap. I didn't want to try to have separate programs for normal and handicap play though.

**Comment by theleapfaith** [comment]
Very interesting idea. But our problem now is that we have very few resources. Not just computing resources but also human resources. In the past, people have proposed many interesting improvements, but we have almost never tried. If we make two branches, it will slow down our progress. Most participants want a stronger AI. As far as I know, some of the participants in China have used quite a few Google colab accounts, and these people are crazy about the powerful Leela. We are already too strong? We haven't won the championship yet, we are not strong enough.

**Comment by alphaladder** [comment]
I bet most people will join the queue of 40b other than 20b elf replicator.

**Comment by Marcin1960** [comment]
@alphaladder 
"If we make two branches, it will slow down our progress. Most participants want a stronger AI. As far as I know, some of the participants in China have used quite a few Google colab accounts, and these people are crazy about the powerful Leela."

Are you saying that those developers who are interested in AI and game Go, should not do things that might interfere with the majority "crazy about the powerful Leela", because "it will slow down our progress"?

I start to miss the days when Leela Zero was below 1 dan.

**Comment by Crazyeight101** [comment]
Adding new functionality to the project without negatively impacting the main branch sounds great.  I would love to see options added for both aggressive play and handicap games, and a dedicated GUI might be nice, too, instead of needing to load the engine into sabaki or lizzie or cgoban.

As for being aesthetically pleasing: the truly aesthetically pleasing aspects of go are found in the highest levels of play.  For instance, I find that @bjiyxo's 40x256 is very enjoyable to watch and play against, far more so than the 192x15s or ELFs.  Every move is reasonable, and you can sense the complexity behind the seeming simplicity of its moves.  Nothing is more interesting than watching a high dan player, or being a high dan player playing against it, and seeing it crush them/you with what looks like a very simple style.  That idea will probably be fulfilled by the main branch once we increase the network size enough.

Exploring and discovering new ways/methods and advancing AI will honestly require a great deal of rigor and the resources to set up proper experiments, and unless we greatly reduce the scale of the experiments, it will probably end up competing with the main branch for those resources.  This is the one that sounds the most fun and interesting to me, though, and I would love to collaborate on a serious project of this nature.  I'm eventually going to have to decide on something anyways for my doctoral thesis, and joining in on something here may give me ideas for my own research.

**Comment by alreadydone** [comment]
I am still experimenting with lots of things (e.g. https://github.com/gcp/leela-zero/compare/next...alreadydone:komi+?expand=1#diff-ede74db51bef85d4bbaf2ee65b64a513R59, sorry for lack of documentation) and a lot of cleanup is to be expected to make a pull request and have it merged. Now that --pos and --neg have been implemented, the development phase will be over after I implement more accurate komi adjustment (better controlling the winrate after some search), and the testing phase will begin; after the optimal configurations are found it should be time to make a pull request.
The current komi+ branch has dynamic komi disabled by default, so it should safe with AutoGTP; someone could test whether it loses strength under equal time setting, which may be possible if there are bugs. Dynamic komi can be enabled with either --handicap or --nonslack.

**Comment by Marcin1960** [comment]
"I am still experimenting with lots of things (e.g. https://github.com/gcp/leela-zero/compare/next...alreadydone:komi+?expand=1#diff-ede74db51bef85d4bbaf2ee65b64a513R59"

Can I just compile it? Will it work with e1d4 15x192 ?

**Comment by Marcin1960** [comment]
@Crazyeight101 

" I find that @bjiyxo's 40x256 is very enjoyable to watch and play against, far more so than the 192x15s or ELFs. "

Where can I watch it?

**Comment by Crazyeight101** [comment]
@Marcin1960 It's not in a public space.  I'm generating games with it on my system.

**Comment by Marcin1960** [comment]
@Crazyeight101 

Perhaps you could place couple game files  here?

**Comment by Marcin1960** [comment]
Would it be possible to train a few 192x15 nets, on the last games, please? At least to see, how it will go?

**Comment by alreadydone** [comment]
Just made a [release](https://github.com/alreadydone/lz/releases/tag/komi%2Bv0.4) (with very detailed readme!) out of my komi+next branch which is a stable, combined and updated version of komi-v0.3x and endgame-v0.3 and opened pull request #1772.
