### ISSUE TITLE
Inconsistency between readme and files provided

### ISSUE THREAD

**Issue by Alderi-Tokori** [gcp/leela-zero#17]
In the readme, it says about the weights that "The zero_mini.prototxt file describes the 12 residual layer case that was used for the example supervised network listed in 'I just want to play'.".

I looked into the weights.txt file and it seems to have only 6 residual layers instead of 12, and the convolutions output 128 features instead of 256.

I made a program that outputs the number of values on each line of the file and it displayed:
20736
128
128
128
147456
128
128
128
147456
128
128
128
147456
128
128
128
147456
128
128
128
147456
128
128
128
147456
128
128
128
147456
128
128
128
147456
128
128
128
147456
128
128
128
147456
128
128
128
147456
128
128
128
147456
128
128
128
256
2
2
2
261364
362
128
1
1
1
92416
256
256
1

You can see clearly here the bias lines contain 128 values (so 128 output features), and there are 12 convolutions with 147456 weights, which corresponds to 6 residual layers (2 convolutions per layer).

Is Leela able to handle "any" number of weights if all that is changed is the number of output features and/or the board size?

**Comment by gcp** [comment]
I recently uploaded a smaller (but better trained) example network which is why they no longer match.

The number of residual blocks is allowed to vary, as is the number of outputs features. The board size is hardcoded in several places in the program, and can't be changed. Because the layers after the residual tower contain fully connected layers, the networks aren't transferable between board sizes either.
