### ISSUE TITLE
Keynote Lecture: Gian-Carlo Pascutto (Leela Town, Belgium): Trends and Observations in Computer Go

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1706]
https://egc2018.it/za/conference.html
 August 8

 10.00h Registration
 10.15h Welcome

 10.30h Keynote Lecture: Gian-Carlo Pascutto (Leela Town, Belgium): Trends and Observations in Computer Go
 11.15h Discussion

**Comment by herazul** [comment]
I hope it will be filmed !

**Comment by thalessa** [comment]
Hey congrats.

**Comment by roy7** [comment]
Here's the Pair Go game that LZ played on each side. GCP operated Lizzie. Hayashi Kozo vs Manya Marz. No audio or commentary but was a fun game, Hayashi went for the Black Hole opening. :)

https://www.youtube.com/watch?v=e5OXzI6Vp8g

**Comment by AncalagonX** [comment]
Internet spectators claim to have spotted an elusive @gcp playing as the Leela Zero rengo partner to EU 4p Manya Marz—of course, such sightings are hard to confirm, but my anonymous sources can exclusively confirm [this Youtube video indeed confirms @gcp playing in the bottom right as Leela Zero for white.](https://www.youtube.com/watch?v=e5OXzI6Vp8g&feature=youtu.be&t=1h13m41s)

**Comment by AncalagonX** [comment]
Thanks for participating in another one of these events. It was very enjoyable to watch, though it's too bad the audio stream malfunctioned since it would have given unique insights into how baduk pros deal with the new challenge of AI.

As of mid-2018, there are a handful of public AG/AGZ spin-off projects currently running. None of these projects, however, brought together *thousands* of go players like the Leela Zero project did, to such a degree that at any one moment we can count hundreds of individuals who are donating their personal computing resources towards the larger community project of following in Alpha Go Zero's footsteps. Now beyond even the initial, lofty goals, Leela Zero has grown to become the very first and very real, open-source, independently verifiable, and truly post-human artificial baduk player to ever exist—and a full decade before many futurists' optimistic projections. And if that wasn't enough, the community @gcp organized has accomplished this—in all ways that matter—entirely devoid of human input beyond the basic rules of the game, right from Day Zero of the Leela Zero project.

To achieve this progress to date, innumerable contributors have time and again provided assistance to LZ has proved invaluable, whether by generating self-play games or improving the code base. Without each of them, Leela Zero would not have achieved so rapidly the post-human status it currently enjoys and still continues to internally surpass on a nearly daily basis.

When @gcp began this project long ago, he was probably not fully expecting it to reach the heights that it has now. But Leela Zero isn't @gcp's first, second, or even third major computer engineering undertaking. And considering how young he still is (look at his Wikipedia page!), I doubt this will be his last important project.

So thank you not just for establishing the genesis of the Leela Zero project, but for continuing to act as a solid anchor for the community to rally around. Go players like me certainly haven't lost interest simply because open-source, consumer-hardware networks have surpassed human pros so decisively. To the complete contrary, our wide-ranging community—and really, the entire human race—has never at any point in history been better equipped to study the fascinating and multi-faceted game of go. I've written enough for now.

**Comment by Ishinoshita** [comment]
@gcp: If admissible per EGC rules, can you please share with us your full presentation? The hyperlink on the EGC website only  points to an abstract. Thank you in advance.

**Comment by roy7** [comment]
I'm really hoping there's a video someplace we can watch.

**Comment by gcp** [comment]
Someone recorded to talk, so I guess it will be available later. Gimme a minute to clean up my slides.

**Comment by gcp** [comment]
>Leela Town?! Is there really such a place? (If so, it is unknown to Google Maps.)

I have no idea why they didn't put my real town, I guess when they prepared that document they suddenly noticed they didn't know.

**Comment by gcp** [comment]
These are the slides:
https://docs.google.com/presentation/d/1PgJAvZAeO9bGNF0ehEP8G8KOxfoAYeTdU470c_pAG6U/edit?usp=sharing

**Comment by herazul** [comment]
Well honnestly at this point, renaming the town would be better than correcting that document. Leela Town is hilarious :D 
And i'm glad it was recorded, looking forward to it !

**Comment by gcp** [comment]
>And i'm glad it was recorded, looking forward to it !

You'd probably need the audio to make full sense of it, like why the first slide is in a different theme and says 1/51 instead of 30-ish :grin:

**Comment by herazul** [comment]
>1/51 instead of 30-ish grin

I was reading calmly without having noticed it, but now that you mentioned it i won't manage to sleep. WHY 51 §§§!!!
WHY White background ??!!

**Comment by l1t1** [comment]
can you upload the slide as attachment? @gcp

**Comment by gcp** [comment]
>can you upload the slide as attachment? @gcp

File->Download As

>Internet spectators claim to have spotted an elusive @gcp playing as the Leela Zero rengo partner to EU 4p Manya Marz—of course, such sightings are hard to confirm, but my anonymous sources can exclusively confirm this Youtube video indeed confirms @gcp playing in the bottom right as Leela Zero for white.

I played the white stones, the president of the Italian Go federation played the black stones. I was going to run Leela Zero on a 5 year old laptop initially (to demonstrate you don't need the latest and greatest HW), but it broke the week before and I ended up in Italy with a 10 year old one that gets 3 playouts per second. This was too weak - it would mean the game could be decided by Leela blunders instead of the humans, which would be unfair. So I used a remote GTX 1060 and 0ca937d64dad1fd21b76984c4872ce5dbc03cabefe872539dcfa2ed50bf90af5 (which had the highest ~Elo at the time, excluding the 40 blocks).

Lizzie worked fine. We weren't sure how much time was going to be lost for operating so I just kept it in analysis mode and played after a few seconds, unless it was still jumping around a bit between moves. There ended up being issues with the clocks, so the game was essentially untimed anyway.

Playing this way was quite fascinating and I, eh, forgot that it was "my" move several times. White got an early lead due to black's opening experiments, but she couldn't hold onto it - perhaps not surprising given the strength disparity. When Leela had been under 10% for a few moves, she eventually played a first line move and Manya remarked "I think Leela is telling me I should resign", which she did.

Hayashi Kozo was highly entertaining (you can see the mimics in the video) and surprised us at dinner by speaking German, French and Italian in turn.

**Comment by roy7** [comment]
I found Hayashi's expressiveness during the match very entertaining. He tried to do the Black Hole opening, Leela kinda cooperated by letting him place 3 of the 4 7-5 stones.

With dynamic komi Leela wouldn't have imploded at the end, but it was funny seeing that happen as I watched the video since I immediately recognized that as the win rate being too extreme to think clearly any more. :)

**Comment by l1t1** [comment]
https://www.uni-trier.de/index.php?id=65059
has a page of pdf, but it say very little about leelaz

**Comment by l1t1** [comment]
please upload the ppt to https://userscloud.com, google is blocked

**Comment by iteachcs** [comment]
I created a baidu cloud link for those who cannot access the google file:

[https://pan.baidu.com/s/1j7FrT63V5Ad7M5CmHSidTA](url)

**Comment by l1t1** [comment]
thanks @iteachcs

**Comment by roy7** [comment]
Funny thing is that's not GCP. :) But I think that was the guy helping with the Pair Go event who sat next to GCP.

**Comment by gcp** [comment]
That's the president of the Italian Go Federation, which was also organizing the event.
