### ISSUE TITLE
the new weight 44aa is for test?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1735]
9.549M+32K is same as 3b5a

**Comment by gcp** [comment]
Thanks for noticing!

I needed to change the training server to account for the network/server changes we did, but that network went out before I could put the new script in place.

What technically happened is that it tried to download https://sjeng.org/networks/best-network.gz but because of the CDN that specific file lags <=1 day in updating. So it restarted from c910 instead of 9c56.

The resulting file after 32k steps was obviously very close to 3b5a.

**Comment by gcp** [comment]
Hmm, after checking the server, the CDN had actually already updated, so it *did* use 9c56.

The 44aa weights also differ from 3b5a.

So I'm not sure what you mean.

**Comment by l1t1** [comment]
maybe the label of 44aa at web page is wrong, should it be 9.70M+32K?

**Comment by jkiliani** [comment]
Did it use parse the newest set of self-play correctly?

**Comment by gcp** [comment]
Oh, right, that was another thing that I had fixed in the script...

Should be fixed now, net works will go out later today.

**Comment by Mardak** [comment]
@roy7 could fix up the self-play number for 44aa9e80. Perhaps set it to the same as the next +64k network?

**Comment by gcp** [comment]
There's nothing to fix up. The new self-play games were probably not merged correctly. There'll be a new 32k network.
