### ISSUE TITLE
Ladder & Life-n-death under belly in LZ

### ISSUE THREAD

**Issue by yeechutngeow** [gcp/leela-zero#1779]
AQ was released for PC and android recently, and various people have been pitching it against LZ. One observation is the frequency at which LZ failed miserably on ladder and life-n-death. Below is an example of me pitting LZ/Gridmaster against AQ on android phone. LZ is black, set to 1 move per 10 sec.
![img_20180825_091752](https://user-images.githubusercontent.com/2901215/44624454-cd689c00-a921-11e8-848d-5f7d12481b78.jpg)

Some points for discussion:
- the rate at which the current MCTS strategy will fully evaluate a ladder and life-n-death fully is near zero.
- the winrate in the middle of a ladder or a capturing race is undefined or meaningless until the full sequence is evaluated.
- which means the NN will not get to learn about ladder and many life-n-death patterns.
- AQ has menu like "show ladder capture", "show ladder escape", "show false eyes", which means AQ has built-in logic for these things.
- I like to argue that LZ will need similar built-in logic. A recognition system to guide the tree search to reach a local resolution before applying NN evaluation.

**Comment by alreadydone** [comment]
Can't you use LZ in AQ Android?

**Comment by jokkebk** [comment]
This seems hardly news, as Android phones will get very low number of visits, resulting in misread ladders and L&D in much higher frequency than on PC with high visit count. Or are these "various people" seeing Leela being beat by AQ due to ladders on PC with high visit counts as well?

The "we should implement ladder logic outside the zero framework" argument has been hashed a couple times, and so far the answer has consistently been, that Leela Zero is (for the time being at least) going forward with pure zero philosophy (I'm not GCP or a code contributor so just summarizing the previous discussions based on my memory of them), that means no additional inputs or logic for ladders or simple L&D. Yes it means more visits are needed to avoid blunders, and yes it might mean AQ will kick Leela's ass on phones for some time.

Maybe after the Zero approach has run its course and we have 256x40 super-AI for go, a fork of the project could be made with additional features (and a dozen other improvement ideas that have been pitched), and we could see if a stronger AI would emerge using a "non-zero" approach.

**Comment by yeechutngeow** [comment]
Currently the tree search is considered strictly secondary to the NN but there is no inherent reason for that. It is possible to have an architecture where the tree search and the NN are of equal standing and complementary to each other, and have another super-NN that govern over both. The super-NN can learn how to guide the tree-search engine to push forward and suppress the NN for the time being. Everything can be as zero as we want it be, if computer power permits.

The current architecture is wrong on some fundamental sense. I played LZ on my gaming notebook with unlimited time. It is easy to create a ladder situation with the popular 3-3 point invasion joseki. The way MTCS assign a winrate on a half evaluated ladder is wrong. And the semi-random way the MTCS switch from one branch to another basing on meaningless winrate is doubly wrong. The MTCS may not even get around to see the full ladder given any 'sensible' time limit. I believe that is why even the mighty ELF opengo is susceptible to ladder.

**Comment by alreadydone** [comment]
Look at Ttl's work at https://github.com/gcp/leela-zero/issues/1754
look at DeepMind's [MCTSnet paper](https://deepmind.com/research/publications/learning-search-mctsnets/)
and look at [AQ v1.2.1.7](https://www.reddit.com/r/cbaduk/comments/9817ub/aq_go_v1217_is_out_for_android_phones_combining/)
> ... repair the wrong ladder escape/capture

IMO nothing prevents a large enough network from judging simple or reasonably complicated ladders instantly as humans do, though it's a problem how effectively current self-play games with randomness for training teaches the networks about ladders.
