### ISSUE TITLE
Use two weight to do MCTSeach in handicap game

### ISSUE THREAD

**Issue by zliu1022** [gcp/leela-zero#1787]
Wish make leelazero to play handicap game, it's more and more earnest in go fans.
I think about one idea, load two different weight and when do MCTSearch, leelazero can use the low elo weight to simulate black's move. 

Will this implementation possible in current leelazero's architecture? 
I am trying to do so, but it's difficult for me to learn this part of code.

Wish this can make leelazero to find more interesting move in handicap game more like human being play handicap game.

Thanks for your attention.

**Comment by roy7** [comment]
Check out the pull request for dynamic komi. It let's Leela play handicap games much better.

**Comment by alreadydone** [comment]
Check out https://github.com/gcp/leela-zero/issues/1491, https://github.com/gcp/leela-zero/issues/1547, and https://github.com/gcp/leela-zero/pull/1650.

**Comment by zliu1022** [comment]
Thank you very much.
I check Ttl's code, it can run well with two network.

Maybe it's **not implement as I think**, we need the weak weight's policy for black but still use strong network's value also for black, and for white both policy and value should use strong weight, so these together can give a resonable result.
But now I can't find any implementation like these

Good news is we've got several solution to take a try.

**Comment by alreadydone** [comment]
In my dynamic komi branch https://github.com/gcp/leela-zero/pull/1772 it's in fact possible to back up values at (say) white's turns; the value gotten at black's turns will be discarded and replaced by the value at a child (where it's white's turn).
https://github.com/gcp/leela-zero/pull/1772/files#diff-70aab7683fe64f9428b8bc47d1d183c0R242
https://github.com/gcp/leela-zero/pull/1772/files#diff-70aab7683fe64f9428b8bc47d1d183c0R278
It shouldn't be hard to use the strong net's value; you just run net.get_output and keep the winrate in Netresult. With this approach you get 2 policies and 2 values by running the net 3 times, while with my approach you get 2 policies and 1 value by running the net 2 times. It's hard to say which approach is stronger.

Maybe instead of using a weak net's policy, you'd rather use a network trained from human games, e.g. the GX series. Since the network has the last four moves of the opponent as inputs, it can predict the 
Also @pangafu has a plan to gradually increase the percentage of human games in training data to 100% in GX series training.


 .. do two evals.. GX series: human policy but LZ's value ..
