### ISSUE TITLE
Truth about LZ estimation

### ISSUE THREAD

**Issue by dzhurak** [gcp/leela-zero#1788]
Inspired by this tweet https://twitter.com/GoFederationRu/status/1034470739628437508 I decided to check out how ELF would play this game on. 4% -- is way to low. 
So I set up a match of 50 games between ELFv1vsELFv1 starting from this position and results are
Black wins: | 77.6%
White wins: | 22.4%
![leechangho-chohanseong](https://user-images.githubusercontent.com/34740225/44773484-68a77e80-ab79-11e8-9d14-552e3332e2dd.png)
Results are far from 4% so I would say "Don't trust bot estimation in fuseki!" 

P.S. Archive with stats and games 
[ELF_match1.zip](https://github.com/gcp/leela-zero/files/2331249/ELF_match1.zip)

**Comment by nukee86** [comment]
50 games is too low to assume the winrate. Play 1k games and then post the result. Even with 4% chance you can get 10 straight wins.

**Comment by dzhurak** [comment]
Nice joke. You also can win a lottery. Do you know the probability of 10 straight wins with 4% chance? It is 0.04^10 = 1.0485760000000003e-14.

**Comment by wonderingabout** [comment]
nukee86 is right
he didnt say that 4% was low, enough, but he just said that 50 games are not significant to draw any conclusion, which is true

as for an example, in our latest test games, 40b had 14 wins on a row at first 14 games against elf v1, but at 300 games winrate dropped to 47%, see : 

2018-08-26 16:52
390a3a10 VS  d13c4099

https://zero.sjeng.org/match-games/5b82cca1580ff446786c2b1d

**Comment by dzhurak** [comment]
As I wrote 50 games is enough to say that with 4% chance at one game the probability to get 11 wins out of 50 games is ~0.0000032.
Look at this from another point of view. Having 4% estimation of your position is enough to win against ELFv1. at least some of 50 games.

**Comment by isty2e** [comment]
It is statistically significant. You can verify with two proportion z-test, or a CDF of binomial distribution.

**Comment by Friday9i** [comment]
@wonderingabout The test done by @dzhurak is fair, ELF gives 4% winrate but won 11 out of 50 games :  it is enough to say it is very probable that the winrate is significantly more than 4%. 200 games would be better, but 50 games are already good in that case, it is statistically significant.
And your example about 14 wins in a row and 47% winrate is not adapted: it would not arrive (proba < 0,03%) if they weren't a big difference in winrate between short and long games, which explains it.

**Comment by tapsika** [comment]
I'd be careful with these statistical estimates, there is always the possiblity for unexpected biases, special effects or correlations that distort the results, increase variance or hurt significance estimates. It's better to have more data, for example, another set of 50 (not that I expect a 4% result myself). Or what were the results if divided into first and second sets of 25?

**Comment by nukee86** [comment]
You don't have to tell me that chance to win 11 out of 50 games at 4% is very low. It still can happen. I used to play poker. During downswings it happened few times that I lost 50 times out of 100 >90% winrate hands. What are the odds? Well, pretty low but it happens. With 100k hands sample those streaks are irrelevant, though.

**Comment by wonderingabout** [comment]
i understand your point, but a statistical significancy drawn from a 50 game sample can hardly have any real meaning (you cant discard the risk by saying "its very unlikely therefore its not the case")
i dont say that the 4% winrate estimation is real, i also think its a bit low but we have to remember 2 things : 
1) remember that these winrates apply to bot selfplay, against humans the winrate may be much higher because they do more mistakes and less critical moves, especially so early in the game
2) if you're confident that your hypothesis is true, which i dont doubt, i suggest you collect more data, something like 400 games to make a point

you're just making your point weaker by using small samples, while i also believe you may be right

**Comment by l1t1** [comment]
and what shall we do next?

**Comment by dzhurak** [comment]
> and what shall we do next?
I'll run more games to make test more significant. 
I did it to understand to quality of LZ estimation. Showing 4% in this position is nonsense. And if LZ estimates it so low it can play it normal way which is a drawback of MCTS. So maybe some move number as an additional input to NN will help to overcome the issue :)

**Comment by gjm11** [comment]
This is an Elf estimate, not an LZ estimate. Elf notoriously gives more "extreme" winrates than LZ does.

77.6:22.4 is not a possible outcome after playing exactly 50 games. I expect it's actually 11/49. The supplied archive has 50 games in it, but two of them appear to be identical. (I don't know whether the statistically-best thing to do with these is to ignore one of them or include both.) The duplicated game was won by black, so perhaps this should be treated as 11/50 instead of 11/49.

If the "real" probability of winning is 0.04 then the probability of getting 11 or more wins in a 49-game match is about 1 in 2.6 million, so the given match result is very good evidence that 0.04 is not the "right" evaluation (or at least that it shouldn't be interpreted as an Elf-versus-Elf winrate).

The latest LZ with about 10k visits thinks White's chance of winning with best play from the position given here is about 14.9%. (This doesn't vary much with visit count. If I let it run for longer, after 50k visits it reckons it's about 14.7%.)

If _that_ is the "real" winning probability then the probability of getting 11 or more wins in a 49-game match is about 1/19, which is well within the bounds of reasonable possibility. Of course to evaluate this it might be better to run an LZ-LZ match instead of an Elf-Elf match.

Tentative conclusions:

* Elf's winning "probabilities" are certainly too extreme if treated seriously as probabilities. (It would be interesting to draw a "calibration curve" and see what fraction of games it wins when it estimates a given win probability. And to see how consistent this is across games. The latter would be quite a lot of work.)
* LZ's winning "probabilities" may actually be quite realistic; at any rate, the results reported here are consistent with that.

**Comment by MartinDevelopment** [comment]
The prediction can never be 100% accurate, since it doesn't know all the possible moves that can be played all the way trough. It is very possible that a prediction on one move is really accurate for 10 moves, but missed a move at the 11th move that would chance the entire prediction if it noticed that move.

**Comment by MartinDevelopment** [comment]
Also 1600 visits might be too few to properly check this, since LZ is known to make mistakes even at 100k visits(I often see move chances of ~1% multiple times in the same game in a 250k visit match)

**Comment by lightvector** [comment]
I agree with gjm11, I'm confused at all the people that are saying that this might not be statistically significant, it almost seems like people are saying "not significant" in a kneejerk reaction rather than actually doing the math. Please actually do the math instead?

Assuming the games were played one by one sequentially and every game is independent from each other game (e.g. it is NOT the case that the games were all done in parallel and the testing was stopped in the middle at 49 games such there was a bias towards shorter games), then **under the null hypothesis that the true winrate of self-play from this position under the conditions tested was 4%, then the probability (i.e. the p-value) of getting >= 11 wins out of 49 is about 1/330000.**

(This is  a different result than gjm11 - @gjm11 did you use a gaussian approximation? I just summed the binomial series exactly in a spreadsheet since with 50 samples and extreme proportion a gaussian is not actually a great approximation).

So sure, 1/330000 might have happened, but this is vastly beyond the threshold of significance that we normally demand from anything else. We can say it is very likely that the actual winning rate of the bot from that position under self play was greater than 4% _under the conditions of the number of visits and any other search settings used for the testing_.

The italicized part is of course important. The settings under which ELF was trained are potentially very different from LZ, as ELF was trained using different code.

**Comment by dzhurak** [comment]
> The latest LZ with about 10k visits thinks White's chance of winning with best play from the position given here is about 14.9%. 

What network did you use?
Because this is what b1c37640 thinks
![screenshot from 2018-08-29 17-23-08](https://user-images.githubusercontent.com/34740225/44794215-b1c6f500-abb0-11e8-8390-51e86301c520.png)
Looks more like a fair judgment

**Comment by gjm11** [comment]
@lightvector Oops, I accidentally computed the probability of _more than 11_ wins rather than _at least 11_ wins. With that fixed, I agree with your number. Sorry about that. Will edit my earlier comment.

**Comment by gjm11** [comment]
@dzhurak I thought I was using b1c3, but the numbers I get are quite different from yours (which look _not extreme enough_ compared with the observed results from that 49-game Elf match).

... OK. Oops. My Lizzie config was telling it to use Elf v0 weights, and I'd forgotten. With latest LZ swapped in, I get results that resemble yours. Sorry about that. Will edit my earlier comment.

**Comment by tapsika** [comment]
> Assuming the games were played one by one sequentially and every game is independent from each other game

As I wrote above, these are exactly the assumptions one should not make, or at least be very careful with in any real life statistical problem. It seems there were even a duplicate game, so there likely were several correlated or partially identical games (maybe further biases as well). It seems safer to test variance by subdividing results or doing another test(s).

**Comment by lightvector** [comment]
@tapsika Yep, of course. The point is that it's strange that to be concerned about _whether the number of games is sufficient_. The answer is absolutely, with the major assumption that you've set things up correctly, 49 or 50 games is more than enough, the p value here is already very small.

The distinction matters because if you think the problem is merely "50 games is too small of a sample size", as several people seemed to be thinking, then the solution is to just continue collecting more data. Whereas if you are concerned about problems in the details of how you set it up, then merely collecting more data before is only of limited usefulness, since if there was some bias in the methods used, your new data is likely to be every bit as biased as your old data.

In the latter case the solution is not simply to play more games to get more statistical confidence since you already have more than enough, but rather to review the details of your setup (why was there a duplicated game? is there enough randomness in your settings? if you parallelized the games, was there a bias in how you did the parallelization? were your parameters representative of the parameters used to create the training data that the neural net was trained to predict?) and also look for alternative methods to test the same hypothesis to act as validation.

**Comment by dzhurak** [comment]
Since it not an ELF but LZ project I did similar test for LZ with this position
LZ b1c37640 estimation gives black around 25-26%
![screenshot from 2018-08-30 10-51-49](https://user-images.githubusercontent.com/34740225/44837823-4e39d780-ac43-11e8-9b05-8d53411d6e4a.png)
ELF v1 estimation gives black 1-2%
![screenshot from 2018-08-30 10-56-57](https://user-images.githubusercontent.com/34740225/44837894-850fed80-ac43-11e8-96a0-a13111cfe6db.png)
The result 
Black wins 39 out of 170 which is 22.9%.
So I would say that LZ estimation is more reliable in terms of percentage of winning in self play while ELF is just weird. Maybe they used low resign threshold?

Match games and stats 
[LZ_match1.zip](https://github.com/gcp/leela-zero/files/2335213/LZ_match1.zip)

**Comment by roy7** [comment]
ELF winrates are much too sharp, but we've known that all along. It's also why ELF can't handle handicap games. :)

**Comment by wonderingabout** [comment]
the closer you get to solving the game of go, the earlier in the game you can tell whether a game is won or lost with optimal play

i wouldnt be surprised if after hundreds of million games or billion games, a neural ai could tell a winrate >90% at move 20-30
your data shows that LZ's winrate is less "sharp" than elf's, as @roy7 said
again, we need to remember that leela zero elf is different from elf opengo

**Comment by Crazyeight101** [comment]
@wonderingabout Depends on the size of the network.  If you were to do it with a 15b network or smaller, you would probably never be able to produce an accurate win % before late mid-game.

Also, with a sufficiently large network, you'd probably reach that point well before you've produced 100 million games.

**Comment by dzhurak** [comment]
Definitely not. I'd say that any network can show right estimation after only 20 moves. This is well shown on chess leela project. The network there are much better trained than ours and it is still struggles estimate even endings let alone openings.

**Comment by gjm11** [comment]
@wonderingabout  What differences between LZ-Elf and Elf OpenGo are relevant here?
