### ISSUE TITLE
how to test one version's network over another network

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#179]
for example, I want a leelaz with 200k network over a leelaz with 300k network.
is this possible?

**Comment by Dorus** [comment]
Yes, as stated in usage: https://github.com/gcp/leela-zero#usage

Just set up Sabaki, set Leelaz.exe twice, but with different arguments. With the -w option you can chose what network to use (w for weight file).

For example, the 137k network:

>    --gtp -w 1ac2638de9d4d3f9eef43f2afb6b1b4c090a7c350fde4d2d77e00e39eba6fde0

Do make sure you actually downloaded the network and have it in the same dir as leelaz.exe

Btw, i dont think there is a 200k or 300k network released, you will have to do with the 137k, 265k or 
292k etc that are released.

**Comment by l1t1** [comment]
thanks

**Comment by pcengine** [comment]
@Dorus Thanks for the info. However, the default time is about 50 seconds per move, a bit too slow for beginners. Is there a way to change the time setting? Could someone help?

**Comment by Dorus** [comment]
Yeah i've been trying to figure that out myself too. I found two ways:

1: add `--noponder -p 1000` to the argument list. The `1000` here indicates the number of playouts, 1000 is the default for training, but you can also lower it to 100 for very fast games, or up to say 2600 for a bit stronger.

2: Instead of setting playouts, you can actually set the time setting. This require you to open the GTP console, it's a menu option under Engine in the menu on top.
Type `time_settings 0 10 1` or some other numbers. The first number is the main time, the second number the byo yomi time and the third number the byo yomi stones.

Btw, does anybody know how wo set Leela 11.0 to not resign? I've been trying to run Leela 11 vs Leela zero, with 25 stones. So far half the games Leela 11 resigns mid way trough, but when i force it to continue (by reversing the resign and playing the move she suggested in console), Leela 11 does end up winning because Leela zero has no clue about endgame yet.

**Comment by pcengine** [comment]
@Dorus Really appreciate it. Now it works perfectly fine.

**Comment by Shtanko-mephi** [comment]
Does anyone else has a problem with passing in sabaki? When one of the engines passing, it doesn't send pass command to another, and the play stops.

**Comment by gcp** [comment]
Older versions of Sabaki didn't send passes to the engine at all, and just generated moves twice for the same side, which caused problems. I reported that and it was supposed to be fixed, so maybe it's worthwhile checking you have the latest version. Of course there could be more bugs there.

**Comment by gcp** [comment]
The autogtp in the "next" branch has support for running matches between networks, FWIW.
