### ISSUE TITLE
Making leela zero 40b play 50% winrate games vs elf v1 starting at move 100 (games from elf v1 selfplay MATCH full strength)

### ISSUE THREAD

**Issue by wonderingabout** [gcp/leela-zero#1797]
as was explained in many recent issues, including @bjiyxo in #1791 , elf v1 has indeed a sharper winrate, which means it is able to tell soon in the game whether a position is won or lost

we saw leela zero have a great advantage against elf v1 because of that, to quote @bjiyxo : 
" we found that LZ-40b has an extremely high winning rate when the games ended before 180 moves (110:6 for weight b75, 87:6 for weight 390). On the other hand, elf1 has advantages for games ending after 180 moves (67:164 for weight b75, 52:152 for weight 390)"

however, if all those 110 won games continued, we dont know if leela zero had indeed the strength to win them all (if leela zero was so strong, wouldnt its end game winrate be as high as well ?)

edit : after thinking it for a while, i realized there may be better ways to test this than 400 game matches, for example using dynamic komi or even better : 

we make leela zero 40b play a bunch (ideally 400 games) of 50% winrate at move 100 elf v1 selfplay MATCH games (full strength 1600 visits), and we compare the game result with the result of elf v1 vs elf v1 which we already have
the games we would be looking for would be, to sum up (ideally we could automate the game extracting process) : 
- it has to be elf v1 vs elf v1
- it has to be a match game (full strength, no randomness)
- for consistency, 1600 visit games
- the winrate at move 100 has to be 50%+/-5% 
- ideally 400 games
- for humans only : we have to avoid "ladder" games, as elf falls easily to ladders

**Comment by l1t1** [comment]
can also test visits=3201

**Comment by wonderingabout** [comment]
i just made a giant edit, so i suggest rereading my suggestion again

the problem with a 400 game match is that if elf v1 plays indeed slacky, this wont answer our question at all, because : 
- elf v1 could still be stronger but playing slacky because low winrate
- or elf v1 could indeed be stronger but not able to see it with this data

**Comment by Crazyeight101** [comment]
What's the average length of ELFv1 selfplay games?

**Comment by wonderingabout** [comment]
as for full strength games, we'd need arround 100 games at least to have an idea

**Comment by gjm11** [comment]
Incidentally, I also think this is a clear indication that Elf should play with a tighter resignation threshold than LZ: its winrates _don't mean the same thing_ as LZ's. Ideally each should play with a resignation threshold corresponding to its estimated winrate in positions where it wins < some fixed fraction of games, but figuring out those thresholds is a nontrivial job.

**Comment by wonderingabout** [comment]
i also thought of this idea, it may be actually simpler : 

we go to the last official 400 game match of 40b vs elf v1, and we pick all games elf lost by resignation
then play every of these games once in 40b vs 40b, starting at move 100

- if elf's estimation was right and leela zero 40b should be the right winner, then leela zero 40b will have about the same games won against itself as against elf v1
- if leela zero 40b has significantly won less games against itself than elf v1 did resign, then this will confirm that leela zero is weaker than what we estimated

**Comment by bjiyxo** [comment]
> however, if all those 110 won games continued, we dont know if leela zero had indeed the strength to win them all

You may check those games one by one. In my opinion, all those games are in really bad positions(either lose on ladder or lose up to 15 points) and even strong amateur player wants to resign immediately.

> we make leela zero 40b play a bunch (ideally 400 games) of 50% winrate at move 100

We don't need to maintain 50% win rate at move 100. Now we are in a situation that there are lots of treasures in elf-v1, but we only learn the opening and find the opening weakness of elf-v1.  Also, it seems that we do not learn too much in the middle game and the endgame, so elf-v1 can finally make a comeback.  Therefore, there's no threshold at move 100 or near move 100. What we are going to do is make the opening slightly different (-m 999) and learn those middle game and endgame knowledge. Accordingly, I suggest to train the match between 40b and elf-v1 so that we can learn faster than the selfplay from 40b or elf-v1.

**Comment by Crazyeight101** [comment]
@gjm11 the argument you make in the first paragraph of your long comment is incorrect.  The model you give immediately afterwards demonstrates why your initial argument is incorrect.  The conclusion you state at the end is incomplete: as your model demonstrates, when two players who are approximately equal in strength play and one of them resigns significantly early and often, then in addition to the big difference in results we would observe between long and short games, the other player should also have a much higher win rate overall.

Interestingly, you seem to be arguing against @wonderingabout 's comment about the 110 resign games, yet you make and prove the exact point that @wonderingabout was getting at.  Early resigns by ELF are skewing the results because ELF is essentially surrendering some +EV associated with the probability that it would've come back to win some of those games had it not resigned.  The problem is the resigns are skewing it towards around 50%, and not to the much higher % we would expect if LZ and ELF were actually approximately equal in strength.

If ELF was making very good evaluations about the win rate in those resign games, then we could trust that it wouldn't be able to make a comeback in any of them.  However, as we've already seen in #1788 that's far from being the case.  In a position where ELF had evaluated its win rate to be about 4%, it demonstrated an actual win rate closer to 20%.

It appears that LZ is just generally weaker than ELF in later game positions, and the crux of the problem seems to be a lack of mid-late game positions in ELF self-play games that we use for training.  I wonder if it wouldn't make sense during ELF self-play to have games continue for a set number of moves at reduced visits and with zero noise once the resign threshold has been reached before it actually resigns the game.

**Comment by alphaladder** [comment]
I think bjiyxo ‘s idea on mixing 40b self play with 40b vs elf match is simply applicable. 
Other idea is so complicated that no one knows any pitfall ahead.

**Comment by wonderingabout** [comment]
@bjiyxo 
yes you're right, exactly as you said it well elf v1 still has a lot of things to teach leela zero, be it 20b or 40b
but this also means we still cant accurately evaluate leela zero 40b 's real strength against elf v1

the idea to train the middle game with elf v1 mid game / endgame data is indeed interesting and worth trying it

**Comment by gjm11** [comment]
@Crazyeight101 Yes, my first paragraph shouldn't have said "about half the time, E will win" because the difference in resignation strategies will make that untrue. However, nothing else in what I was saying depends on that.

I agree that when two players equal in strength have such different resignation thresholds we should expect the slower-resigning player to win rather more often. If you're suggesting that this means my argument doesn't apply to LZ40 versus Elf1, though, I don't agree, because having E and L equal in strength was a mere convenience and not an essential. If I recall correctly, LZ-40b and Elf-v1 win roughly equal numbers of games against one another, and I think the appropriate conclusion is that _Elf v1 is still substantially stronger than LZ-40b_ but that isn't apparent in overall winrate because of the resignation effect.

I am not sure what in @wonderingabout's comments you think I am disagreeing with; I certainly was not disagreeing with the proposition that Elf may still be much stronger than LZ. What I _do_ disagree with is the idea that the pattern of wins and losses we see is strong evidence that there's a difference in their relative strength _between early and late parts of the game_. (There might be such a difference, of course, but the mere fact that LZ wins short games and Elf wins long ones isn't good evidence of that, as we can see from my model's results.)

So when you say "It appears that LZ is just generally weaker than Elf in later game positions" I don't disagree, but I _suspect_ that actually LZ is just generally weaker than Elf, and attacks on that problem based on the idea that it's _specifically later-game positions_ where LZ is weaker may be misdirected.

(Or they may not! As I say, I don't claim to have proved that LZ _isn't_ specifically weaker in the later game. I would be all in favour of getting some later-game Elf play into the training data. Giving Elf a much stricter resignation threshold would achieve that, as well as giving more honest results in matches.)
