### ISSUE TITLE
why the 292k network file size is smaller than 265k?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#180]
as stated

**Comment by killerducky** [comment]
Both files are 58 lines long, so they are exactly the same size in terms of network architecture and how many floating point numbers are in them. The only reason they're different is due to details in how the numbers are represented in ASCII (mostly how many zeros need to be added or get dropped, or if there is a negative sign or not).

**Comment by roy7** [comment]
The # such as "292K" is the number of games they were trained on, which won't change the size of the weights file. The weights file will remain the same size until @gcp changes the architecture of the network again. A larger architecture will have more weights.

Although I'm not certain if @gcp uses "292K" to mean "292K games were input into training" or "292K games had been logged in the database at the time of the data dump for training". The different being once we're past 500K games in the database, that'll be the max data dumps but I imagine we might still refer to networks as like 750K or 1.4M to reflect when the networks were generated.

**Comment by gcp** [comment]
It is the number of games in the database the training was dumped from, which at the moment is the number of games for training.
The size difference is just fluctuation because some numbers are more compact to represent in decimal than others.
