### ISSUE TITLE
a finding about the self play no resign games

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1800]
I press key q  saved two games, then modify the -r 0 to -r 5 in storefile...bin, then rerun the autogtp.
one saved file is more than 200 moves, the game finished with resign in two moves.
another saved file is less than 92 moves, the game finished with resign at  92 or 93 moves.
can we conclude that each no resign game whose moves more than 93 will soon finish?

**Comment by Ishinoshita** [comment]
I don't understand what kind of statistics you expect to discover with this experiment. No-resign games are no different from resign games, but for being continued after resignation threshold. Pre-resignation game length has the distribution as regular resign games length. There is a peak of games finishing at or close to 92 move count because of the 92 move minimum rule, etc... Randomly stopping the autogtp and moving the -r value from 0 to 5, then resume and record if the game stops amounts to randomly sampling within the -r 5 game length distribution, no ?

**Comment by l1t1** [comment]
I set -r 1, it continue to play for more moves
Got previously stored file
Engine has started.
Infinite thinking time set.
219 (B M9) 220 (W B19) 221 (B A14) 222 (W T19)
