### ISSUE TITLE
resign on an already-won game on CGOS

### ISSUE THREAD

**Issue by hwj-111** [gcp/leela-zero#1807]
http://www.yss-aya.com/cgos/viewer.cgi?19x19/SGF/2018/09/05/465874.sgf

Black actually won by 1.5 if count the score, but black resigned.  dont know why

**Comment by gcp** [comment]
Check the actual SGF with the relevant network and see the eval?

(I didn't manage to get the SGF out of that link)

**Comment by gcp** [comment]
http://www.yss-aya.com/cgos/19x19/SGF/2018/09/05/465874.sgf

**Comment by gcp** [comment]
```
NN eval=0.010116
Playouts: 456, Win: 78.96%, PV: pass O4 pass L11 pass L10 pass K12 pass
pass ->   52934 (V: 95.25%) (N: 39.77%) PV: pass O4 pass C7 pass J10 pass L10 pass L11 pass K12 pass pass
 L11 ->      34 (V: 20.95%) (N: 13.67%) PV: L11 J10 pass O4 pass L10 pass
 L10 ->      31 (V: 23.87%) (N: 12.34%) PV: L10 L9 pass O4 pass L11
 J10 ->       7 (V:  2.56%) (N:  3.93%) PV: J10 O4 pass L10
  L9 ->       4 (V:  2.82%) (N:  2.09%) PV: L9 L10 pass L11
 K12 ->       4 (V:  2.21%) (N:  2.46%) PV: K12 O4 pass
  T1 ->       3 (V:  2.02%) (N:  1.54%) PV: T1 O4 pass
 L12 ->       2 (V:  2.21%) (N:  1.03%) PV: L12 J10
 M11 ->       2 (V:  1.92%) (N:  0.87%) PV: M11 L11
  S2 ->       2 (V:  1.52%) (N:  1.01%) PV: S2 O4
  R3 ->       2 (V:  1.23%) (N:  0.98%) PV: R3 O4
 N13 ->       1 (V:  4.68%) (N:  0.90%) PV: N13 
  J9 ->       1 (V:  3.25%) (N:  0.77%) PV: J9 
  J6 ->       1 (V:  2.63%) (N:  0.78%) PV: J6 
 E11 ->       1 (V:  2.19%) (N:  0.77%) PV: E11 
  G5 ->       1 (V:  1.94%) (N:  0.66%) PV: G5 
11.1 average depth, 19 max depth
31683 non leaf nodes, 1.25 average children
53031 visits, 2332354 nodes, 53030 playouts, 1177 n/s

Passing wins :-)
= pass

```



Looks like it's miscounted by the network, although the engine counts correctly.

**Comment by gcp** [comment]
Nice illustration why no-resign games are important :-)

**Comment by gcp** [comment]
Hmm, one reason why this is appearing on CGOS is that passing isn't allowed because you need to clean up the board. So while normally the engine would see that it's actually won on the board, on CGOS it would need to make it to the final "only eye filling moves remaining" moment without resigning to see that passing out does indeed win.

It might be possible to special case this and disable resignation as long as passing wins.

But that's getting a bit hackish. The underlying problem is that the network is just wrong.

So I think this is still not-a-bug / wontfix.
