### ISSUE TITLE
Recommendations 52% above the winning rate are pass

### ISSUE THREAD

**Issue by a270709570** [gcp/leela-zero#1816]
This will speed up the efficiency of chess and improve efficiency：
The winning rate of the 400 game is 54%, and the probability of chess promotion is 93.95%；
The winning rate of the 400 game is 53%, and the probability of chess promotion is 87.49%；
The winning rate of the 400 game is 52%, and the probability of chess promotion is 77.34%；
The winning rate of the 400 game is 51%, and the probability of chess promotion is 63.68%

**Comment by odeint** [comment]
Groundhog Day...
https://github.com/gcp/leela-zero/issues/1734
https://github.com/gcp/leela-zero/issues/1524
https://github.com/gcp/leela-zero/issues/906
https://github.com/gcp/leela-zero/issues/676
https://github.com/gcp/leela-zero/issues/543
https://github.com/gcp/leela-zero/issues/420
...and many more.

**Comment by l1t1** [comment]
only the  proved stronger weights can touch the PM, like two elfs, c9d7, but there are a few exception, like dc01, or a mistake made by the machine like b1c3

**Comment by wonderingabout** [comment]
as said many times already, the 55%/400 games gating avoids a lot of hassle, see how leela chess zero struggles because of the elo yoyo, bringing the community unstable
it's ok if it's slow, slowly but surely
this loss of speed was expected when moving from 20b to 40b, yet people wanted to promote to 40b, so all what is left now is to wait

if you want to decrease gating to for example 53%, you need to increase the number of games to arround 800 games to keep the same significancy
seeing as slow the 40b is to train, i'd rather take these 800 games in selfplay rather than waste them in unsuccessful match games

**Comment by l1t1** [comment]
https://cloudygo.com/v3-9x9/eval-graphs
