### ISSUE TITLE
AutoGTP v16 Multithreading (solved)

### ISSUE THREAD

**Issue by Weberkx3** [gcp/leela-zero#1871]
I revisit my uploaded game
Found many game errors.

Especially this one
Both sides play chess to 723.

https://zero.sjeng.org/view/94f4aa51c21792ca587a6f186b717425a8864a282e7ea819dec731f87caaec9f?viewer=wgo

====================

I suspect that it is a multi-threaded problem
So cancel the multi-threaded parameters.

There is no error game today.

====================

And I observed that multithreading didn't speed up at RTX2080

Operate the current 256x40 neural network

(8 self played and 0 matches) played in 89 minutes = 671 seconds/game, 3719 ms/move, last game took 512 seconds.

My CPU is i7-8700, I lower the frequency in the BIOS to 3.0GHz
I tried the CPU frequency of 4.5GHz and did not increase the speed.
But 4.5Ghz adds a lot of heat and electricity consumption.

Each AutoGTP single thread may be better.
Performance bottleneck on the GPU.

**Comment by Ishinoshita** [comment]
Hi @Weberkx3,
> Found many game errors. Especially this one. Both sides play chess to 723.

723 moves games are 'normal'. The game you attached is a 'no-resign' game ("-r 0" argument):
* Leela Zero options: -p 0 -v 1601 **-r 0 -m 999** -t 1 -d -n --noponder -s 58333560157324744 -g -q -w networks/...

A fraction of the self-play games requests sent by the server to the clients are no-resign games (this fraction is supposed to be ~10% by now). As an example, I took a bunch of LZ177 self-play games (340 games) and found this distribution here below. There is a peak of 723 moves count games because of the hardstop @723 moves and some games could have gone even further than 723).
![image](https://user-images.githubusercontent.com/37498331/45995800-e50a8000-c099-11e8-9fc2-435aa8fda63e.png)

**Comment by Weberkx3** [comment]
Thank you for your answer.
I know too little about LeelaZero.
