### ISSUE TITLE
the labels of three round weights are the same: 10.34M+32.0k 256x40

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1908]
is it because of round of the number?

![2018-10-04_110203](https://user-images.githubusercontent.com/23301704/46450726-53c69800-c782-11e8-96cd-8ae3f4613807.png)

**Comment by l1t1** [comment]
suggest using 3 digits after the decimal point?

**Comment by l1t1** [comment]
the graph also has a problem

**Comment by gcp** [comment]
It's probably a real problem. The internet in my neighborhood is undergoing major maintenance works and it's been down a lot this week.

If the connection goes down, the synchronization between the training server and game server will fail.

This will probably continue until the weekend.

**Comment by gcp** [comment]
I might try to force a synchronization overnight, as I assume nobody will be cutting any cables then...

**Comment by Friday9i** [comment]
@gcp: did you succeed with the forced synchro? 
FYI, it already happened between the 9/22 and 9/27: 2 full cycles of match games trained with the same 10.25M selfplay games.

**Comment by gcp** [comment]
This is back OK now. I still have intermittent connectivity problems (looks like the maintenance wasn't so successful?) but for now the synchronizations are working.

>FYI, it already happened between the 9/22 and 9/27: 2 full cycles of match games trained with the same 10.25M selfplay games.

I could try some clever scripting to detect and retry these cases, but they've been rather seldom since the ~1 year it's been running, so I'll leave it be for now.
