### ISSUE TITLE
#186 playing ladders with high visits AND incorrectly evaluates endgame 

### ISSUE THREAD

**Issue by jillybob** [gcp/leela-zero#1990]
You can see this game https://online-go.com/game/15133067 Where LZ 186 played a ladder out. This game was at 1000 visits, but when I re-visit the game in Lizzie, even with high visits, Leela Zero plays the ladder. 

[Image 1: It has read the ladder at low visits, but still wants to play it](https://i.imgur.com/0sUS3zO.jpg)

[Image 2: Over 10,000 visits and it still wants to play ladder](https://i.imgur.com/LEnZCjc.jpg) 

[Image 3: After ladder, evaluation for W is over 95%](https://i.imgur.com/qB5F8gx.jpg)

In the end,  after B passes, W passes and loses on points, instead of passing, it should have attacked the bottom left B group as it isn't settled.

**Comment by sheeryjay** [comment]
LZ probably plays the ladder because choosing between a move that is a 96% winning move and one that is 95% is close enough. Both are basically won positions anyway. In fact playing out the ladder simplifies the position. If white sees that he wins even with playing out the broken ladder it will do so freely.

BTW, LZ did not feel any need to attack the lower left Black group, the position is settled as it is. Black group is dead as it stands (so called unconditionally dead group - even if black makes the first move, the group dies). Thus white LZ knew it was winning the game and did not want to waste more time with moves. It did not anticipate a human making a scoring mistake though :-(.

**Comment by l1t1** [comment]
cannot see the graphs, could you attach them here?

**Comment by pondturtle** [comment]
1000 is anything but high visits as far as ladders are concerned too. Try 15 000 for starters.

**Comment by tterava** [comment]
W only loses if you incorrectly mark the bottom left group as alive. LZ does all kinds of crazy moves when it's sure it is winning. This is expected behavior because technically all winning moves are equally good.
