### ISSUE TITLE
can self play game and match be set to no resign before 150 moves ?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#1998]
as todays matchs vs elfv1 shows, both lz187 and lz 188 got winrate greater than 0.6 as so far.
but there are so many games are resigned by elfv1 are less than 100 moves, most of them are 92 or 93 moves threshold.
i guess some of those games would be different, if let them play a little more time?
 so why not try it.

**Comment by l1t1** [comment]
in a regular match, such as http://zero.sjeng.org/match-games/5be1bd48b4ea15180b4271ca
there are only 13 games shorter than 150 moves in all 400 games.

**Comment by Splee99** [comment]
Only in handicap games LZ has some chance to revive the 5% winrate.

**Comment by wonderingabout** [comment]
the problem is when winrate is low, elf will play hopeless and non sense moves, so it wont make any difference, better resign

what could be done though is to give lz vs elf a sample of even games at say move 150, and make them play it
easier said than done though, and eventually leela zero 40b will be absolutely stronger even in mid/late game, so the time-effort vs benefit ratio is rather low
