### ISSUE TITLE
About the training data format

### ISSUE THREAD

**Issue by vigor95** [gcp/leela-zero#2002]
I know the first 16 lines represent the history board stones, but cannot understand each bit's meaning...

Since the feature is binary(stone or empty), why use hexadecimal strings?

**Comment by Ishinoshita** [comment]
For both compression and simplicity purpose I guess.

Training data are text format. For the position, 1 byte = 1character = 1 hex 'digit' = 4 bits = 4 board intersections coding from either black or white stones presence point of view (1= stone of the considered color is present, 0 = no stone or stone of the opposite color; and not 'empty'). 

Each hex string is 81 characters long, coding the presence of (e.g.) black stones over 364 'intersections'.  361 first are for 'real' 19x19 intersections. Last hex value is either 0 (= 'b0000') or 1 (= 'b0001') to code Pass move (from what I have deduced from data files inspection;  but not explicit on readme). 

Then, that text file is gunzipped before upload to the server.

**Comment by vigor95** [comment]
Thanks for your explanation...
Actually a hex string has 92 characters, thus 92 characters = 368 intersections where 361 first are real ones.

**Comment by alreadydone** [comment]
The value after 16 hex strings encodes the side to move (blcak/white) IIRC. Doesn't it always alternate?

**Comment by Ishinoshita** [comment]
Windows Notepad display is indeed misleading. The first 0 is not the first policy value but the side to play, when it's black turn. And it indeed alternates with 1 (white to play).

Notepad++ offer a perfect, unambiguous display and recommended here.

**Comment by alreadydone** [comment]
The linebreaker character in Windows and Linux are different so if the file is created under Linux, Notepad on Windows doesn't properly display it.

**Comment by Ishinoshita** [comment]
@alreadydone I cheated a bit ;-) In order to have 16 lines and not 8 lines, I minimized a little the Notepad window. There is some threshold in window size where the display switches from 'all in one line' to a neater display. I use Windows7.

But definitively, N++ render is nicer. Immediately breaks each training position in 19 lines.

BTW, do you confirm my empirical observation that the 91th hex value codes for a pass move for the considered color?

**Comment by alreadydone** [comment]
I think it's just a binary input for the 361st intersection padded by zero. The first 90 hex values code the other 360 intersections. So you find that the 91st hex value is always 0 or 1? That's consistent with what I think.

**Comment by Ishinoshita** [comment]
Yes, you would expect 'b1000', i.e. 'x8', so that 361st position is contiguous to the 360th position in the binary representation. But I only observed 'x0' or 'x1', i.e. 'b0000' or 'b0001', IIRC (will double check).

**Comment by Ishinoshita** [comment]
My initial mention of pass move coding was indeed erroneous (corrected here above). My script `train2sgf` detects picked move by comparing current position with next position. And pass if position representations are identical. But this discussion on input planes coding made me discover a bug in my code, which explain the 'issue' p_picked =0 ;-).

**Comment by vigor95** [comment]
If Xi and Yi are the values introduce in the 2017 Nature paper, where Xt,i=1 if intersection i contains a stone of the player's color at time t; 0 if empty or opponent or t < 0.
Let me confirm...To summarize, the data format is actually:
line 1: Xt
line 2: Xt-1
...
line 8: Xt-7
line 9: Yt
line 10: Yt-1
...
line 16: Yt-7
line 17: to_play(0/1)
line 18: policy
line 19: value

**Comment by Ishinoshita** [comment]
See [Weights format] (https://github.com/gcp/leela-zero/blob/master/README.md#weights-format) of Readme.md

**Comment by Vandertic** [comment]
I can confirm what you wrote.

> line 17: to_play(0/1)

0 = black, 1 = white

> line 18: policy

362 probabilities in decimal notation

> line 19: value

This is from the point of view of current player: +1 if it won, -1 if it lost. This is then converted on the range 0-1 when a winrate is needed.

**Comment by Ishinoshita** [comment]
Today, with 'dump_supersived' command sent to Leela Zero, I generated the training data, and thus input planes, for the following sgf/position:

![image](https://user-images.githubusercontent.com/37498331/48220713-570bff80-e390-11e8-9688-32c49d0cf5db.png)

I observe that last intersection (361st intersection, T19) do not use the same binary coding as the rest of the intersections:

![image](https://user-images.githubusercontent.com/37498331/48220805-989caa80-e390-11e8-8597-5fa08e55689e.png)

i.e. is coded as '0x1' if there is a stone of the considered color, and not as '0x8'. This is not explicited on readme.md.

I fell for that oddity in my `train2sgf` python script, which interprets T19 moves as Pass move (the latter often having a 0 probability in the search policy). Consequently:
- the issue I reported regarding move picked whereas it has 0 probability (0 visit) is a false issue.
- the stats I made regarding Pass probability (p_pass) are wrong (overestimated, as sum up p(Pass) + p(T19)).
- the sgf generated by my script might be wrong regarding Pass move (some Pass may actually be T19 moves).

However, T19 move is seldom played in a game (only 1.3% of games on average) so that should have only a marginal impact on the various 'commented sgf' I have posted so far. And doesn't explain the other weirdnesses I reported so far (fake data a priori).

*I will update my script on my repo.*

**Comment by alreadydone** [comment]
Good catch, it shows my big-endian vs. little-endian comment was not correct. There is indeed special handling for the last bit when writing the input planes:
https://github.com/gcp/leela-zero/blob/631b88fb73bbc9b45d9513af6ccaf8adfd4f8df9/src/Training.cpp#L241-L252
And in the training code there is comment about least/most significant bit:
https://github.com/gcp/leela-zero/blob/631b88fb73bbc9b45d9513af6ccaf8adfd4f8df9/training/tf/chunkparser.py#L174-L182
