### ISSUE TITLE
an ios app use lelazero and elfv1

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#2026]
https://www.lifein19x19.com/viewtopic.php?f=18&t=16216&sid=e704bfc5fddda482668930c260a13815

**Comment by l1t1** [comment]
y_ich said it use alphuago zero, not leelazero

**Comment by l1t1** [comment]
he said it use  pyaq https://github.com/ymgaq/Pyaq/blob/master/README.md

**Comment by l1t1** [comment]
ymgaq also developed https://github.com/ymgaq/FizzBuzzZero

**Comment by l1t1** [comment]
@y_ich could you release a free version too?

**Comment by l1t1** [comment]
@y-ich could you release a free version too?

**Comment by y-ich** [comment]
@l1t1 san,
Thank you for introducing my app here!
Please let me recover investments (iPad Pro and deleloper program subscription) for a while^^
I was so surprised by the power of A12X Bionic.

**Comment by l1t1** [comment]
@y-ich I understand.
you ask a question at https://github.com/gcp/leela-zero/issues/1991, but I don't know who is the author of that weight

**Comment by y-ich** [comment]
@l1t1 san,
I see.

I also tried ZQ-i8 as well as ELF OpenGo's on my engine.
Its performance was 6 nps on iPhone 6, on which the performance of ELF OpenGO's is 1nps.
it was pretty nice for processors before Bionic.
And it also showed me several bugs in my engine thanks for its speed.

Thanks anyway!

**Comment by zhanzhenzhen** [comment]
@y-ich I bought your app without hesitating. Yes it reaches 170 playouts per second on A12X Bionic. It's even higher than NVidia K80, unbelievable!

Some suggestions:

1. Maybe the 11-inch's most widely used mode is portrait mode. But for iPad Pro 12.9-inch, many people like to place it in landscape position, otherwise the height is too long. But the UI is only optimized for portrait mode. On landscape mode it looks strange.

2. Using Apple Pencil to play a game is simply a treat to me, because it will provide the highest accuracy and the fastest speed even compared with using mouse. I suggest adding a "pencil only" option to disable and thus eliminate accidental hand touch to the board when using pencil.

**Comment by y-ich** [comment]
@zhanzhenzhen san, thank you for purchasing my app and your suggestions!

About landscape mode, currently it is just for supporting split view. (You need to support landscape mode in order to enable split view.) So I eased up the design^^;

About Apple Pencil, I have never think it. Thank you!

I will consider both suggestions in the next major verion.

**Comment by l1t1** [comment]
@y-ich will you make the PyaqArgo public downlord?
http://www.igoshogi.net/ai_ryusei/01/en/list.html
 Program name / Team name (Representative)
https://github.com/gcp/leela-zero/issues/2027
 9.PyaqArgo / Yutaka Ichimura (Japan)

**Comment by y-ich** [comment]
@l1t1 san, I am not Yutaka Ichimura san^^;

**Comment by l1t1** [comment]
sorry, i misunderstanded, your (nick) names are so similar and both use something includes Pyaq....
