### ISSUE TITLE
AlphaZero will play chess

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#2038]
https://www.youtube.com/watch?v=OP_3h__MleY
24min Demis Has****s  
Demis Has****s about AlphaZero at 34:36 : "we would need to play under tournament conditions to know for sure". If he says this, I bet he plans on doing exactly that.

**Comment by barrtgt** [comment]
He discussed there will be news in the next few weeks with a publication coming out and a stronger A0 chess network.

**Comment by gcp** [comment]
>If he says this, I bet he plans on doing exactly that.

Fake news.

**Comment by alreadydone** [comment]
From https://twitter.com/FogleBird/status/1061819753675788288:
![qq 20181122160547](https://user-images.githubusercontent.com/3064145/48922433-a3693c00-ee74-11e8-9990-f2f26bf7e4c1.png)

From https://www.youtube.com/watch?v=emHc-bCpal4 and https://www.youtube.com/watch?v=OP_3h__MleY:
+ AlphaZero now seems to adopt gating and no longer does continual neural net parameters update: the new net needs to beat the old one ~80% (!) of the time to replace it. Apparently this is because there are too many draws between nets of similar strength.
+ One training game (considering "10000 positions per decision") takes 1 second to play. I suspect this is the average speed on a TPU when many games are played in parallel, but Hassabis didn't explicitly say so.
+ The Elo of this new version of AlphaZero is estimated to be ~3600 (on TPU I assume; loses 100 Elo on "usual computers"); pros say the board seems bigger when AZ plays
+ AZ favors mobility; a game was mentioned in which pieces are manipulated back and forth between two wings

**Comment by herazul** [comment]
>>AlphaZero now seems to adopt gating and no longer does continual neural net parameters update:

This is interesting. This and the fact the paper was kinda not specific about the strenght of AZ vs AGZ, AND the fact that the paper is still not approved make me definitly think that AZ approach is not better or easier to implement for now.

**Comment by killerducky** [comment]
> AlphaZero now seems to adopt gating and no longer does continual neural net parameters update: the new net needs to beat the old one ~80% (!) of the time to replace it. 

Can someone give a timestamp for this? I didn't watch these videos but long ago I saw Hassabis talking about how they name new versions of the AlphaGo (e.g v18). For that I recall a similar had to beat the previous a large percentage, maybe it was even higher than 80%. So there could be confusion between this and the much quicker iterations of new NNs into self-play loop. I don't have a direct link to what I'm recalling either.  :)

**Comment by barrtgt** [comment]
The 80% question is here: https://youtu.be/emHc-bCpal4?t=4686
Also I should point out that he said they have the newest net play against older versions, similar to the original AlphaGo.

**Comment by gcp** [comment]
>The 80% question is here: https://youtu.be/emHc-bCpal4?t=4686

Huu! this is a hugely revealing question. I hope/assume this is being discussed in the Leela Chess github too?

First of all, 80% is a huge "gain" for a new net to beat the old ones. This makes me wonder how many playouts they use.

Secondly, the use of much weaker opponents to get decisive results and some additional diversity.

**Comment by gcp** [comment]
Here's another thought: what's the drawing rate of Leela Chess games with the current temperature used?

If it's not prohibitively large, this is an indication DeepMind is using a lower temperature (and hence, sees less blunders are more draws).

**Comment by barrtgt** [comment]
Statistics for the different lc0 runs: https://script.google.com/macros/s/AKfycbz3cw6fXOQ2T2QIpMzSEdUNwVaqfmYpR0LWvP3zwas2-Bn4TR8/exec

They have changed settings for the latest run test30 quite a bit.

**Comment by roy7** [comment]
I wonder if these new changes (playing multiple older nets Minigo style, higher gating, etc) will actually be in their full paper once published.

**Comment by l1t1** [comment]
www.newinchess.com/game-changer

Sadler and Regan reveal its thinking process and tell the story of the human 
motivation and the techniques that created AlphaZero.
