### ISSUE TITLE
40b networks are overfit?

### ISSUE THREAD

**Issue by wentaol** [gcp/leela-zero#2044]
I have been running some matches between 157 and 190.

Experiment 1: 100 normal games (i.e. starting from empty board): 4-96

Experiment 2: 100 games starting from 50 randomly sampled human game positions: 62-38
(Positions were randomly sampled from 9d games from [this ](https://github.com/featurecat/go-dataset) dataset, between 0-150 moves.)

Experiment 3: Same as experiment 2, but only positions at the 5th move are sampled: 64-36

Experiment 4: Same as experiment 2, but between 157 and Elfv1: 40-60

Matches were at visit parity using the settings: -t3 -v1600 --noponder
Results are uploaded [here](https://drive.google.com/drive/folders/1J_HHpC8P5YIYu0F0xyBzXIYKFD-PREkA?usp=sharing) 
twogtp was used to automatically run the matches, it also handled starting positions and color alternating.

As expected, 190 won most of the games in experiment 1.
Result of experiments 2 and 3 are surprising, suggesting 190 and possibly other 40b nets are overfit to self play positions.

**Comment by roy7** [comment]
It seems bizarre to me that by the 5th move 190 is in a position where the win rate has dropped 60% vs starting on an open board. That is barely time to play any sort of joseki if they open with one stone per corner.

**Comment by barrtgt** [comment]
Interesting tests. I think this shows the difficulty of training 40 block networks, plus the 40 block is still immature compared to the 15 block. The training games appear to have some diversity, so I don't think it's an issue yet. I would like to see how results have changed in like 5 more nets.

**Comment by wentaol** [comment]
Something I just noticed, the relative amount of time spent is completely different for the 5th move position matches and the empty board matches. 190 is spending much less time on the 5th move matches so it isn't surprising that it's losing a lot more games. The question then is why this is happening...

**Comment by Ttl** [comment]
Does 40b get all visits? By default thinking time is limited even if you set max visits and if your GPU isn't fast enough it's possible that 40b gets to think much less than specified. Infinite thinking time can be set with `time_settings 0 1 0` GPT command.

**Comment by pliuphys** [comment]
Elf v1 beat 166 325 : 75 (81.25%) . So result from 3 is also somewhat strange.

**Comment by pnprog** [comment]
If I understand well (please correct me):

- 190 is still stronger than 157
- both networks know how to avoid playing a bad opening/fuseki
- but 190 has "over fitted" to the point that if it is put in the situation to deal with a bad opening anyway, it has not so much clues on how to handle it, while 157 can still hold its own?
- so 190 just knows that it should avoid it, probably knows how punish the opponent if the opponent plays it, but just play very poorly out of its usual/tested openings lines?

In that case, it would means that from this point, the new networks are still stronger and stronger (for a game played from start to end) but becomes a poor tool to study games played by other players?

**Comment by Ttl** [comment]
Okay, I read the log files and I spotted some problems.

In the tournament without opening 40b takes about 3.3 times more time which sounds correct. Many of the games seem to be duplicates. If you look at the time column there are lots of games which took under 5s in total. This seems to be because twogtp doesn't restart the engine after completing the game and NNCache from the previous game is still loaded. If multithreading doesn't provide enough randomness to change any of the moves it just finds all the moves from previous game from the cache and replays them immediately without even needing to evaluate the network on GPU.

In positions_uniform tournament 40b takes only 1.25 times longer than 15b, so these games are not run with equal visits as claimed. With low visits and equal time this isn't that unexpected result. Also it seems that there are several games that are just few seconds long. I don't think the positions are well balanced and at least in some openings the engine resigns on the first move as the second engine spent 0 seconds.

5 move openings are also played with time settings and not with equal visits since ratio of time use is only 1.4. Assuming that the tournament without opening was played with 1600 visits and without time settings (which is kind of unclear considering the other tournaments) the real visits move can be approximated from the ratio of time use. 40b spent 200s per game without opening and 70s in 5 move opening so it used only about 500 visits.

I also ran replication of the 5 move opening with lower number of visits using command: `./gogui-twogtp -black "leelaz -g -d -t 2 -r 5 -v 200 --noponder -w d351f06e446ba10697bfd2977b4be52c3de148032865eaaf9efc9796aea95a0c --precision half" -white "leelaz -g -d -t 2 -r 5 -v 200 --noponder -w 53f805d1a0e9b2acbfbeddb9715f3c5db0581cf36aeef7c28b69c1b5dd36df32.gz --precision half" -alternate -auto -debugtocomment -sgffile 157_vs_191 -time 999999 -verbose -openings positions_5moves` and got the result of 15-5 for 40b which is much closer what I would expect.

<details>

```
# Black: Leela Zero
# BlackCommand: leelaz -g -d -t 2 -r 5 -v 200 --noponder -w d351f06e446ba10697bfd2977b4be52c3de148032865eaaf9efc9796aea95a0c --precision half
# BlackLabel: Leela Zero:0.16
# BlackVersion: 0.16
# Date: November 25, 2018 7:16:51 AM EET
# Host: henrik-desktop (Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz)
# Komi: 6.5
# Openings: positions_5moves (50 files)
# Referee: -
# Size: 19
# White: Leela Zero
# WhiteCommand: leelaz -g -d -t 2 -r 5 -v 200 --noponder -w 53f805d1a0e9b2acbfbeddb9715f3c5db0581cf36aeef7c28b69c1b5dd36df32.gz --precision half
# WhiteLabel: Leela Zero:0.16
# WhiteVersion: 0.16
# Xml: 0
#
#GAME	RES_B	RES_W	RES_R	ALT	DUP	LEN	TIME_B	TIME_W	CPU_B	CPU_W	ERR	ERR_MSG
0	W+R	W+R	W+R	0	-	146	21.2	66.1	0	0	0	
1	W+R	W+R	W+R	1	-	139	17.5	55.6	0	0	0	
2	W+R	W+R	W+R	0	-	190	27.3	84.8	0	0	0	
3	W+R	W+R	W+R	1	-	157	24.2	77.5	0	0	0	
4	W+R	W+R	W+R	0	-	152	21.2	75.5	0	0	0	
5	B+R	B+R	B+R	1	-	112	12.3	41.3	0	0	0	
6	W+R	W+R	W+R	0	-	128	16	56.4	0	0	0	
7	W+2.5	W+2.5	?	1	-	351	39.9	129.7	0	0	0	
8	W+R	W+R	W+R	0	-	92	11.6	28.9	0	0	0	
9	W+R	W+R	W+R	1	-	259	33.8	103.1	0	0	0	
10	W+R	W+R	W+R	0	-	182	25.2	80.3	0	0	0	
11	B+R	B+R	B+R	1	-	160	19.8	63.7	0	0	0	
12	W+R	W+R	W+R	0	-	116	13.2	35.4	0	0	0	
13	W+R	W+R	W+R	1	-	113	12.8	42.4	0	0	0	
14	B+R	B+R	B+R	0	-	211	28.6	88.1	0	0	0	
15	B+R	B+R	B+R	1	-	112	13	41.3	0	0	0	
16	W+R	W+R	W+R	0	-	150	18	59.8	0	0	0	
17	W+R	W+R	W+R	1	-	203	26.1	91.8	0	0	0	
18	W+R	W+R	W+R	0	-	92	9.6	22.4	0	0	0	
19	B+R	B+R	B+R	1	-	196	24.2	79.7	0	0	0	
20	W+R	W+R	W+R	0	-	150	19.9	66.6	0	0	0	
```
</details>

The time use ratio is about 3.1 which matches the tournament without opening.

**Comment by Marcin1960** [comment]
@wentaol "the 40 block is still immature compared to the 15 block."

" Still" this is an undocumented speculation-  as it might be simply bad. But a logical conclusion from the fact that much smaller ELF net is so strong, is that rush move to 40b or abandoning 20b was an error.

Yet it is not  psychologically possible to retread to 20b or something little above 20b.

**Comment by MartinDevelopment** [comment]
Everyone should stop using twogtp for these kind of things. It is not made for this and will only make the results less accurate or totally invalid and give you a major headache.

**Comment by wentaol** [comment]
Looks like the -time argument for twogtp is needed. Have no idea why it didn't affect the matches without opening though...

**Comment by pliuphys** [comment]
Perhaps NN cache is reused more without variation in the opening, so the time limit is less of a problem.

**Comment by wentaol** [comment]
I have redone experiment 2 and results are in line with what @Ttl has described (I got 27-73 in favor of 190). As far as I can tell, there is no evidence of overfitting so there's not much point keeping this issue open.
 
I believe it has been shown before that 40b network is stronger at time parity only at higher visit counts. This is probably addressed in a separated issue.
