### ISSUE TITLE
Question about NNCache sense

### ISSUE THREAD

**Issue by Vandertic** [gcp/leela-zero#2067]
(I apologize if the question is too stupid because I didn't understand some fundamental concept.)

If I understand correctly, NNCache is used to speedup computation of the NN in already seen positions. When exactly is this expected to happen? 

I am aware that since NNCache uses a symmetry table, this is happens a lot in the first few moves.

I am also aware that NNCache did _not_ use symmetries when initially introduced, so there must be other cases when the cache is used. I suppose it would be used if one navigates the game, typically by using _undo_, but are there other cases too?

I am asking because I am currently disabling NNCache for SAI's training and matches, and I don't want this to do unknown damage.

**Comment by Hersmunch** [comment]
See:
- #471 where NNCache was added
- #662 where transposition table was removed
- #1421 where symmetry checking was added for the first 30 moves

Note that the initial speed increase reported was when T=1 was only used for 30 moves rather than the whole game so it is likely that it has a larger effect during self-play now. It would be interesting to hear if there are any effects other than speed change observed.

**Comment by gcp** [comment]
>I suppose it would be used if one navigates the game, typically by using undo, but are there other cases too?

That should be the main use case right now. Some amount of gain for transpositions and symmetries (at a theorethical risk of getting very complicated kos wrong), and a large gain for people analyzing in a GUI.
