### ISSUE TITLE
why a client return three games in a row nearly at the same time?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#2074]
1 100.00%  1641e1db632d10461f50ab1d3b3624c6 8ef6a924 W+Resign 299 2.3 minutes  sgf 1 17 
2 50.00%  e8fbc330dc2f66b0a94a42c0a4be50e7 9d4ac610 W+Resign 173 1.6 minutes  sgf 1 17 
3 33.33%  cd10dc3dde62a1847824b0de8fa44293 9d4ac610 B+Resign 182 1.7 minutes  sgf 1 17 

404 56.68%  7d3204341695122916fcaa28dc407357 9d4ac610 W+4.5 193 139.6 minutes  sgf 3 16 
405 56.54%  b93ea1240d6dc9a0bf9203083d7deeda 9d4ac610 B+Resign 246 142.8 minutes  sgf 3 16 
406 56.40%  316fe04835ce13119323d075cf09ec41 9d4ac610 B+Resign 182 139.2 minutes  sgf 3 16 

from http://zero.sjeng.org/match-games/5c0cbb8f469ad81ed7a9a655

**Comment by l1t1** [comment]
and more, did it receive many tasks at one time?

407 56.51%  caad7f4a2a07c177a61c02634e3fcad9 8ef6a924 W+Resign 263 142.7 minutes  sgf 3 16 
408 56.37%  a98419bbb5379508642afa9f0a83aa9a 9d4ac610 W+Resign 277 145.2 minutes  sgf 3 16

**Comment by Hersmunch** [comment]
autogtp's `-g` option can be used to play multiple games at the same time.

**Comment by l1t1** [comment]
so the server will that clients many match/self games at a time when it detected them used -g?

**Comment by Hersmunch** [comment]
I believe the server only uses IP addresses to identify clients. autogtp requests jobs as needed (i.e. one one game finishes it asks for another). If autogtp is used to play multiple games at the same time (either by using `-g` to asynchronously run multiple instances of leelaz or running multiple instances of autogtp) then due to the asynchronous running and variability in game length, many requests can be made at the same time and many games might happen to finish at the same time.
