### ISSUE TITLE
How to get elo scores of different generations as the paper describes?

### ISSUE THREAD

**Issue by GeneZC** [gcp/leela-zero#2132]

**Comment by alreadydone** [comment]
Check out https://github.com/breakwa11/GoAIRatings#go-ai-ratings. It computes the maximum-likelihood ratings of many generations of LZ as well as other AIs (~200 in total) under standardized test conditions. according to the Bradley-Terry Model which is also used in [BayesElo](https://www.remi-coulom.fr/Bayesian-Elo/) adopted by CGOS.

**Comment by Marcin1960** [comment]
Where to find LZ LM 15BGX78 net?

**Comment by alreadydone** [comment]
@Marcin1960  
https://drive.google.com/file/d/1cV9lFT4uq-DAaIrctBjymYRO9WsZxLf9/view?usp=sharing from https://drive.google.com/drive/folders/1XrdAxjDQ7Dnz49QRdv9Dfm1P__-rwR3L

**Comment by alreadydone** [comment]
Note that GX78 is weaker than GX88 and GX89 (with the default -p 1600) although a -p 3200 version of it ranks high.

At least for the LZ/LM nets this could be made a distributed effort ... with server sending out request. breakwa11's current scheduling algorithm involves selecting the net with least games played, then select the net with least Elo difference as the opponent, and select the net which played less percentage of games as black to take black (randomly in case of equal percentages).

**Comment by GeneZC** [comment]
I'm just wondering how to do such so-called standardized test specifically? @alreadydone

**Comment by GeneZC** [comment]
And whether there any way to calculate the elo score of each generation if I only have records associated with best model comparisons, i.e., the game records between a new model and currently the best model

**Comment by alreadydone** [comment]
https://en.wikipedia.org/wiki/Elo_rating_system#Mathematical_details The Elo rating system hypothesizes that the winrate between two players of Elo difference R is equal to 1/(1+10^(R/400)), so to compute the Elo increment of a new net over the last one, just do log10 (1/winrate - 1). If you only have match data between adjacent generations, this is the only reasonable way to calculate the ratings, and the result is shown on zero.sjeng.org. The result is usually highly inflated by a factor of 3 or maybe more, because the new net is usually very good at targeting its parent's weaknesses.

When you have matches between many different pairs of nets, you can use the data to fit the [Bradley-Terry model](https://en.wikipedia.org/wiki/Bradley%E2%80%93Terry_model#Estimating_the_parameters); just treat the Elo ratings as variables and maximize the log-likelihood function L(p). For CGOS there're ~1200 programs so you have an 1200-dimensional optimization problem, but quasi-Newton method for example can converge under half a minute; the MM algorithm may even be faster. Minigo also tests their nets' strength against a population of networks; maybe they are using the BayesElo program directly?

"Standardized" here just means that the parameters and testing conditions are recorded and that the parameters stay the same for all LZ networks involved ([-p 1600 -t 1, with some -p 3200 tests labelled with 3.2k](https://github.com/breakwa11/GoAIRatings/blob/master/AIcmds.md)). Unlike time restriction on CGOS, fixing playouts/visits makes the test hardware independent.

**Comment by GeneZC** [comment]
Many thanks for your reply.

**Comment by roy7** [comment]
Minigo uses the Bradley-Terry approach. I really like it, it's just harder to do with a distributed setup since we'd need clients to download (or store) more networks to run matches vs older networks.
