### ISSUE TITLE
Crashes entire linux os.

### ISSUE THREAD

**Issue by justanotherlamer** [gcp/leela-zero#2162]
Linux mint 19.
Tried different kernels, different video drivers, both gpu and cpu versions.
RTX 2080, i7-7820X.

**Comment by alreadydone** [comment]
I know of a pro player who bought a 2080ti which passes all other GPU tests but crashes the Windows (bluescreen) after running leelaz for a few minutes and has to be returned. Maybe some 2080 also has some hardware problems only detectable by the OpenCL code of LZ.

**Comment by wonderingabout** [comment]
@alreadydone 

that seems quite unlikely
i dont have a rtx, but 99% of the cases when it doesnt work is software

the pro player you're mentionning should try ubuntu to see if the issue is reproductible (although we'll never know if it was returned)

again, i understand that the new rtx cards can be immature, but if thats the case lz is not a magical problem, similar issues should appear on many softwares

**Comment by ihavnoid** [comment]
Any user application crashing the kernel is a kernel (or the driver) bug.  The minimum it should do is gracefully kill leelaz.

Any kernel panic log?  Have you tried contacting nvidia?

**Comment by gcp** [comment]
What @ihavnoid says.
