### ISSUE TITLE
Why do all the visits when the top move won't change?

### ISSUE THREAD

**Issue by dbosst** [gcp/leela-zero#2163]
This is somewhat related to #968 and #951, except this is related to when there is no time management, and you are only limiting visits/playouts.

With limited visits (or playouts), after half of the max visits have been done, if the first ranked move (by visits) has significantly more visits than the second ranked move, we potentially waste effort doing more visits than necessary -- the first ranked move can't change with the number of visits left that we can do.  Instead why don't we stop early (d6def08) when this is the case, saving quite a bit of time.

Example (max visits: 1600): move A has 801 visits, move B has 200 visits.  1001 visits have been done, leaving only 599 visits left. Even if the remaining 599 visits went to move B, giving move B 799 visits, nothing would change, and move A would still be chosen (it having 2 more visits). So we could have stopped early after 1001 visits, rather than doing the remaining 599 visits (in which some would potentially be wasted examining move B).

My main question is, how much do you think stopping early would affect the self-play games training data & training? It seems to me the main side effect is we won't get as accurate probabilities, especially when there is one move with many more visits than the rest, since we will stop that much earlier. Would it be more useful to do stop early and raise the number of max visits?

As it is now, it feels like visits and playouts set the mandatory amount of effort to be done (even if that some of that effort is potentially useless), rather than the maximum (potentially useful) effort done if we stopped early.

**Comment by alreadydone** [comment]
+ Time management is currently enabled by default, no matter in self-play or not, and it works the same way as you describe, namely stop the search when the second most visited move has no chance catching up with the first one. https://github.com/gcp/leela-zero/pull/1497

+ However, during the first 30 moves, the moves are chosen with probability proportional to the visit counts; every move has a chance being chosen, not just the top one. Since additional search will affect the visit counts, stopping early will affect the likelihood of each move being chosen. (A while ago, **every** move is chosen in proportion to visit counts.)

+ Even after 30 moves, stopping early does affect the training data, which records probabilities that are proportional to the visit counts of the children, which are used to train the policy output of the neural net.

**Comment by dbosst** [comment]
I see, thanks for the info! I guess this utility is only outside self-play where you are not randomizing with -m.  OK, I am closing this then.

**Comment by gcp** [comment]
>I even tried different --timesettings on or time_settings 0 1 0 or time_settings 0 9999 9999 -- it doesn't cut the search early off when it should, either for lz-analyze or lz-generate. Am I doing something wrong?

--timesettings on isn't a real option, time_settings 0 1 0 is infinite time, and I'm not sure what is expected of time_settings 0 999 999

>doing lz-analyze it keeps analyzing even when its not necessary...

Why would it cut short when you're *analyzing*? It should cut short when it has to choose a move, not when you're asking it to run indefinitely.

**Comment by gcp** [comment]
Please reopen if there is real bug, but this seems like user error right now.

**Comment by dbosst** [comment]
> Why would it cut short when you're _analyzing_? It should cut short when it has to choose a move, not when you're asking it to run indefinitely.

visits limits lz-analyze and lz-generate
