### ISSUE TITLE
GTP error because of OpenCL error messages

### ISSUE THREAD

**Issue by ljn917** [gcp/leela-zero#223]
I had the following error with Fedora 27. The reason is that Intel Gen OCL Driver does not work correctly on Fedora and prints "cl_get_gt_device(): error, unknown device: 0" to stdout. Autogtp treats the opencl error message as gtp message...

```
autogtp v4
Best network hash: 223737476718d58a4a5b0f317a1eeeb4b38f0c06af5ab65cb9d76d68d9abadb6
Required client version: 4 (OK)
Already downloaded network.
Engine has started.
GTP: cl_get_gt_device(): error, unknown device: 0

*ERROR*: Error in GTP response.
```

**Comment by gcp** [comment]
Muh, GTP requires the communication to go over stdin/stdout, so if you have some broken software that is writing error messages to stdout instead of stderr, it's never going to work very well. You can hack around it in autogtp (I'd rather not) but it will break real GTP interfaces.

Would be much better to fix the thing that is generating that error to use stderr like proper software.

**Comment by sethtroisi** [comment]
I was also seeing this error and "fixed" it by following the advice here:
https://github.com/nanopool/Claymore-Dual-Miner/issues/15#issuecomment-326846578

but I'd suggest moving instead of deleting the file
sudo mv /usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1 /usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1.bck

**Comment by ljn917** [comment]
I have done that already. It does not work. The issue is in intel beignet driver. My clinfo also prints errors like in this issue (https://bugzilla.redhat.com/show_bug.cgi?id=1478536)

Uhmm, can someone merge #226 and this as one issue..... Sorry for opening two related issues.
