### ISSUE TITLE
723 moves upper bound  is correct?

### ISSUE THREAD

**Issue by teddy-cc** [gcp/leela-zero#225]
As title, because of the way to decide game result, there may sometimes happen a kind of strange thing.
One player can fill its stones in another player's field. If he only way to wind the game is to eat all of dead stones, but opponent always fill its stones in your field after you eat.  So one player may win the game that should lose with filling dead stones in another player's field and has no way to be against this method if it reaches the upper bound.

**Comment by isty2e** [comment]
From AGZ paper, Methods - Domain knowledge - (1):

> Games terminate when both players pass or after 19 × 19 × 2 = 722 moves.

So the reasoning behind this upper bound would be like this:

1. There are almost no games that extend over this limit, so statistically it should not matter.
2. Not perfectly sure about it, but the game might last unnecessarily long if not infinitely for some cases.
3. Such a long game with filling eyes of own living groups is usually played when LZ feels like it is in a desperate situation. It implies that the outcome of the game is unlikely to change even if we truncate. With resignation enabled (which is likely to be so in a few days, I believe), such games will not happen anyways.

**Comment by billyswong** [comment]
The 19x19x2 moves upper bound should be more than enough to fill up one's own territory till all eyes are single spaced. The only way that there are still meaningful moves after 722 have to be caused by a player filled up second last eyes of its own living group, causing some sort of suicide thus opened an empty spaces for stones from both side to fill in again. For those cases, it is the stupid player losing anyway so the game result is correct with or without truncation.

**Comment by teddy-cc** [comment]
Another doesn't need to fill its eyes of live stones. If there is a large piece of stones being eaten, there remains large field that can be filled with stones. If the only way to win the game is to eat all dead stones, opponent can fill them and again and again until 723 moves to win the game.  Even if they are professional games, I can find several games form them to change the game result.  So you mean it may happen, but it only happens very few times so we can ignore them?

**Comment by isty2e** [comment]
No, if you had a group of your stones captured by the opponent, then you have less remaining stones on the board. Assuming the remaining space can be filled with approximately the same number of black and white stones, that doesn't affect the game result.

At any rate, if there is a particularly extraordinary case, that shouldn't matter the training process statistically.

**Comment by Dorus** [comment]
I think you misunderstand Tromp-Taylor rules. Not only empty space but also stones on the board give points. Thus if you remove 180 white stones and black still has 180 stones on the board, black is 180 points ahead and even if black passes 170 times and only play 10 new stones, white cannot possibly get ahead as there is not enough space on the board to place x2 190 stones.

**Comment by teddy-cc** [comment]
I mean ,for example stones+field black has 185,but if there are any white stones not captured, black will lose. In the situation white just needs pass( count 1 move ) and wait opponent to capture white's stones. After black capture white stones white can puts its stones on the  same place if it can be. I even can find it in the human's game. It seems rare situation so we don't care about it?

**Comment by isty2e** [comment]
@teddy-cc That does not influence the game result, black wins no matter what.

**Comment by Dorus** [comment]
Tbh i see no value in self play games with more play outs. 1000 or 1600 play outs is in the same ball-park, but 10k really wont add anything (*).

The neural network has a policy network (and value network build into one). Each iteration of the training, the policy network is updated towards the MCTS probabilities of 1000 play outs of the last network. Thus if everything goes perfect, the next generation policy network predicts moves based on 1000 play outs. Thus every new play out has the strength of 1000 previous play outs. However, these play outs are also based on the previous network, so until you train a new network, these play outs are not even all that valuable.

This is only "if everything goes perfect". In practice, the policy network cannot update exactly towards those new probabilities. The network can overshoot the target, the network might be too shallow to learn everything in the training set. The training set might be too small to contain everything the network can learn. The training set might be (randomly) be of low quality. That and a lot more (discussed many times already).

Thus many of the variables we play with are very important. A larger network, a larger window and more play outs all result in a higher quality of learning and a higher training cap. However, also result in slower training because it cost a lot more cpu and gpu cycles. A large training set means the networks keeps training on old data longer. Too many play outs might reduce the variation in the sample games and they become too similar. A larger network will make move generation slower, not only in training and evaluation games but eventually also in real games.

The right balance between testing games and training games is important. If you test the new network every 25k training games, it might already have overshot the target. However if you test the net network every 1000 training games, you end up spending 30% of your time in testing instead of training. Worse, training doesn't happen on just 1000 games, it happens on a random picked selection of moves from the last x games. You can (and probably should) iterate training and testing many times on the same set of training games.

For example AGZ 20 blocks had 700,000 mini batches over 4.9 million games. (If understand it right) they do an evaluation every 1000 mini-batches thus 700 evaluations of 400 games is 280k testing games. 4.9 million games is also 196 times 25k games. So they generated 25k self play games 196 times. That makes 3.5 evaluation rounds per 25k training games.

(*) citation needed, it would actually be interesting to run different number if play outs. Different number of network blocks. Different number of training games. Different window of training games. Different batch size. Different number of training loops between evaluations and different number of evaluations per number of training games.

Short term we can play with window size, batch size and training loops on the existing data set, so that seems to be what a few people here are testing out.
