### ISSUE TITLE
why 6f27 network games are shorter than before

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#240]
by my test
max =443 steps
avg =190 steps
and prior vesion often beyond 400 steps

**Comment by isty2e** [comment]
Please do understand that this place is for discussion, suggestion, or bug reports. You're just stating the games are shorter.

**Comment by bood** [comment]
Proper question should be: any theory can explain this?

Does white now choose to pass when win rate is low? Or black knows it will win even with pass, and white just blindly follows...

**Comment by olbrichj** [comment]
I only looked at one game, but it looks like it's better at judging which value a move is. There are nearly no moves on the 1rst line in the fuseki. Those few are (my assumption) due to the existing randomness. It doesn't try to kill all the stones anymore (400+ moves). Maybe it's just learning and improving :)

**Comment by jenchien** [comment]
It is true that the average steps per game is changing with the networks. From the graphs in this [google doc](https://docs.google.com/spreadsheets/d/1QhYWYQvXBhI5eHJm45fvf97CaV2rRmgrATwVgBFGKoU/edit#gid=0), number of games submitted per client per hour jumped ~1.4x after switching to the 585k network. Similar trend was also observed when switched from 292k to 485k. It's certainly learning and improving!
