### ISSUE TITLE
Is it possible for this project to run on the P2P network?

### ISSUE THREAD

**Issue by klmsj** [gcp/leela-zero#256]
Is it possible for this project to run on the P2P network?
I don't have the related technology, but I'm just interested in alphago, and I have some ideas. If the project can run on the P2P, I think the whole NN can be divided into many parts, everyone can get the entire NN and other people's game playouts, each person can only update part of NN weight, then part of the update to the network broadcast, so the NN will be updated, and finally, the NN evolved slowly.
It's a very naive idea. Please criticize more.

**Comment by isty2e** [comment]
One does not simply split NN into many fragments and train. The result will be abysmal. Another thing is that it is much more efficient to train an NN on a single machine (preferably with more GPUs) than distributing it all over the places, especially considering latency and bandwidth, since the NN training is not essentially an asynchronous task.
