### ISSUE TITLE
could you tell me the meaning of the message in webpage?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#325]
1663 network test matches in past 24 hours, 0 in past hour.

**Comment by OmnipotentEntity** [comment]
I could be wrong, but I believe this is the network vs network test matches being played in order to evaluate if a newly generated network is better than a previous one.  It's a new feature in the next branch.

**Comment by roy7** [comment]
Correct! I added that stat since if we're running a lot of matches, the # of selfplay games will drop.

**Comment by marcocalignano** [comment]
@roy7 easy way to improve your tables css http://tablestyler.com/. 
And also if you put the server code in git-hub maybe someone can use JQuery UI to make the charts from the match table.

**Comment by bood** [comment]
JQuery is really out of date these days, should be something like react or vue :-)

**Comment by barrtgt** [comment]
Personally, i think it's great how it is. Don't really care for flashy graphics. If it's functional and informational, I like it.

**Comment by marcocalignano** [comment]
@roy7 The server distributes 400 match games every time there is a new network to test, right?
Could be that the server wait 400 request and the evaluate the new network ELO and put in the chart **before** all 400 games are submitted?

**Comment by roy7** [comment]
@marcocalignano Someone sent me some code to use a web based graphing system to automate the chart, I need to look at that further and might just adapt it when we're ready. I had planned to use https://www.amcharts.com/ since I've used it before a few times. (This in regards to replacing the Google graph and automatically updating it.)

We could plot the ELO in the chart "live", or once all requested games are completed. Whatever people (or just @gcp) prefer.

**Comment by marcocalignano** [comment]
@roy7 what about the early ELO calculation?

**Comment by roy7** [comment]
For the graph plots that are older and not present in the database we have a few options. I can hard code those into the graph data, or we could add the older networks if we wanted to the server for historical purposes. It might be interesting to see, with all of the early LZ bugs fixed now, what the ELO reallly was between some of these network changes. I suspect we had some improved networks and just never knew because of that one bug that kept causing white to lose games for a while.

**Comment by gcp** [comment]
I uploaded all networks I had and roy7 scheduled matches for all of them. So all historical networks are in the graph/DB.
