### ISSUE TITLE
leela-zero-0.9-windows hanging on the curl step

### ISSUE THREAD

**Issue by jgkwok** [gcp/leela-zero#327]
Just unzipped leela-zero-0.9-windows.

When I run autogtp, I get the following message and the program hangs here.

```
AutoGTP v8
Using 1 thread(s).
Best network hash: eebb910dc02d50437b8fe78c43e4f77b3428b092e9477163aa16403238cea
918
Required client version: 8 (OK)
curl.exe -s -O -J -w %{filename_effective} http://zero.sjeng.org/best-network
```

Given the %{filename_effective} either there's a problem with the code or it's not picking up from the website. When I copy the best network file from my 0.8 folder, the game continues as expected.

**Comment by roy7** [comment]
@marcocalignano This reminds me, and maybe it helps whatever went wrong here for @jgkwok, should we update client to pull from http://zero.sjeng.org/networks/HASH.gz instead of /best-network? We might start serving /networks as a normal http directory via nginx and not even handle it with our LZ server. So you'd just download eebb910dc02d50437b8fe78c43e4f77b3428b092e9477163aa16403238cea918.gz directly.

**Comment by roy7** [comment]
@jgkwok How about running 

> curl.exe -s -O -J -w %{filename_effective} http://zero.sjeng.org/best-network

from command line to see what happens?

**Comment by qysnn** [comment]
Add some kind of retry mechanism as implemented in `Production.cpp` may help

**Comment by marcocalignano** [comment]
@roy7 this is autogtp V8 so the last master release it should have retry built in, and BTW the now version 9 it downloads the HASH.gz file

**Comment by jgkwok** [comment]
It seems to have fixed itself and has correctly downloaded the next network.
