### ISSUE TITLE
Generate Training data with Leela(standard)

### ISSUE THREAD

**Issue by yufanyufan** [gcp/leela-zero#333]
Hi,

Why not skip the bootstrap process, and use matured Leela to generate initial training data?
Google has already proves that no prior knowledge is required, so we dont need to test that again.
Google also shows that prior knowledge is not harmful, so if we can get high quality training data from leela, then we should use it.

Is the bootstrap crucial to final result? 
If it is, then we problaly should restart now because so many bugs are fixed, and the learning curve now is off lot comparing to AGZ.
If it is not, why not skip the bootstrap, and start training leela zero at high level?

**Comment by kimitsu** [comment]
> Google has already proves that no prior knowledge is required, so we dont need to test that again.

Isn't that exactly what we're doing, testing it again? To see if it really works or if Google made some sort of mistake they had not noticed. Sure, some parametres we have are slightly different, but that allows to collect some more data on scaling and limitations of the approach. And I don't think we're that far into the training so that we need a complete restart due to some bug fixes.

**Comment by isty2e** [comment]
The goal here is not just training a strong go AI.

**Comment by yufanyufan** [comment]
Given currently progress, it might need another 5 months or so before leela zero reach the level of leela.
While not stoping current training, we can have a separated instance to bootstrap with leela.
Don’t you want to see how leela zero perform at higher level right now? It might uncover bugs that could waste 5 months of training.
Also it has great acadmic value if we can show the best way to combine supervised learning and reinforce learning.

**Comment by isty2e** [comment]
Not really. If you are interested in such approaches, well it's your project.

**Comment by Marcin1960** [comment]
@yufanyufan
> it might need another 5 months or so before leela zero reach the level of leela.

If code and parameters keep on being  improved and speed accelerates it might be only two months, or less.  Perhaps speed should be the first priority?

**Comment by Alderi-Tokori** [comment]
> we can have a separated instance to bootstrap with leela.

"We" (I suppose you meant GCP by that), simply don't have another instance on which to run this second experiment. Moreover, the goal here is to try and reproduce the results from deepmind and see to which extent they are reproducible with more limited computing power.

Ofc if you have a server, you can totally fork the project and try your own experiment :)

**Comment by zhurak** [comment]
Also we want to built pure AI, without any human knowledge. And Leela's policy and value networks were build on human games. So it more or less tries to replicate the humans. And we want LeelaZero to be trained only on its own games.

**Comment by gcp** [comment]
I didn't run this from the ground up not because I necessarily think this will lead to the best network (I'm not sure), but because:

- Although it logically seems the result should be reproducible in a distributed setting, it needs debugging and tweaking to work, which we've been doing here.
- Producing intermediate networks of varying strength is very useful for people that actually play and study go.
- I don't think there's agreement about which parts from a classical program (like say normal Leela) are keepers and which ones aren't. So starting from Zero avoids that can of worms.

>Google also shows that prior knowledge is not harmful

I'm not sure what you mean by this. I haven't actually seen that result.

**Comment by barrtgt** [comment]
Not to mention a supervised network has holes from moves strong players never play that this training strategy could pick up on.

**Comment by yufanyufan** [comment]
Thank you for bringing in many valid counter arguments!
Then we can revisit this after current leela zero is successfully trained.

I just want to clarify that, in my original proposal, we only use standard leela to generate initial training data, then reinforce learning will take over, and leela zero will learn by it own.
People seems to believe that once the DNN learned from human play, it got some imprint that is impossible to removed. That is not true, and this experiment will verify that.

**Comment by yufanyufan** [comment]
Quote from AlphaGo Zero paper:

"AlphaGo Master is the program that defeated top human players by 60–0 in January, 2017 34
It was previously unpublished but uses the same neural network architecture, reinforcement
learning algorithm, and MCTS algorithm as described in this paper. However, it uses the
same handcrafted features and rollouts as AlphaGo Lee 12 and training was initialized by
supervised learning from human data."

**Comment by killerducky** [comment]
@yufanyufan I agree it is an interesting experiment. But there are limited resources and too many interesting experiments!

The current approach emphasizes reproducing the paper as faithfully as possible, with some concessions due to us having less hardware resources. I feel this is the safest way to achieve success instead of spending time on experiments that seem reasonable but have not been proven to work.
