### ISSUE TITLE
Suggestion: add hash shortcut to on-hover tooltip in strength graph

### ISSUE THREAD

**Issue by grolich** [gcp/leela-zero#345]
It would make it easier to keep track over which network is which between the graph and the growing best-net list.

Right now, it's getting harder and harder to make to spot the different nets because the two (graph and list below the graph) don't share any info - 
the graph shows the number of total games and elo, while the list/table below shows net hash and number of games that specific network played (until it was replaced).

**Comment by justinwong098** [comment]
In the meantime, you can use this spreadsheet created by Andy Olsen. 
https://docs.google.com/spreadsheets/d/1QhYWYQvXBhI5eHJm45fvf97CaV2rRmgrATwVgBFGKoU/edit#gid=806323235

**Comment by roy7** [comment]
I think we're hoping to replace the Google chart sometime soon with a chart that is automatically generated from the database data. This way as matches are completed we can move successes to be the best network automatically, and also chart them automatically.

**Comment by roy7** [comment]
Done.

**Comment by justinwong098** [comment]
@roy7 
In the tables, can you add a thousands separator to the 'Games' and 'Prior #' columns? Maybe add a comma or a space (since a comma represents a decimal mark in some countries) to separate the thousands?

**Comment by roy7** [comment]
Should I have numbers collapse into like 741K or 1.12M in the tables? Or stick with full prevision, just formatted with spaces?

**Comment by justinwong098** [comment]
I don't feel strongly either way.

But if you choose to collapse it into numbers like 741K, I think it's better to stick to the K convention. So, 1.12M would be 1120K. Also, I would change the graph to match the convention that the table uses.

**Comment by justinwong098** [comment]
Also, since we're on the topic of the tables, In the 'Test Matches' table, I'm wondering if it would be worth it to move the recent matches between weaker networks, and move them lower in the table. The table would therefore be organized by when the network was released, instead of when the matches were started. This would allow people to look at the 'Test Matches' table, and follow along with the graph.

**Comment by roy7** [comment]
@justinwong098 Yeah I'll clean that up as soon as I get the number of training examples in here. Then I can do some things like sort the matches tables by the # of training examples the network they played against had, instead of sorting by the creation date of the match itself. That should sync it all up nicely.

**Comment by roy7** [comment]
@justinwong098 Done. (On test server http://zero-test.sjeng.org/)

**Comment by roy7** [comment]
Have all the suggestions from this issue/thread been addressed?
