### ISSUE TITLE
some mean person maybe do bad thing to this project

### ISSUE THREAD

**Issue by cwycn** [gcp/leela-zero#403]
hi,gcp
i from china, i had help run leela zero training self play game,
and yesterday i hard a  rumour on a forum someone or little "hack"
group want to upload some fake (human play or rubbish) sgf to 
contaminated leela zero project ,maybe just rumour or someone has did it
and who want to do this maybe has plenty of compupter power,so 
i just want warning at advance you guys can implement prevention and check measures
and as i kown most people get involved in this project  base on good wil and helpful

**Comment by marcocalignano** [comment]
@gcp @roy7  how would you protect from such attach?

**Comment by MartinDevelopment** [comment]
It's quite easy to do damage to the project by simply forcing the program to play with 1 playouts a move. I wouldn't know an easy way to protect against that.

**Comment by evanroberts85** [comment]
1 move per turn would show up in the training data.

**Comment by marcocalignano** [comment]
I guess checking the training data against the SGF would be the best idea.

**Comment by ihavnoid** [comment]
It is quite baffling that there are people who want to do these kind of pranks... this isn't some kind of national security or financial thing where anybody can gain anything, and this is why we can't have good things.


I think we can randomly pick submitted data and rerun some moves to see if the reproduced results look consistent, that is, the reproduced training data is similar within reasonable error bounds.  If any anomaly is found then blacklist the IP - the important part is not to simply refuse submission, we should accept the submission and throw it into /dev/null to prevent them from noticing that they have been caught and try a different strategy.

This will probably help finding broken OpenCL implementations too.

**Comment by Armavica** [comment]
Perhaps you already do this, but as an easy mitigation of this kind of damage, the server could refuse games submitted too fast by a client. If someone wants to submit forged data, they will then have to do it at a rate not higher than someone submitting legitimate games.

**Comment by grolich** [comment]
@ihavnoid with the all-games sgf easily downloadable and searchable even with its massive size, wouldn't anyone be able to periodically test it for a recent game? Can't really hide it for long by rerouting to /dev/null

The whole notion of such an intended (rather than a coincidental) "attack" is rather hard to understand...

But preventing people from knowing that their games are being blacklisted does not seem to be possible to me because of the aforementioned reason, while it may be harmful to project-related collaboration (not sure how gcp is thinking of using that the fact that it's public in the future, so I'm not sure. Generally, I would think that keeping as much information as possible accessible is important to projects like these).

**Comment by MartinDevelopment** [comment]
Even if someone were to upload 5000 bad games in a short time on purpose I don't think it would cause that much damage, because we can easely spot someone uploading so many games and we use a 300k window, so that is a mere 1.7% and we can easely remove those games by IP and just continue from a past network. At most we would lose a day.

**Comment by Yakago** [comment]
What if that person uploads 100 000 games from 100 000 different IPs ? At that point you either have to identify the games or restart from a spot where you know there is no issue. 

And if the attack persists, there's not much you can do without some special countermeasures

**Comment by ihavnoid** [comment]
Yes I agree that we might not really need to do something very extreme.  Even if we do nothing probably the worst might be that we lose a day or two worth of training.  However I still think it worth the effort of periodically validating incoming training data just to verify that the whole pipeline is healthy.  

Banning probably is only the last resort, and is unlikely to happen since pranksters will get bored quickly anyway.  It's hard to understand why anybody will pull off a prank like that, but we see a bunch of incidents caused by stupidity anyway...

**Comment by MartinDevelopment** [comment]
I think the best solution would be to somehow generate a key which can only be made if a game is legitimately played that the server can verify. I don't know how we could do this, but it is something to think about. Even if it's not 100% secure it should still be able to slow down possible attacks or make them harder to do.

**Comment by kimitsu** [comment]
@gcp Can we have the recent training data & sgf dump? Want to run some tests. (Or am I missing an obvious link where I could find it?)

**Comment by ihavnoid** [comment]
@Yakago  - If there is somebody that determined to use 100K IPs then this project is doomed anyway.  Whoever don't really need to inject malicious data, he/she can just DDoS the server.  Hopefully, anybody who has a malicious intent and has 100K IPs are more likely to be engaged in a more profitable crime, e.g., blackmailing businesses.

@kimitsu  - Training data is on #167, sgf is on http://zero.sjeng.org/.  The other concern is that the network data is quite large so I don't think we can expect so many people to spend time looking for something wrong.

**Comment by justinwong098** [comment]
We could do something like this: double check 1 random game from each client, every day. With only ~500 clients, this is only an extra 500 games. This would also help catch adversaries who use multiple IP addresses.

**Comment by gcp** [comment]
What does "double check each game" mean? They aren't reproducible right now.

**Comment by gcp** [comment]
Training data is current to 2 or 3 days ago. The SGF is on sjeng.org/zero.

**Comment by justinwong098** [comment]
>What does "double check each game" mean? They aren't reproducible right now.

Yup. I was referring to some point in the future, once games are reproducible.
Alternatively, we could do something you've suggested in the past, if reproducibility becomes too difficult.
https://github.com/gcp/leela-zero/issues/47
>check whether the stored game result is correct and whether the move probabilities that are recorded could actually be produced by the network.
