### ISSUE TITLE
Miscounted match wins / losses from white resigning on older clients

### ISSUE THREAD

**Issue by Mardak** [gcp/leela-zero#436]
I currently see `2017-12-20 00:41 | 610cf48a VS 657f91c7 | 1 : 5 (16.67%) | 6 / 400`

This would seem to indicate that the new 610cf48a network won only 1 game so far.

I happened to open up 2 of the most recent match wins:
http://zero.sjeng.org/viewmatch/436b06581e4d0b8c5dc7844861edb378af503427dfcc5725e857284a9fb17438?viewer=wgo
```
Black Leela Zero 0.9 657f91c7
White Leela Zero 610cf48a
Result W+16.5
```

And http://zero.sjeng.org/viewmatch/a6a39a698a2279a9dcc22b1c387f83b5c3f20a083e0787395c41878fd3a8f617?viewer=wgo
```
Black Leela Zero 0.9 610cf48a
White Leela Zero 0.9 657f91c7
Result B+Resign
```

This would mean the first game had White 610cf48a winning and the second game had Black 610cf48a winning. But the table says there should only be 1 win for the new 610cf48a network.

Unclear if the table is just delayed or there is some issue counting.

**Comment by roy7** [comment]
Thank you for spotting this. It's actually an error in the SGF file. I think @marcocalignano has already fixed it in the latest version of /next that the person running that game hasn't upgraded to yet, or maybe the pull request is still pending.

On your 436b06581e4d0b8c5dc7844861edb378af503427dfcc5725e857284a9fb17438 example, the SGF does say RE[W+16.5] but the autogtp process reported "winnercolor" : "black", "score" : "B+Resign". So white resigned in the game. In the past a white resign wouldn't be logged in the SGF correctly and the board would score out, but the correct result does get sent in by autogtp. This has been fixed very recently so that SGFs will have correct winner and results matching what autogtp reports.

**Comment by roy7** [comment]
Or work might be pending on this. See https://github.com/gcp/leela-zero/issues/338.

**Comment by Mardak** [comment]
Looks like both the linked matches end with `W[tt]`, so it looks like there are some (newer) clients that are reporting a correct B+Resign for a white resignation.

**Comment by Mardak** [comment]
Just to wrap things up, the 2 games originally linked should both be B+Resign with 1 win and 1 loss for 610cf48a. The win / loss count is correct, but the SGF file shows the wrong result.
