### ISSUE TITLE
where are the rest of the games?

### ISSUE THREAD

**Issue by Yoitsu36** [gcp/leela-zero#445]
Currently, according to http://zero.sjeng.org/, the newest best network hash (657f91c7) has supposedly 20000 games played, yet in the list of test matches you can see there are barely 200 games if you dont count the first match vs previous best hash with 435 games.

So, where are the rest of the games? is it showing games started + completed? if that is the case it still doesn't add up at all.

There is also the fact that most matches overplay the needed amount of games to the point that I wouldn't be surprised if 30% of games played are worthless. Is the data on http://zero.sjeng.org/ wrong? are the extra games not shown needed for something else? is there a need to keep playing games against a hash that was already decided as fail/pass? Clarity about these things would be really appreciated, i am sure i dont know a lot of the problems that come with the model of client-server and a lot of them are probably very hard to solve, but clarity about such things cannot be bad.

**Comment by gcp** [comment]
The majority of games played are self-play games to train the network who have nothing to do with test matches. See the AlphaZero papers.

**Comment by Dorus** [comment]
The overshoot on failed networks is because there are many clients still doing games after a fail. The overshoot on succeeded games is intentional. They run all 400 matches to get an accurate elo graph. All this info is already discussed in other issues btw.

Work to decrease the number of overshot games is in progress, but it's really a question if 50 extra matches i that much of a problem, we're talking about 10-20k self play games per network anyway and more matches do mean a more accurate elo graph, even on failed networks that's a nice thing to have. Failed evaluation matches already decrease the number of games played on them from 400 to 100-200. Extra work to get that in the 50-150 range isn't that important.

**Comment by Yoitsu36** [comment]
> The overshoot on failed networks is because there are many clients still doing games after a fail. The overshoot on succeeded games is intentional. They run all 400 matches to get an accurate elo graph. All this info is already discussed in other issues btw.

oh, ok i imagined that the rest of the games not shown were also against other hashes and that would cause quite a lot of games lost to fails because of overshoot.

>The majority of games played are self-play games to train the network who have nothing to do with test matches. See the AlphaZero papers.

sorry, it seems i had a fundamental misunderstanding, even thought i had read a bit of the paper i had thought that LZ was using some sort of evolutionary algorithm with the SPRT, being newer hashes variations of the current best. If this is not the case, then arent the selfplay games supposed to increase the ELO without substituting the hash? or is it that the new hashes are being generated by the selfplay games? 

sorry if this was asked before, i didnt see much of this info in the FAQ.

**Comment by odeint** [comment]
> arent the selfplay games supposed to increase the ELO without substituting the hash?

All the networks are fixed entities, they do not change from playing, be it against a copy of itself or another network. They only generate the data used to get the next, possibly better, network (that happens on a single machine, usually gcp's). If we were being precise, we shouldn't actually connect the blue dots on the graph, since there is no smooth function that interpolates between them, or any in-between networks. Each blue dot is only a new high water mark, and until we find a better network, that is exactly the current strength Leela Zero has.

**Comment by grolich** [comment]
A summary of the way AlphaGo Zero was trained might help a bit - 
The sequence of actions are:

1) Best network plays many self play games. Only play. Not learn.
2) Once in many games, the network undergoes training, using random positions from the last X self played games. Only then is a new network generated.
3) The new network and the old one are matched up against each other, and if the newer one wins more than 55% of the games, it becomes the new best network.

That process continues.
SPRT is just a confidence test that is used to determine how confident are we of the current match result between the 2 networks. That way, really bad networks can be skipped before all match games are completed.
