### ISSUE TITLE
why top 2 have same training amount?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#450]
Upload Date | Hash | Games | Training #
-- | -- | -- | --
2017-12-21 04:39 | 6140dc2e | 1189 | 1242298
2017-12-21 01:27 | 273a029d | 1079 | 1242298

**Comment by SharlatanY** [comment]
Looks to me like both nets were trained with the same data set but the better net simply used 16000 training steps, while the worse one was trained using 4000 steps.

You can see the number of steps if you download the network and open it with an archiving program like 7-zip.

**Comment by l1t1** [comment]
thanks

**Comment by gcp** [comment]
That's correct. You didn't see this much before for 3 reasons:

1) Because the amount of training games wasn't exactly known on the training machine, the server estimated it, but I moved things around so that information is exact now.

2) I believe the server now automatically promotes the best network. When we were doing this manually there was a good probability that the second match was far enough along that we'd see it was better than the first.

3) This exact situation didn't happen before AFAIK.
