### ISSUE TITLE
[question] What causes these checkerboard patterns on the NN heatmap?

### ISSUE THREAD

**Issue by fishcu** [gcp/leela-zero#456]
Someone on reddit has generated these heatmaps for the beginning of the game:
https://imgur.com/a/Y8XAl#WJmPuVL

In some positions, you can observe a strong checkerboard pattern that cannot be explained by Go theory. For example, the pattern is also apparent in the center of the (almost empty) board -- one would expect the heatmap to be smooth there.

The current play style of the bot also mirrors this, with the 2-4 point "invasion" being much more frequent than the 3-4 attachment.

Another user has commented with this link:
https://distill.pub/2016/deconv-checkerboard/
As the neural network essentially generates a 19x19 grayscale image, maybe the underlying mechanism (could also call it an "issue") is the same?

**Comment by evanroberts85** [comment]
A lot of basic but effective shape moves follow the checkerboard patter, i.e one space jump. kosimi, tigers mouth, ponnuki. So if 4-4 is good, then 6-4 is good. if 6-4 is good 5-5 is good etc. This pattern logic could spread accross the board from the star points. Just a theory.

**Comment by fishcu** [comment]
A curious thing to note is that these patterns only appear for white -- i.e., when an odd number of moves has been played. 

It makes sense that around already played stones, a somewhat regular and symmetric pattern emerges. That doesn't explain how it propagates to the center, however, does it?

**Comment by isty2e** [comment]
Many people tend to be too impetuous and try to explain something or shout out "I think LZ understands/discovered something". However, many of behaviours in ML cannot be simply explained, or sometimes it is impossible to construct such a theory. I don't think such premature attempts will help understanding or developing LZ, since most of those are based on a wrong reasoning and/or insufficient evidence. To be fair, none of us has a thorough knowledge about the training set itself. 

Also note that the standard Go theory is a set of empirical human knowledges, which doesn't necessarily apply LZ games, especially considering that LZ is still quite weak.

**Comment by killerducky** [comment]
If black opens 4-4, the white heatmap shows low values for attaching at either 3-4, and high value for invading 3-3. In the other corners, it has high values for 4-4, and 3-3. But it also has low values for the 3-4 points. 

Black often plays 4-4, and white thinks attaching at 3-4 is bad. As gcp said, I think the network is overgeneralizing this to be "3-4 is always bad". In the empty corners white has managed to realize 4-4 is still good, and 3-3 is always good. This results in the checkerboard.
