### ISSUE TITLE
Redundancy

### ISSUE THREAD

**Issue by SebastienFaurite** [gcp/leela-zero#47]
This project looks really interesting, and I will gladly donate compute time for it.

Have you thought about result redundancy ?
It could protect against wrong results. They may be intentional or not.

Is there any way to validate a result, other than recomputing it on another client ?

Thanks for your time on this project.

**Comment by gcp** [comment]
The self-play games are random so they cannot be validated by recomputing them.

**Comment by SebastienFaurite** [comment]
It is pseudo random. With the same seed, you can recompute the exact same
game. Isn't it ?

2017-11-14 11:05 GMT+01:00 Gian-Carlo Pascutto <notifications@github.com>:

**Comment by gcp** [comment]
The seed is dependent on time, thread id, and the program is parallel so the actual game played is highly variable dependent on random timing intervals in the operating system.

**Comment by SebastienFaurite** [comment]
I see, thanks

2017-11-14 11:11 GMT+01:00 Gian-Carlo Pascutto <notifications@github.com>:

**Comment by gcp** [comment]
Note that the progress of the network is checkpointed on beating past versions of itself. So you cannot break the other clients by sending bad data, or regress the project, we would simply notice that the training data appears to be no good since the last checkpoint. The server records the IP that submitted a game, as well as client versions, so there are some possibilities to filter if it turns out to be needed (sigh!).

**Comment by SebastienFaurite** [comment]
Perfect !

2017-11-14 11:17 GMT+01:00 Gian-Carlo Pascutto <notifications@github.com>:
