### ISSUE TITLE
how mcts expand the node in leela?

### ISSUE THREAD

**Issue by ericyan71** [gcp/leela-zero#485]
I think there is a parameter called "playout depth" in mcts in alpha go, which control the simulation depth, when reach the depth, expanding is over, and a rollout is executed. but in leelaz' mcts, it seems to play to the end of the game in one simulation, and use the count of the nodes(40'000'000) to determine whether to expand node. are there something wrong with my understand?

**Comment by isty2e** [comment]
AFAIK AlphaGo uses a standard UCT algorithm. I couldn't find the playout depth mentioned in their papers, so can you be more specific?

**Comment by grolich** [comment]
In AlphaGo Zero (which Leela Zero is based on), they removed all rollouts that were previously in AlphaGo. There are no rollouts to the end of the game anymore at all. 
Instead, they use truncation and the value part of the network.

However, the searches are not supposed to always continue to the end of the game at all. 
There should still be a depth at which searching stops (except it doesn't use rollouts anymore, so perhaps it has a different name in LZ?).

I'll look into the code later. Theoretically, if LZ is correctly modeled after AZ, it shouldn't attempt to go to the end of the game like that.

**Comment by roy7** [comment]
@grolich Leelaz does have a max tree size, but I don't think it has a max depth? From my casual reading of https://github.com/gcp/leela-zero/blob/58f689608dc87c79b1e69bc0f6a8602c0ffc2eb8/src/UCTSearch.cpp#L50.

**Comment by grolich** [comment]
That would be strange. 
As AZ used truncations with no rollouts the way I understand it. 
Just reread the relevant parts of the paper.

First it says they no longer use rollouts but rely solely on NN evals.
This, in and of itself, can be understood in multiple ways, but I remember there were other parts in the paper which made it clearer to me that they were truncated.

For example, when they talk about policy evaluation, they mentioned an earlier work which "ALSO performs policy evaluations by regressing a value function towards TRUNCATED rollout values, similar to the value component of AlphaGo Zero.

(Also David Silver called this "reducing the complexity of the Algorithm" somewhere. Although it is definitely more computationally intensive to have all those complete network evaluations for every move instead of a random simulation).

If the AZ algorithm truncates at the same depth criteria AlphaGo did but uses network value instead of rollouts from there, and LZ doesn't, it would make LZ be a lot slower than AZ even on comparable hardware...

**Comment by isty2e** [comment]
@grolich My understanding is like the following:

1. AlphaGo Lee, in its evaluation step in MCTS, uses a linear combination of the value net result and fast rollout. The rollout begins form a leaf node to be evaluated following the policy net values.

2. In AlphaGo Zero, instead of the linear combination, only the value head result is used for evaluation.

3. The full paragraph of is like this: "A more recent instantiation, classification­ based modified policy iteration (CBMPI), also performs policy evaluation by regressing a value function towards truncated rollout values, similar to the value component of AlphaGo Zero; this achieved state­-of-­the-­art results in the game of Tetris. However, this previous work was limited to simple rollouts and linear function approximation using handcrafted features." My understanding is that the cited approach is more similar to AlphaGo Zero than a simple MC search is, and it doesn't mean that truncation is involved in AGZ.

**Comment by grolich** [comment]
That's why I said it can be understood in two ways. I said one of them, since the other was already shown in previous comments.

You're right, I can't tell which of these they meant. 
That's why I had to reread the article.

**Comment by gcp** [comment]
There is no such thing as a fixed playout (or evaluation) depth. The concept does not exist in AlphaGo Lee, AlphaGo Zero or Leela Zero.

MCTS with UCT style node selection expands the node with the highest Upper Confidence bound (that's the UC in UCT). Depth is irrelevant and not even measured in the engine.

**Comment by grolich** [comment]
I think he meant the point at which they stop expanding and do the rollouts, and assumed it was fixed depth.

I simply meant that rollouts don't happen anymore. Hmm so in LZ and AZ, the search just doesn't care how deep it reached in the tree so the value has the same intended effect as I thought anyway at the any (arbitrary) depth it reaches. 

Silly of me now that I look at it again.
