### ISSUE TITLE
Net probability is not taken into account when choose move

### ISSUE THREAD

**Issue by aTan-aka-Xellos** [gcp/leela-zero#5]
May be it called not net probabiliry, but seems it's not used properly?
 A19 ->    3516 (V: 56.39%) (N:  0.0%)
For move V: 56.39% is highest but N is zero, but move still was played.
Other moves with high N is reasonable but choosen - is not.
P.S. I remember that this is only draft weigth and read 'I just want to play right now' section, but isn't it here an issue with choosing move mechanism when the net generate correct data? 

![692 26-oct-17 11 14](https://user-images.githubusercontent.com/7886823/32042098-25b053bc-ba3f-11e7-84a4-aa851e969efb.jpg)

**Comment by gcp** [comment]
The Net Probability is the output from the policy network. It is a "prior", which means it controls the order in which the program explores the moves, and it also controls the amount of search effort the move gets (via a factor the P-UCT formula). But it does not mean that the search cannot play anything different! If that were true, there would be no point to having a value (part of the) network and searching at all. That is rather important, because else the program cannot learn anything by exploring the search space.

Unless randomization is enabled (--randomcnt) the program plays the move with the most playouts. Which move gets the most playouts allocated is a function of prior, ratio of playouts vs the parent, and especially the winrate. The best move as determined by the search typically gets the majority of playouts.

In this case, the search (after first exploring other moves) found that A19 is by far the best, with 56% winrate vs 43% winrate for the next best move, so it correctly played A19 although it had a very low prior (close to 0%).

Of course the move is nonsense. The assessment of the value network that the position after A19 is better is wrong. Essentially what you're seeing here is that in the example weights the policy network has converged much better than the value network.

But the program is functioning exactly as it should.
