### ISSUE TITLE
Better to set komi to 7?

### ISSUE THREAD

**Issue by TFiFiE** [gcp/leela-zero#500]
7.5 may be the current standard komi to use with area-counting rulesets, but it was kind of a missed opportunity not to see some AlphaGo self-play games ending in jigo with (near-)perfect endgames from both sides. If an engine like this becomes strong enough to become useful as an analysis tool, it would arguably be more objective (from a minimaxing perspective) if it were fine tuned for an integral komi (take an endgame position, shift the right number of stones around to equalize the score and then watch it minimax the rest of the game perfectly).

Conversely, there should only be a negligible effect in performance in games where the komi is off by a half; it should almost never throw away wins then. Speculatively, it might even improve the training, because it would increase the number of game states there's something to play for.

It may be a bit early to start this discussion, but AlphaGo already sees a pretty significant advantage for white (about equal to the first-move advantage in chess), and there is precedence in that 9x9 bot tournaments nowadays are played with a komi of 7.

**Comment by thynson** [comment]
why 7 instead of 6.5? Draw is intended to be a voided by all serious go match, except using a rule without restriction of super ko. territory counting rule use 6.5 as it's practically a  balance point. area counting rule use 7.5 komi mainly due to technical reasons.

**Comment by jkiliani** [comment]
In theory, TFiFiE is right that komi should be integer for balanced play at very high level. In practice, this is a non-issue for Leela Zero at its current level. Far in the future, when we achieve a level of play comparable to Alphago Zero, such a measure would make sense, but currently there's simply no reason to deal with the numerous code changes required for allowing draws.

**Comment by gcp** [comment]
Real games are played with uneven komi, and even if white has an advantage, players need to know the optimal black strategy to combat it. Nobody is suggesting that chess is played with komi bidding or whatever.

**Comment by hanysz** [comment]
I know this is closed, but I can't resist commenting anyway.  If it's not practical to implement, then it's not going to happen any time soon.  But in the long term, I certainly do think it's interesting.

Avoiding draws in go is a cultural phenomenon, not an intrinsic property of the game itself.  The professional go tournament scene is based largely on knockout formats, where draws would mess up the schedule, whereas chess tournaments tend to use Swiss formats that are more tolerant of draws.  It's just a historical accident.  A "zero" approach to playing go shouldn't be influenced by these factors!

From a game theory perspective, if we ever do get close to perfect play, then a komi that means a forced win for white makes the game a lot less interesting, as all black moves become equally good (i.e. black loses no matter what).  But an integer komi would force both sides to play optimally in order to reach a drawn position.  The point is moot for now, as per jkiliani's comment, but might be worth revisiting in a future year.
