### ISSUE TITLE
Why 400 match games?

### ISSUE THREAD

**Issue by Azirine** [gcp/leela-zero#504]
According to the binomial test, 300 games with 55% (165:135) already gives a p value of 0.0470.

**Comment by GillesZm** [comment]
Suppose X_i = +1 with probability 1/2 and -1 with probability 1/2 and set S=sum of X_i from 1 to 400.
X_i has variance 1 and therefore S has variance 400, so that S has sigma equal to 20. Therefore, with 50-50 winning probability, getting 55% of wins means getting 220 +1's and 180 -1's, in other words  S=40. This is exactly 2sigma, and corresponds to a 95% probability of happening.
(See e.g. wikipedia 68–95–99.7 rule). Surely this is the rationale behind the 400 match games.
Admittedly it is somewhat arbitrary.

**Comment by Azirine** [comment]
That is the two-tail p value, we only need one-tail which will give p=0.0255 i.e. 97.45% confidence with 400 games and 220 wins. 300 games and 165 wins will give p=0.0470 i.e. 95.30% confidence.

**Comment by GillesZm** [comment]
Yes, you're quite right that given a 50-50 chance of winning, the probability of getting 220 or more wins out of 400 games is 0.9745 (I just checked :) ) and not 0.95. I am guessing though that the choice of 55% for 400 games was made because 400 is a square and 55% corresponds to exactly 2sigma -- it's too neat to be a coincidence. It is easy to (inaccurately, as you pointed out) hastily associate this with some 95% confidence. Anyway this choice was always going to be pretty arbitrary (what's so special about 95% ?). Since the percentage of wins is used to estimate elo, one would really want a (more messy) estimation of the standard deviation of Leela's (and AlphaZero's) elo.

**Comment by evanroberts85** [comment]
I had wondered why my basic school maths binomial calculations were different from the SPRT requirements. Good to have an explanation. 

@gcp is understandably following AGZ and they used 400 games. Personally I think a simple 50% with a minimum number of games is probably better, if not the AZ idea of just using the new network regardless of win rate (though that probably requires first understanding what training parameters to use).

**Comment by LetterRip** [comment]
I'm pretty sure that the 400 games was selected in the AGZ paper because of the desire for 95% confidence interval, so we can safely switch to 300.  Seethe quote from "Mastering the game of Go without human knowledge"

"Evaluator To ensure we always generate the best quality data, we evaluate each new neural
network checkpoint against the current best network fθ∗ before using it for data generation. The
neural network fθi is evaluated by the performance of an MCTS search αθi that uses fθi to evaluate leaf positions and prior probabilities (see Search Algorithm). Each evaluation consists of 400 games, using an MCTS with 1,600 simulations to select each move, using an infinitesimal temperature τ → 0 (i.e. we deterministically select the move with maximum visit count, to give the strongest possible play). If the new player wins by a margin of > 55% (to avoid selecting on noise alone) then it becomes the best player αθ∗ , and is subsequently used for self-play generation, and also becomes the baseline for subsequent comparisons"

**Comment by evanroberts85** [comment]
How much would switching to 300 affect the Elo calculations? Keeping in
mind errors are cumulative?

**Comment by LetterRip** [comment]
@gcp you said in [another thread](https://github.com/gcp/leela-zero/issues/78#issuecomment-354003404)

> Yes but it turns out that the error margin to make this decision with a 400 game limit means it is 55%.

See the above discussion, the 400 games was based on an error of assuming a two tailed p-value.  So we actually only need 300 games.

**Comment by GillesZm** [comment]
> How much would switching to 300 affect the Elo calculations? Keeping in
> mind errors are cumulative?

Well, here's a back of the envelope margin of error estimate. For 400 games, the standard deviation of the number of wins is 10 wins, which translates into 2.5 %, which should very roughly translate into about 15-20 elo points, depending on what winning percentage we are dealing with. So, assuming the whole process involves changing networks 100 times (say), the sum of the errors will pretty much follow a Gaussian distribution with standard deviation 15 x 100^(1/2) = 150 elo points.
The final Elo rating should therefore have a margin of error somewhere between 100 and 200.
When switching from 400 games to 300, everything, including the final margin of error, gets roughly multiplied by 4/3. There's not really much point in trying to be more precise, since it is difficult to appreciate how Elo computed from self-play reflects actual strength anyway.

**Comment by sethtroisi** [comment]
If you want to see try with more precise calculations I have a branch with some code.
https://github.com/sethtroisi/leela-zero/blob/analysis/scripts/elo-uncert.py

version, elo_over_last, stddev, sum_elo, sum_stddev, 95% CI lower, 95% CI upper
9k      , 279, 100, 279, 100, 83, 475
19k     , 91, 25, 370, 103, 168, 573
62k     , 238, 37, 609, 109, 394, 824
107k    , 48, 19, 657, 111, 439, 875
137k    , 178, 45, 836, 120, 600, 1071
265k    , 381, 95, 1217, 153, 916, 1518
292k    , 191, 49, 1408, 161, 1093, 1724
485kw   , 130, 37, 1539, 165, 1215, 1863
585k    , 93, 29, 1633, 167, 1304, 1962
ad8a1d02, 40, 16, 1673, 168, 1343, 2004
2184b750, 14, 15, 1688, 169, 1355, 2020
eebb910d, 39, 11, 1727, 169, 1394, 2060
1607dbea, 38, 10, 1766, 170, 1432, 2100
96bf20e7, 325, 18, 2092, 171, 1756, 2427
a0d3531f, 125, 14, 2217, 171, 1881, 2554
fe7a6c28, 222, 13, 2440, 172, 2103, 2778

This is ~600 elo of uncertainty after only 2440 elo gain.

my code is messy and hard to explain so I'm not going to explain right now, but if it interests you I can follow up.

**Comment by amirlb** [comment]
If I can use this thread for a related question -
How do these game turn out so different? Noise and randomization are turned off, so we should have 2 games (black/white assignment) repeating 200 times.
The only randomization still left in the algorithm is in the rotation of the board state each network sees in the node expansion process, but this should get smaller as the network learns that the rules are perfectly symmetric...
What am I missing?

**Comment by gcp** [comment]
> So we actually only need 300 games.

We need much less games in general which is why the best network is promoted as soon as SPRT passes. The calculation gives some background on why AGZ used those parameters but is not relevant to us.
