### ISSUE TITLE
How blocks/filters of network are decided?

### ISSUE THREAD

**Issue by ayssia** [gcp/leela-zero#510]
Why it's 5 blocks * 64 filters, and then 6 blocks * 128 filters? Is it possible to upgrade to 5 blocks * 128 filters (or even 256 filters)? And how does blocks/filters affect network potential?

**Comment by RavnaBergsndot** [comment]
Yes. We can tune the block number, the filter count, the filter size, the filter shape, the activation function, the fc layer, as well as a lot of other hyper paremeters. The number of possible combinations should be millions.

5 blocks/64 filters gives us about 30k training games per day. If we upgrade to 5 blocks/256 filters it would be reduced to about 1.9k games per day. Unless we can get an influx of huge donated computation power, the self-playing process would become very, very slow.

**Comment by gcp** [comment]
How we ended up with 5 x 64 is a bit buried in the various issues discussing the progress of the project. The idea was to step up gradually to 6 x 128 (starting with that made no sense when the network was random and the amount of clients tiny), but because there were some issues (bugs that were later found) this was postponed and eventually the first games went out of the training window, which means that stepping up to 6 x 128 then wouldn't be exactly the same as having it from the start, so we will stick with 5 x 64 for this run.

If the training is fully stalled, we can still try if we can train a 6 x 128 network to have better performance.
