### ISSUE TITLE
end game bug

### ISSUE THREAD

**Issue by mkw1234** [gcp/leela-zero#539]
Hello all,

Encountered following bug with latest network:
Dead group of stones with leelaz reporting winrate of 100%.  As soon as the stones are captured winrate falls to 0%.

The training games are being played with a resign  threshold  to save on calculation.  However game results should be based on the ground truth of tromp-taylor rule.  

Propose that when low winrate threshold is hit,  game is played out to the end at an accelerated pace with lower number of simulations, say 400, per move.  This should increase the quality of self play games and make leela stronger at end game. 

Thank you.

**Comment by sethtroisi** [comment]
Can you provide a game? In the past when we're debugged this sort of situation it turns out capturing the stones doesn't change the outcome of the game.

**Comment by mkw1234** [comment]
Sorry, I am unable to now.  FYI,  the dead group of stones was a large dragon with one eye.

**Comment by killerducky** [comment]
I have reviewed several of the incorrect resign games I have. Suppose B is winning. W ataris a huge string of stones that are part of B's wall. B doesn't realize the string is in atari because "big ~~dragons~~ strings don't die". Then W captures the string, reversing the game. Sometimes also B fills it's own 2nd to last eye in a huge dragon, like @mkw1234 is describing, but the first case was more common.

@mkw1234 we are already disabling resign in 20% of the games, this should give LZ training data to learn to avoid this.

The case of filling your own eyes should be very easy to fix, the network should learn the rule "never fill your own completely solid eye". But it's possible generalizing all cases of "is my string of 40 stones in atari?" will be difficult for our relatively small network.

IMO we should wait to see because increasing the network size is very expensive in compute time.

**Comment by roy7** [comment]
Should we perhaps stop resigns for a while? Slower game generation but higher quality data?

**Comment by killerducky** [comment]
The paper says incorrect resigns 5%, disable resigns 10%. We have incorrect resigns 10% disable resigns 20%. I think it's close enough.

There is no such thing as "ground truth" as long as LZ hasn't solved the game of Go.

**Comment by roy7** [comment]
I get the feeling from the match lists like http://zero.sjeng.org/match-games/5a4ad2b05e943c4845eb8d86 that all games would end in resign if we didn't have the 20% forced to end games.

**Comment by MartinDevelopment** [comment]
LZ sometimes resigns when it should have passed, because at the end of the game when it cannot make a move to win it just resigns instead of passing

**Comment by mkw1234** [comment]
Just for the record, here is the game: http://eidogo.com/#2kqOrN5fz
@killerducky Thank you for the information.
