### ISSUE TITLE
AutoGTP timing question

### ISSUE THREAD

**Issue by isty2e** [gcp/leela-zero#541]
```
AutoGTP v10
Using 1 thread(s) for GPU(s).
Starting thread 1 on GPU 0
Got new job: selfplay
Net filename: 58da61769a5fb12ff555ee927f16b50d4c24de73a1170a85df1b0d2d706bdef3
net: 58da61769a5fb12ff555ee927f16b50d4c24de73a1170a85df1b0d2d706bdef3.
Engine has started.
Infinite thinking time set.
1 (B D16) 
... 246 (W resign) Game has ended.
Score: B+Resign
Winner: black
Stopping engine.
Uploading game: 3fbbe6c1b9aa47208a41b49c464d3ba8.sgf for network 58da61769a5fb12ff555ee927f16b50d4c24de73a1170a85df1b0d2d706bdef3
Game data f3f76414e27d29d57eb745b5e194d9ed0cbc6e50853bf8a3e0759b457de44254 stored in database
1 game(s) (1 self played and 0 matches) played in 10 minutes = 650 seconds/game, 2642 ms/move, last game took 636 seconds.
```

I am on the next branch. There is an inconsistency between "650 seconds/game" and "last game took 636 seconds". Does the former include time spent for downloading the network file and etc.? If so, wouldn't it be better to calculate the time elapsed per move without them?

**Comment by marcocalignano** [comment]
The first time (650 s) is the total time for all threads used to calculate the total time and the average per time per move. It has some overheads like creating the threads, asking for the work (including download of the network) and starting the threads. The second number is the real time used for the game. 
The overheads are inevitable because when a thread finishes a job and has to start another it has to request the new job and has to download the new network if there is a new one. All this time is added to the total time anyway and it is part of the performance of the PC (this PC take x seconds per game).
We also discussed in #431 how we need to calculate the ms/move number.

**Comment by isty2e** [comment]
After reading the thread, it became clear for me. Closing this issue.
