### ISSUE TITLE
Boost error "what(): character conversion failed"

### ISSUE THREAD

**Issue by as0770** [gcp/leela-zero#6]
Compiling works fine, executing the binary gives following error:

terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::logic_error> >'
  what():  character conversion failed

I have Boost 1.58.0 installed on ubuntu.

**Comment by gcp** [comment]
Are you specifying anything on the command line when this happens?

**Comment by gcp** [comment]
FYI: https://stackoverflow.com/questions/35382902/boost-program-options-throws-character-conversion-failed

Is it possible you have multiple versions of boost installed?

**Comment by as0770** [comment]
I have only Boost 1.58.0 installed. I start Leela Zero like this:

./leelaz --gtp --w weigths.txt
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::logic_error> >'
  what():  character conversion failed

I tried also with path to weigths.txt...

btw, many thanks for starting this nice project!

**Comment by roy7** [comment]
I believe it is -w not --w.

**Comment by gcp** [comment]
--w works as well, as does --wei etc.

I have a test system with Ubuntu 16.04, and boost 1.58, and it's working there, so I'm not sure about the problem here. Every reference to this problem I find is in this exact configuration and people saying they somehow had multiple versions of boost installed. They say reinstalling boost can fix it - not sure how that could work, but maybe it doesn't hurt to try.

**Comment by as0770** [comment]
Indeed after reinstalling boost Leela Z is working. Many Thanks!
