### ISSUE TITLE
What are those networks?

### ISSUE THREAD

**Issue by pcengine** [gcp/leela-zero#646]
There are several new networks on the webpage,  all 2.4M+1M. Could someone please explain what are the differences among those networks? Thanks.

**Comment by gcp** [comment]
They're 6x128 networks trained from the dataset of the the 5x64.

**Comment by pcengine** [comment]
@gcp Thank you

**Comment by Marcin1960** [comment]
On KGS, 6x128 net, 8787/1464K is running now as LeelaZeroT against 1 dan bot

**Comment by DanielThomas55** [comment]
On 14 Jan 2018 8:41 PM, "Marcin1960" <notifications@github.com> wrote:

On KGS, 6x128 net, 8787/1464K is running now as LeelaZeroT against 1 dan bot

http://files.gokgs.com/games/2018/1/14/LeelaZeroT-DCNN1d03.sgf

this game?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gcp/leela-zero/issues/646#issuecomment-357499545>, or mute
the thread
