### ISSUE TITLE
Tree reuse crashes on resignation

### ISSUE THREAD

**Issue by gcp** [gcp/leela-zero#680]
This is blocking release.

https://github.com/gcp/leela-zero/blob/e9171bc1ad563aa3f4580c2379a6f8719775e0b7/src/UCTNode.cpp#L422

**Comment by roy7** [comment]
Paging @killerducky

**Comment by gcp** [comment]
I'll fix this, working on it now. Just putting it here for reference in case anyone wonders where the binaries went.

**Comment by gcp** [comment]
https://github.com/gcp/leela-zero/blob/e9171bc1ad563aa3f4580c2379a6f8719775e0b7/src/UCTSearch.cpp#L470

This will call with bestmove being FastBoard::RESIGN, so it won't find the new root.

**Comment by killerducky** [comment]
In addition to just removing the assert, I think you should also change the return to: 
`    return std::make_unique<UCTNode>(FastBoard::PASS, 0.0f, 0.5f);`
instead of returning a nullptr.

BTW in the new cmake flow, how do you compile with debug on? In the old flow I would just do `make debug` but that doesn't seem to work with cmake.

**Comment by gcp** [comment]
>I think you should also change the return to: return std::make_unique<UCTNode>(FastBoard::PASS, 0.0f, 0.5f); instead of returning a nullptr.

Yes, that's required or the next game will crash.

**Comment by killerducky** [comment]
Ugh, obviously I didn't test this enough.  :(

**Comment by gcp** [comment]
To be fair I changed this while merging. I believe the comment so I made sure we would crash if we hit the condition that should never happen. Now we know when it happens :-)
