### ISSUE TITLE
A non GPU (or only CPU) version?

### ISSUE THREAD

**Issue by emdio** [gcp/leela-zero#70]
So, I'm quite sure if this hasn't been done it's either impossible or worthless, but just in case, wouldn't be possible to develop an only CPU version for computers that don't have a compatible graphic card?

**Comment by emdio** [comment]
Well, it seems here there's a turnaround to make leela-zero work without GPU

https://www.reddit.com/r/baduk/comments/7dg219/psa_you_can_help_training_leelazero_without_a/

**Comment by gcp** [comment]
Running on the CPU is very slow for a large network, running it through OpenCL on the CPU is far, far worse.

https://github.com/gcp/leela-zero/blob/9064f6facc452262b3eba12a55f9ff2ca3486dfd/src/Network.cpp#L450

It's not very hard to fill in this part, all the supporting code for convolutions, batchnorm etc is there, and the residual part is a simple add. But I didn't do it because it's a waste.

**Comment by fishcu** [comment]
I'm the author of that reddit post. It was more of a test of feasibility rather than practicability.
Still, the difference in performance between that old i5 (2nd gen) and my new machine with an i7 (7th gen) and a GTX 1060 is only about 1 order of magnitude! If 1 order of magnitude more people can run the distributed training, it is still worth enabling them to do so -- why do you consider it a waste?

**Comment by gcp** [comment]
This is because the initial network is very small. Until the learning data accumulates a little, the program is effectively CPU limited and the GPU part (or not) doesn't really matter. But this won't last very long...

**Comment by fishcu** [comment]
You are right, that's something I was aware of but forgot to mention in my little experiment. I have no idea how that will change though.

Do you have any idea how much you'd expect a CPU-only trainer to slow down in the near future? Another order of magnitude?

**Comment by gcp** [comment]
From experience with regular Leela it is about a factor 10x-30x. That is with OpenBLAS convolutions. With OpenCL-on-CPU it would be far worse.

**Comment by fishcu** [comment]
I'll keep my old machine with OpenCL-on-CPU running. Then we will find out how slow it really gets!

**Comment by nauzykaa** [comment]
@gcp If it's relatively easy to add support for CPU-only, I would ask you to reconsider despite all those performance related objections. The reason is that people want to feel included and help as much as they can and basically hearing "you are useless with your puny CPUs" is very uncomfortable psychologically. Secondly, there are orders of magnitude more machines without strong GPU and together they can probably contribute in non-negligible way. Last point, it would help to keep people engaged. People are curious to load the newest network to see how it plays and now they cannot do this without strong GPU.

**Comment by emdio** [comment]
Now this is interesting.

My hardware is a laptop with an i5 cpu and nvidia geforce gt 540m.

Like ten hours ago, autogtp was providing moves at a really slow pace, like 10-15 seconds per move (even for the first moves of the game).

I've just started autogtp today and it's going way faster. Like running autogtp in 1 core needs less than 5 seconds per move.

I post this here because my guess is that it has to do with the new trained net.

**Comment by fishcu** [comment]
Another user on Reddit has provided another data point. For the normal leela version, OpenCL on the CPU is about 100x slower than the CPU-only version in his case.

If it's not too much work, it would be great to have a CPU only version. I think once (if) autogtp becomes very popular, maybe in Asia, it would be well worth it in terms of usable compute.

**Comment by Tsun-hung** [comment]
I expect a CPU only version too

**Comment by bood** [comment]
Adding a point here:
If a CPU only version is available, we can also leverage Google Compute Engine (probably other engines too) for some free computing resources too. As long as it's not too slow (like 100 times slower).
See #124 for details. Currently it fails due to lack of GPU.
@gcp

**Comment by fishcu** [comment]
FYI, With the latest network, 1 game takes about 6-7 hours on my OpenCL-on-CPU machine.

BTW, have you guys seen https://github.com/NTT123/LZW? It seems to aim at being a leela-zero implementation in javascript. Not sure how slow that would be, but then we could also use smartphones, for example, to help training!

**Comment by godmoves** [comment]
A lot of people who don't have a modern GPU also want to join this project, so maybe we should consider to add a CPU version if it is not very difficult.

**Comment by lwins-lights** [comment]
@gcp I'm not familiar with modern tools like im2col and BLAS. Would you consider to accept an naive implementation for a CPU version? If so, I would like to have a try. Nevertheless, if it turns out that these tools are easy to learn and they runs quite faster than naive approaches do, I would also use them. Would you mind give us more detailed information about this?
