### ISSUE TITLE
how to avoid system check before start game on autogtp 13?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#715]
It took about 3 min to finish
<pre>
D:\tool\leela11>autogtp -k sga
AutoGTP v13
Using 1 thread(s) for GPU(s).
Starting tuning process, please wait...
net: 7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a.
./leelaz --tune-only -w 7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a
Using 2 thread(s).
RNG seed: 7904500447168824187
Detecting residual layers...v1...128 channels...6 blocks.
Initializing OpenCL.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 8.0.0
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce GT 730
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 376.62
Device speed:  901 MHz
Device cores:  2 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce GT 730
with OpenCL 1.2 capability.

Started OpenCL SGEMM tuner.
Will try 578 valid configurations.
(1/578) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 6.5764 ms (8.0 GF
LOPS)
(2/578) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 3.8861 ms (13.5 G
FLOPS)
(5/578) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 3.1819 ms (16.5 G
FLOPS)
(6/578) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 2.7935 ms (18.8 G
</pre>

**Comment by wctgit** [comment]
Hmm, seems I'm not the only one who ran into this kind of problem. See #712.

The temporary workaround solution (probably) is to move the leela11 folder to somewhere under your User folder, such as Documents or Downloads. Yeah, it's awkward to have software running from those kinds of locations, but the underlying issue seems to be connected to some esoteric folder/file permission restrictions on Windows for "C:\" and "C:\Program Files".

Until the underlying issue is resolved, the workaround is probably your best bet. Eventually, it would be nice to have a simple installer for Windows machines, which would probably bypass the whole issue by doing things the 'proper' way for installing software on Windows.

**Comment by Alderi-Tokori** [comment]
>the underlying issue seems to be connected to some esoteric folder/file permission restrictions on Windows for "C:" and "C:\Program Files".

Launching the program as admin doesn't work?

**Comment by wctgit** [comment]
I think my previous comment on this issue is a red herring, caused by my confusion between 'lengthy downloading of network files' and 'lengthy tuning process'. 

Since the underlying problem of my issue #712 is actually a quirk/bug of gzip.exe behaving differently when run in different folder paths, then it's unlikely to be connected to this issue regarding tuning. Unless, of course, there's some dependency on the tuning process and usage of gzip.exe -- such as to de/compress the leelaz_opencl_tuning file. However, if there's no such dependency, then my previous comment in this thread is almost certainly a red herring.

On the other hand, since the proposed workaround is easy (move the folder to Documents or Downloads and try again), it might be worth a shot just to try it. Ya never know.
