### ISSUE TITLE
After double pass autogtp must report correct score

### ISSUE THREAD

**Issue by Splee99** [gcp/leela-zero#724]
Currently Tromp Taylor rule is used and sometimes it's incorrect. More details are discussed in #624.

**Comment by jkiliani** [comment]
The correct score regarding Leela Zero is the Tromp Taylor score. If you're referring to this thread: https://www.reddit.com/r/cbaduk/comments/7s566x/a_weakness_of_the_current_network/, in the example game white simply made a mistake by passing, because passing back wins the game for black, while capturing the dead group would have won. In the past, these types of mistakes were much more severe. Eventually the reinforcement learning process will eliminate such behaviour, so there's no cause for concern.

**Comment by Splee99** [comment]
Hi, 

I didn't expect this issue is closed so quickly. I hope you can still see this email. The problem is that sometimes resign is not allowed in self play games and LZ has to play to the end. When the game result is already fixed it doesn't matter if LZ continues to play or just pass. There are quite some games with wrong score reported during self play just because some dead stones were on the board. This will affect training result and can not be fixed by any better weight file. 

Thanks for your attention. 

SP Lee

**Comment by roy7** [comment]
New weight files should fix it, when LZ learns that not capturing those groups results in a loss though. The point is the score isn't "wrong". It's wrong if you think about Chinese scoring, but LZ is learning Tromp Taylor scoring. They are similar enough that LZ can play humans with Chinese rules and it will work although LZ will capture dead stones at the end of game when a human wouldn't bother. But LZ has to learn how to score by losing games when she failed to capture those dead stones. Does that make sense?

**Comment by Splee99** [comment]
Theoretically that makes sense. However, that makes the training more tricky because this losing a won game thing. So I think your point is to treat it like an end game training.
