### ISSUE TITLE
Pass at end of the game

### ISSUE THREAD

**Issue by pheasant75** [gcp/leela-zero#743]
I check the game played here using the latest weight:
http://www.yss-aya.com/cgos/viewer.cgi?19x19/SGF/2018/01/24/361864.sgf
White passed without kill some stones in it's territory. White actually wins in Chinese rule.  But the game result, according to the Tromp-Taylor rule is a black win.  I am wondering whether LZ didn't learn to kill stones in the territory because most of the training game result in resigning?  Or does white simply think he is losing and no play can change that (then why not resign)?

**Comment by roy7** [comment]
I'd hope anyone running LZ bots on CGOS aren't running with --dumbpass. But if not, then I don't understand why White would pass there. The pass checking code would score the game as a loss on the board presently for White, and LZ won't pass into a loss without --dumbpass.

**Comment by MaxMaki** [comment]
Could it be that the person running the bot on CGOS has it playing with genmove instead of kgs-genmove_cleanup?

I remember reading a thread that you need to change the genmove on the cgos connection scripts in order to run leela zero there, or it wont clear the board properly?

So might be that the bots on CGOS are configured incorrectly and getting losses that they actually shouldnt.

**Comment by roy7** [comment]
@MaxMaki That's a problem for someone to run Leela on CGOS without knowing better, but not a problem for LZ, since in theory LZ is learning and playing Tromp Taylor scoring anyway.

Most CGOS LZ bots I think are run by someone from Reddit, I asked and he uses -d because the selfplay and match testing does it. So end game pass errors just mean "LZ needs to learn to score better", really. But people insist on thinking it's a bug since they expect LZ to be playing to win at all costs. Not doing strength measurement snapshots during this experiment...

**Comment by killerducky** [comment]
Guys I get Black won the game. Who counted wrong? wO1 is dead, anything else weird happening?

**Comment by roy7** [comment]
@killerducky White wins if it takes the time to capture black's dead stones. By passing without capturing those stones, the game is a win for black. Normally the "don't pass into a loss" check would prevent that, but the CGOS bots run with --dumbpass.

So IMO there's no bug/error  here? Just the bot operator chooses to use --dumbpass so we see LZ's scoring errors (white didn't realize it was going to lose when NN said to pass).

**Comment by killerducky** [comment]
Oh I read the post wrong.

**Comment by odeint** [comment]
@roy7 I had a look over this game ( https://online-go.com/game/11537786 ). Quite nice, good ko fighting, but lost in the end due to passing. Is that a problem with the dumbpass configuration? LZ could have just killed the "seki" in the bottom left, even moving second.

**Comment by roy7** [comment]
Leela Zero scores the board (if you load the sgf and type final_score) as B+2.5. So LZ didn't make an error by passing. The problem is OGS's score estimator (iffy on complex boards) and Leela disagree, and OGS doesn't currently support getting dead stone status from bots. It just auto scores and that's that.

Without dumbpass it might play until every dead stone is gone, like you want on CGOS, but that'd be very annoying for humans on OGS so I don't leave the bot running that way.
