### ISSUE TITLE
Why not a single history plane?

### ISSUE THREAD

**Issue by TFiFiE** [gcp/leela-zero#755]
I've seen superko issues being addressed here, but could anyone tell me what exactly would be ill thought out about simply replacing the 14 input planes concerning the board's past with a single one indicating which moves would (illegally) repeat any earlier position (so not just basic kos)? It seems like an awful waste and an overfitting liability that such a huge part of the input is taken up by mostly redundant information. Or does perhaps knowing the immediate past provide significant (metagaming) benefit in determining where to play next, e.g. strongly help the bot in developing a sense of when to tenuki?

**Comment by gcp** [comment]
>what exactly would be ill thought out about simply replacing the 14 input planes concerning the board's past with a single one indicating which moves would (illegally) repeat any earlier position (so not just basic kos)

That just gives you the information for the current move, not about the next moves.

>It seems like an awful waste and an overfitting liability that such a huge part of the input is taken up by mostly redundant information. 

There's not much waste, input planes are very cheap.

**Comment by grolich** [comment]
The problem is that it is impossible for the network to give correct positional evaluations with only the info you suggested. I'm not saying it's difficult. It is actually impossible.

The problems would arise in any ruleset, whether or not superkos are used.
Simple examples of the problems you'd face:

The exact same stone position can be arrived at with the exact same moves that would create repetitions, however, with the correct positional evaluation being very good for the network in some but very bad in others. 
How? If in some cases the network or the opponent would not be able to play an otherwise decisive move somewhere down the line. 

Your suggested inputs would make it so that the differences between these cases is not visible to the network at all, and thus, it is unable to learn the difference and will return the same evaluation for both the good and the bad positions.
Go positions aren't defined only by their stone positioning and legal/illegal moves...


As to letting the search fix that - that does not seem to be a good idea at all - MCTS as used in AGZ/AZ/LZ barely looks at a tiny fraction of the possibilities, even at the depth to which it happened to reach. Thus, it heavily relies on the network to guide it. 
Unlike more exhaustive searches, it is used with noisy evaluation functions such as neural networks, and it filters out some of the noise. The network itself needs to be able to give the correct evaluation and it should be different for two different positions, even if the inputs you suggested will be identical, at least as much as possible, for the search to be as effective as possible.

Note that even using the AZ planes, and not adopting superkos, the problems are still there, but their occurrence should at least be extremely rare, hopefully not in a sufficient amount to affect network performance.

**Comment by Vandertic** [comment]
BTW, has anyone a clear understanding of why 8 planes are needed? I would say a triple ko should require 5 or 6 planes, since without superko rule the positions would repeat every 6 moves.

**Comment by grolich** [comment]
For the purpose of deciding on the amount of history planes used, there is no theoretical difference between positional superko (as in Chinese rules. PSK doesn't care about whose turn it is, only about the exact stone positioning) and no superko at all.

Any sequence of moves that would end in an illegal repetition in a game with PSK would also cause a repetition without any superko, it's just that in that case, the move won't be prohibited. Rather, it will just case a draw / no result (for our purposes, draw).

Therefore there's no difference in the amount of moves necessary to reach the repetition.

Another thing is, people have a fixation on triple kos, either thinking that's the only way a repetition to occur without tripping the normal ko rule, or the only feasible way in practice...

However, that is not so - In the 21st century  alone, there have been at least 4 professional games that I know of that had quadruple kos in them. That is definitely way above average, but LZ played several orders of magnitude more games than professionals have played in these years, and we need to account for every position ever reached in search, not just ones played, so it's also an important issue to address.

Also, there are ways to form repetitions that do not include only (or at all, sometimes) single stone captures. For those interested in a simple case in systems using area scoring - search for "sending two, returning one". 
LZ is actually susceptible to this because unlike any of the used rule systems, it uses area scoring but no superko rule.

In that sense, it doesn't matter how many history moves you add to the network, if you don't add a lot more of the game history (all of it minus a certain number of first moves...), potential repetitions could change the evaluation of the position and the network will not always be able to know that. However, the likelihood of that affecting LZ would be significantly smaller the more you add.

**Comment by rchs819** [comment]
For anyone who is interested in quadruple KO game
Gu Li vs Lee Sedol on 2012-09-05
https://gogameguru.com/go-commentary-gu-li-vs-lee-sedol-quadruple-ko-game-17th-samsung-cup/
