### ISSUE TITLE
Undo and ponder?

### ISSUE THREAD

**Issue by Marcin1960** [gcp/leela-zero#767]
Is it possible  in self-plays, to move back to the  moment when the game deteriorated as a result of a damaging move, then to ponder thoroughly on other possible moves, and if the much better ones are found to keep them instead of the initial bad one?

**Comment by petgo3** [comment]
In my opinion, if any algorithm knows since which move the game is deteriorated, you could train networks with this algorithm. 
Even the complete training would be obsolete. Any go-program would decide moves with this algorithm.

This algorithm does not exists (now). That why  "to move back to the moment when the game deteriorated" is not possible.
