### ISSUE TITLE
Resigned too early?

### ISSUE THREAD

**Issue by pheasant75** [gcp/leela-zero#777]
http://zero.sjeng.org/viewmatch/62ac54a2bade9e1c0beb8f54d40bf4efa6cb8d656a6540f5dd79922a80c895dc?viewer=wgo

White just lost a few stones.  No life death issue.  Wonder why it just resigned.  Maybe LZ have emotions as well?

**Comment by wctgit** [comment]
Don't know if it's too early (still a noob at Go), but if it _did_ resign too early, then this will presumably eventually be corrected through training. As game play gets tighter and tighter, where the correct assessment of probability of winning becomes more important for determining resignation, then networks will begin to compete more strongly around the tuning of that portion of the network, and presumably this will lead to better and more accurate estimations. I have a hunch this game, even if it _does_ show white resigning too early, does not represent an actual problem with the AI architecture, rather than merely a lack of good judgment based on a lack of sufficient training.

**Comment by jkiliani** [comment]
This was discussed before several times, see #758

**Comment by Dorus** [comment]
Black is ahead (by about 20 points on my crude estimate), and black won. You could let a strong bot analyse this game, but by the look of it the correct player won, so it's only good that the network resigns as early as possible.
