### ISSUE TITLE
Leela defeated 6 dan Hirabot !!! :)

### ISSUE THREAD

**Issue by Marcin1960** [gcp/leela-zero#786]
Victory!

**Comment by Marcin1960** [comment]
LeelaZeroT on KGS

**Comment by LetterRip** [comment]
How many nodes or playouts per turn is that?

**Comment by CheckersGuy** [comment]
On what server did that happen ? Would like to watch some games by Leela myself :P

**Comment by Marcin1960** [comment]
4.2 per 15 sec on average. I overclocked my GPU

**Comment by Marcin1960** [comment]
KGS, LeelaZeroT against Hirabot43

**Comment by apetresc** [comment]
@CheckersGuy He is almost certainly referring to [this game on KGS](http://files.gokgs.com/games/2018/1/30/LeelaZeroT-HiraBot43-9.sgf)

**Comment by wctgit** [comment]
Looks like it still needs some extra training to beat Hirabot more reliably, and perhaps a larger network architecture to see big groups and liberties, but it's a good start nonetheless. Here's a link to all LZT's games: http://www.gokgs.com/gameArchives.jsp?user=LeelaZeroT. It's fun reading the commentary/kibitzing in the SGF's move comments. :-)

**Comment by marcocalignano** [comment]
But so do we believe that with the last network we reach 6 Dan amateur on KGS ?

**Comment by Marcin1960** [comment]
Maybe strong 5 dan against other bots.

**Comment by marcocalignano** [comment]
@roy7 or @Marcin1960 I wanted to ask a go teacher to play with Leelaz do you think that he wants to can we set it up? If yes we would have to agree on a date and time.

**Comment by WhiteHalmos** [comment]
There's also LeelaZSlow and LeelaZFast on KGS.
RoyalZero and RoyalZeroSlow on OGS.

These are usually always available.

**Comment by marcocalignano** [comment]
I know but with the teacher I'd like to have some supervision if possible and maybe reserve the Bot for that date and so on.

**Comment by roy7** [comment]
@marcocalignano I'd just suggest any time they want to do something with LZ, if they are going to play online bots, just play RoyalZero or RoyalZeroSlow on OGS. They are reliable bots and available 24/7. I used to sometimes stop all other bots and change my settings to use all 16 cores for Leela when a pro wanted to play vs Leela, but it's been a long time since that happened. These days I'm content to just operate the bots hands off and not set up special situations. :)
