### ISSUE TITLE
Time management

### ISSUE THREAD

**Issue by TFiFiE** [gcp/leela-zero#788]
From the looks of it, the current time management code doesn't appear to be particularly sophisticated and as I can't find any existing thread dedicated to this subject, let me so bold as to create one and ask what plans and/or ideas there are concerning this.

Some existing literature:
https://www.remi-coulom.fr/Publications/TimeManagement.pdf
https://dke.maastrichtuniversity.nl/m.winands/documents/time_management_for_monte_carlo_tree_search.pdf

**Comment by jkiliani** [comment]
The implementation of --visits is a form of time management, since it allocates more resources to positions with relatively free move choices, and less when responses are forced. So far, it hasn't been used for self-play however.

**Comment by odeint** [comment]
From the paper:
> Comparison with fixed time per move. To illustrate the
effect of successful time management, two additional experiments
were conducted with OREGO using fixed time
per move in 13×13 Go. In the first experiment, the time
per move (650 msec) was set so that approximately the
same win rate against GNU GO was achieved as with EXPSTONES
and STOP at 30 seconds per game. The result of
2500 games demonstrated that the average time needed per
game was 49.0 seconds—63% more than needed by our timemanagement
strategy. In the second experiment, the time per
move (425 msec) was set so that the average time per game
was approximately equal to 30 seconds. In 2500 games under
these conditions, OREGO could only achieve a 27.6% win
rate, 11.5% less than with EXP-STONES and STOP.

To be honest, 27.6% vs 39.1% versus a benchmark doesn't seem that big a deal. That was comparing their best strategy against the pretty stupid equal-time-per move. That's just about 1-2 generations of new networks for LZ. Even AlphaGo against Lee Sedol didn't seem to use fancy time management, so DeepMind also didn't think it worth working too much on. Of course, we're all volunteers and do it for fun and learning, so if someone wants to implement time management strategies, that would still be cool!

**Comment by gcp** [comment]
>The implementation of --visits is a form of time management, since it allocates more resources to positions with relatively free move choices, and less when responses are forced. So far, it hasn't been used for self-play however.

I didn't want to change this mid run, but now that all clients should have --visits capability it would be possible. But IIRC previous results were inconclusive and of course tree reuse + NNCache=TTable have a pretty big impact on those two?

**Comment by gcp** [comment]
Fancy time management is nice for non-self play games, but indeed you just can't expect to get too much out of this.

One very obvious thing you can do is to terminate the search early if no other move can possibly overcome the current best.

**Comment by jkiliani** [comment]
How does Leela 0.11 do it? With verbose output I regularly see "allowing early exit" or "allowing very early exit", is this based on the the number of playouts being very lopsided to one particular response?

**Comment by gcp** [comment]
Early exit means that the second best move is statistically very unlikely to overtake the current best move. (There's cheating here and assuming the underlying distributions are stationary, which of course they aren't, so it's much more strict than 95%)

Very early exit means that one move has an overwhelming prior and a short search did not find anything that indicates that would be incorrect.

Even such simple heuristics take a lot of tuning to get right. Ask @roy7 about some war stories.

**Comment by killerducky** [comment]
See below early results, I'll let it run some more. This is with latest next (da2d38) and weights (adf2d2).
```
lzbase-p-1600-t-1 v lzbase-v-2600-t-1 (160/1000 games)
board size: 19   komi: 7.5
                    wins              black         white       avg cpu
lzbase-p-1600-t-1     68 42.50%       28 35.00%     40 50.00%    296.50
lzbase-v-2600-t-1     92 57.50%       40 50.00%     52 65.00%    288.17
                                      68 42.50%     92 57.50%
```
I undershot slightly on CPU time, -v 2600 runs a bit faster than -p 1600. For self-play the tuning of equivalent CPU time for visits vs playouts will be different since there is more tree reuse. I can calculate that number later if maintaining equivalent average playouts is important.

**Comment by marcocalignano** [comment]
@killerducky did you used "validation" from the next branch for the test?

**Comment by killerducky** [comment]
@marcocalignano no I use gomill's ringmaster.

**Comment by marcocalignano** [comment]
@killerducky Do you know that you can give different binary and different parameter to leelaz with the /next  validation?

**Comment by killerducky** [comment]
Final results:
```
lzbase-p-1600-t-1 v lzbase-v-2600-t-1 (408/1000 games)
board size: 19   komi: 7.5
                    wins              black          white        avg cpu
lzbase-p-1600-t-1    182 44.61%       78  38.24%     104 50.98%    281.46
lzbase-v-2600-t-1    226 55.39%       100 49.02%     126 61.76%    274.18
                                      178 43.63%     230 56.37%
```

**Comment by jkiliani** [comment]
Looks significant even if not huge like the FPU tuning...

**Comment by gcp** [comment]
Elo diff = 37.6148 +- 33.9735
Score = 0.553922
LLR    = 2.36574
LB     = -2.94444
UB     = 2.94444
Status = 0

It wouldn't pass SPR [0, 5] but obviously it's much more likely to be a gain than not.

**Comment by sethtroisi** [comment]
I independently had this thought and am most of the way throught testing [my implementation](https://github.com/gcp/leela-zero/compare/next...sethtroisi:t__fast_thin_tree?expand=1)

I have these result

```
100 playouts versus 100 "playouts" stopping when it's not possible for 2nd node to pass 1st in remaining playouts

leelaz-feb-03 v leelaz-short-circuit (200/200 games)
board size: 19   komi: 7.5
                       wins              black          white       avg cpu
leelaz-feb-03           105 52.50%       53  53.00%     52 52.00%     14.14
leelaz-short-circuit     95 47.50%       48  48.00%     47 47.00%      9.67
                                         101 50.50%     99 49.50%
```

```
1600 playouts vs 2700 "playouts" stopping when 2nd can't pass 1st

leelaz-feb-03 v leelaz-short-circuit (116/200 games)
board size: 19   komi: 7.5
                       wins              black         white       avg cpu
leelaz-feb-03            53 45.69%       31 52.54%     22 38.60%    155.93
leelaz-short-circuit     63 54.31%       35 61.40%     28 47.46%    155.81
                                         66 56.90%     50 43.10%
```

**Comment by Mardak** [comment]
This is fixed with various time management improvements in leelaz 0.14 https://github.com/gcp/leela-zero/releases/tag/v0.14
