### ISSUE TITLE
Is there any issue with running autogtp with 2 threads?

### ISSUE THREAD

**Issue by barrtgt** [gcp/leela-zero#791]
I'm asking because my computer can run over 60% more nodes with 2 threads with leelaz as I am currently stuck with -g 1 with my gpu.

**Comment by killerducky** [comment]
I saw on reddit you mentioned there is an opencl issue with your setup when you run autogtp -g 2. Can you describe that?

**Comment by killerducky** [comment]
Quoting @barrtgt from reddit: 

> Opened. Using more threads runs multiple searches in the same game simultaneously , which is different than running multiple games simultaneously. Surely you've heard of the check that autogtp does occasionally with a cpu implementation of the network to confirm the results of the GPU starting with 0.10.

Oh, is this the same issue we discussed before? Sorry I thought gcp made it clear he doesn't want systems with buggy OpenCL drivers running autogtp. I don't think trying to find workarounds like this is a good idea. The self-check is not guaranteed to find when your OpenCL driver returns bad results. It's very possible your autogtp is still returning garbage results.

Frankly I'm a little upset right now. Either I'm misunderstanding the situation, or you are going to reddit trying to get a rogue binary that allows you to submit bad results using autogtp. Ok I admit this is not a totally fair representation, but like I said I'm a little upset right now. Please explain why I shouldn't be upset.

For reference here is what gcp said the last time this issue was raised.
https://github.com/gcp/leela-zero/issues/597#issuecomment-355900653

**Comment by killerducky** [comment]
Ok I have taken some deep breaths and thought about it more. I deleted my overreaction in the previous post, sorry about that. 

For reference, the error message is `Error in OpenCL calculation: expected %f got %f` and `Update your GPU drivers or reduce the amount of games played simultaneously.`

When you run two instances of autogtp -g 1 does it run for days on end without ever seeing that error? I don't see why that would work but one instance of autogtp -g 2 would die.

**Comment by barrtgt** [comment]
It sounds like you have a personal issue with me more than anything. Where do you get that it's very possible? And the rogue binary accusation? You are unbelievable. I have given plenty of support for this project from the beginning. Why would you ever think I would intentionally want to harm it? I've have always wanted to improve gcp software and helped him several times with reporting bugs with Leela. I have been running for over three weeks with no issues whatsoever. When I discovered the issue with -g 2 weeks ago, I stopped using it immediately.

**Comment by billyswong** [comment]
Come to think of it, since running 2 threads / 2 games gains only 60%, not >90% or 100%, each individual games will be slower even if there were no bugs in barrtgt's display card/driver. So it isn't a huge loss? If running a heavier 256-filter net always lead to bug, then that will be a bigger issue.

**Comment by killerducky** [comment]
@barrtgt Sorry again, I was out of line. I'm also passionate about this project and I over reacted. I'm embarrassed I didn't take extra time to calm down before posting that. I hope we can work together to get to the bottom of this issue.

I'm trying to figure out why the driver would work when you run two autogtp -g 1 but fail with autogtp -g 2. Is it possible that one of the two autogtp -g 1 stopped and the other one continued? 

The reason I keep asking is that it seems these two use cases should be identical. Either autogtp runs 2 instances of leela, or two separate autogtps run 1 instance of leela each. But one case works and the other doesn't. Can anyone think of a reason why?

**Comment by barrtgt** [comment]
Closing issue do to conflicts. I'll stick with what works.
