### ISSUE TITLE
Invisible self-ataris at the edge of the board

### ISSUE THREAD

**Issue by afalturki** [gcp/leela-zero#793]
I was looking at the latest self-play game I submitted and noticed white doing a self-atari on move 312 at the edge of the board. However, black doesn't take the stones but protects his own instead! Since this is not the first time I notice such self-ataris happening, I was wondering if this was indicative of some inherent weakness in the architecture or size of the network that makes it blind to self-ataris at the edge of the board or is just something that is going to be solved by more self-play. I'm asking since it's a bit unexpected that the network with its current strength would make such a basic mistake.

This is the game I'm talking about:
http://zero.sjeng.org/view/92b8a411cdafdb6beb9097db9f94b4c6fb22aa3b5ae7627877f2d1ae0c3a52f8?viewer=wgo

**Comment by ThorAvaTahr** [comment]
It doesnt change the result of the game and leelaz is blind to score, its only aware of winning chances. I guess the winning chance does not change from black's point of view (both very close to 1), so it doesn't matter how to respond.

**Comment by Vandertic** [comment]
It may be that in some conditions LZ has still difficulties counting liberties of border groups, since the architecture makes it a little bit tricky to learn this.
In fact the convolutional layers are translation invariant and they can only understand that the border behaves differently by looking to the two input planes that encode the current player (since one of these is a 19x19 grid of ones and the convolutional filter sees zeros outside the border). Unfortunately, the net has to learn that it has to look to either of the two planes (or to their sum) because we don't have a constant 19x19 all-ones input plane. If this knowledge "happens" in the first layer, the ability to count liberties of border groups has effectively one less layer to count on.

**Comment by gcp** [comment]
A constant ones plane is equivalent to white_to_move * 1.0 + black_to_move * 1.0 which can be fused with whatever other operation is happening in that layer, so in no case do you lose a layer.

**Comment by wctgit** [comment]
And anyway, while it isn't usually an optimal move (because the opponent will probably immediately take advantage of it) a self-atari may actually be a winning move, if the opponent does not take advantage of it for whatever reason, _or_ if taking advantage of it would cause some undesirable result for the opponent, such as a snapback. Thus, I would imagine that it is something that the neural net will have to figure out on its own through training. Thus, I'm not surprised that white, in desperation, played the move.

**Comment by Vandertic** [comment]
Whoops, gcp is right again: constant plane or what we have now are completely equivalent. Anyhow it *may* be more difficult for the NN to count liberties on the border than in the center.
