### ISSUE TITLE
Does not compile with last OS distributives

### ISSUE THREAD

**Issue by GD-fix** [gcp/leela-zero#807]
Linux all.
Doesn't compile:
```
g++: ошибка: unrecognized command line option «-std=c++14»
Makefile:52: ошибка выполнения рецепта для цели «Network.o»
make[1]: *** [Network.o] Ошибка 1
```
Is there compiled CPU only release for Linux (like this one: [https://www.sjeng.org/leela.html](url))?

Thanks in advance.

**Comment by ihavnoid** [comment]
What is your gcc version?  It seems that your compiler does not support the latest c++ standard.

**Comment by seopsx** [comment]
Installed the recommended packages on Ubuntu 17.10.
Previously has compiled successfully. gcc version 4.9.3.

Here is the compile error:

`leela-zero/src$ make
Detected OS: Linux
make CC=gcc CXX=g++ \
	CXXFLAGS='-I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG'  \
	LDFLAGS=' -flto -g' \
	leelaz
make[1]: Entering directory '/home/seopsx/usr/src/leela-zero/src'
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Network.o Network.cpp
In file included from OpenCL.h:27:0,
                 from OpenCLScheduler.h:26,
                 from Network.cpp:44:
./CL/cl2.hpp:1831:25: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
     const cl_type get() const { return object_; }
                         ^
Network.cpp: In static member function ‘static std::vector<float> Network::winograd_transform_f(const std::vector<float>&, int, int)’:
Network.cpp:131:39: warning: missing initializer for member ‘std::array<float, 12ul>::_M_elems’ [-Wmissing-field-initializers]
     auto temp = std::array<float, 12>{};
                                       ^
Network.cpp: In static member function ‘static std::pair<int, int> Network::load_v1_network(std::ifstream&)’:
Network.cpp:200:42: error: use of deleted function ‘std::basic_stringstream<char>::basic_stringstream(const std::basic_stringstream<char>&)’
         auto iss = std::stringstream{line};
                                          ^
In file included from Network.cpp:29:0:
/usr/include/c++/4.9/sstream:502:11: note: ‘std::basic_stringstream<char>::basic_stringstream(const std::basic_stringstream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_stringstream : public basic_iostream<_CharT, _Traits>
           ^
/usr/include/c++/4.9/sstream:502:11: error: use of deleted function ‘std::basic_iostream<char>::basic_iostream(const std::basic_iostream<char>&)’
In file included from /usr/include/c++/4.9/fstream:38:0,
                 from Network.h:30,
                 from Network.cpp:21:
/usr/include/c++/4.9/istream:795:11: note: ‘std::basic_iostream<char>::basic_iostream(const std::basic_iostream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_iostream
           ^
/usr/include/c++/4.9/istream:795:11: error: use of deleted function ‘std::basic_istream<char>::basic_istream(const std::basic_istream<char>&)’
/usr/include/c++/4.9/istream:58:11: note: ‘std::basic_istream<char>::basic_istream(const std::basic_istream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_istream : virtual public basic_ios<_CharT, _Traits>
           ^
/usr/include/c++/4.9/istream:58:11: error: use of deleted function ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’
In file included from /usr/include/c++/4.9/ios:44:0,
                 from /usr/include/c++/4.9/istream:38,
                 from /usr/include/c++/4.9/fstream:38,
                 from Network.h:30,
                 from Network.cpp:21:
/usr/include/c++/4.9/bits/basic_ios.h:66:11: note: ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ios : public ios_base
           ^
In file included from /usr/include/c++/4.9/ios:42:0,
                 from /usr/include/c++/4.9/istream:38,
                 from /usr/include/c++/4.9/fstream:38,
                 from Network.h:30,
                 from Network.cpp:21:
/usr/include/c++/4.9/bits/ios_base.h:792:5: error: ‘std::ios_base::ios_base(const std::ios_base&)’ is private
     ios_base(const ios_base&);
     ^
In file included from /usr/include/c++/4.9/ios:44:0,
                 from /usr/include/c++/4.9/istream:38,
                 from /usr/include/c++/4.9/fstream:38,
                 from Network.h:30,
                 from Network.cpp:21:
/usr/include/c++/4.9/bits/basic_ios.h:66:11: error: within this context
     class basic_ios : public ios_base
           ^
In file included from /usr/include/c++/4.9/fstream:38:0,
                 from Network.h:30,
                 from Network.cpp:21:
/usr/include/c++/4.9/istream:795:11: error: use of deleted function ‘std::basic_ostream<char>::basic_ostream(const std::basic_ostream<char>&)’
     class basic_iostream
           ^
In file included from /usr/include/c++/4.9/istream:39:0,
                 from /usr/include/c++/4.9/fstream:38,
                 from Network.h:30,
                 from Network.cpp:21:
/usr/include/c++/4.9/ostream:58:11: note: ‘std::basic_ostream<char>::basic_ostream(const std::basic_ostream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ostream : virtual public basic_ios<_CharT, _Traits>
           ^
/usr/include/c++/4.9/ostream:58:11: error: use of deleted function ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’
In file included from /usr/include/c++/4.9/fstream:38:0,
                 from Network.h:30,
                 from Network.cpp:21:
/usr/include/c++/4.9/istream:795:11: error: use of deleted function ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’
     class basic_iostream
           ^
In file included from Network.cpp:29:0:
/usr/include/c++/4.9/sstream:502:11: error: use of deleted function ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’
     class basic_stringstream : public basic_iostream<_CharT, _Traits>
           ^
/usr/include/c++/4.9/sstream:502:11: error: use of deleted function ‘std::basic_stringbuf<char>::basic_stringbuf(const std::basic_stringbuf<char>&)’
/usr/include/c++/4.9/sstream:64:11: note: ‘std::basic_stringbuf<char>::basic_stringbuf(const std::basic_stringbuf<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_stringbuf : public basic_streambuf<_CharT, _Traits>
           ^
In file included from /usr/include/c++/4.9/ios:43:0,
                 from /usr/include/c++/4.9/istream:38,
                 from /usr/include/c++/4.9/fstream:38,
                 from Network.h:30,
                 from Network.cpp:21:
/usr/include/c++/4.9/streambuf:802:7: error: ‘std::basic_streambuf<_CharT, _Traits>::basic_streambuf(const std::basic_streambuf<_CharT, _Traits>&) [with _CharT = char; _Traits = std::char_traits<char>]’ is private
       basic_streambuf(const basic_streambuf& __sb)
       ^
In file included from Network.cpp:29:0:
/usr/include/c++/4.9/sstream:64:11: error: within this context
     class basic_stringbuf : public basic_streambuf<_CharT, _Traits>
           ^
Network.cpp: In static member function ‘static std::pair<int, int> Network::load_network_file(std::string)’:
Network.cpp:291:41: error: use of deleted function ‘std::basic_ifstream<char>::basic_ifstream(const std::basic_ifstream<char>&)’
     auto wtfile = std::ifstream{filename};
                                         ^
In file included from Network.h:30:0,
                 from Network.cpp:21:
/usr/include/c++/4.9/fstream:430:11: note: ‘std::basic_ifstream<char>::basic_ifstream(const std::basic_ifstream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ifstream : public basic_istream<_CharT, _Traits>
           ^
/usr/include/c++/4.9/fstream:430:11: error: use of deleted function ‘std::basic_istream<char>::basic_istream(const std::basic_istream<char>&)’
/usr/include/c++/4.9/fstream:430:11: error: use of deleted function ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’
/usr/include/c++/4.9/fstream:430:11: error: use of deleted function ‘std::basic_filebuf<char>::basic_filebuf(const std::basic_filebuf<char>&)’
/usr/include/c++/4.9/fstream:72:11: note: ‘std::basic_filebuf<char>::basic_filebuf(const std::basic_filebuf<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_filebuf : public basic_streambuf<_CharT, _Traits>
           ^
In file included from /usr/include/c++/4.9/ios:43:0,
                 from /usr/include/c++/4.9/istream:38,
                 from /usr/include/c++/4.9/fstream:38,
                 from Network.h:30,
                 from Network.cpp:21:
/usr/include/c++/4.9/streambuf:802:7: error: ‘std::basic_streambuf<_CharT, _Traits>::basic_streambuf(const std::basic_streambuf<_CharT, _Traits>&) [with _CharT = char; _Traits = std::char_traits<char>]’ is private
       basic_streambuf(const basic_streambuf& __sb)
       ^
In file included from Network.h:30:0,
                 from Network.cpp:21:
/usr/include/c++/4.9/fstream:72:11: error: within this context
     class basic_filebuf : public basic_streambuf<_CharT, _Traits>
           ^
Network.cpp:301:42: error: use of deleted function ‘std::basic_stringstream<char>::basic_stringstream(const std::basic_stringstream<char>&)’
         auto iss = std::stringstream{line};
                                          ^
Network.cpp: In static member function ‘static void Network::show_heatmap(const FastState*, Network::Netresult&, bool)’:
Network.cpp:962:38: error: ‘rbegin’ was not declared in this scope
         std::stable_sort(rbegin(moves), rend(moves));
                                      ^
Network.cpp:962:51: error: ‘rend’ was not declared in this scope
         std::stable_sort(rbegin(moves), rend(moves));
                                                   ^
Makefile:61: recipe for target 'Network.o' failed
make[1]: *** [Network.o] Error 1
make[1]: Leaving directory '/home/seopsx/usr/src/leela-zero/src'
Makefile:4: recipe for target 'default' failed
make: *** [default] Error 2
`

**Comment by gcp** [comment]
gcc 4.9.3 is very old and does not support C++14, which is required for Leela Zero, as described in the README.

Ubuntu 17.04 ships with gcc 5.4 or even gcc 6.3 so you have done something to your installation to mess it up.

```
sudo update-alternatives --config gcc
sudo update-alternatives --config g++
```

**Comment by GD-fix** [comment]
It's default gcc version on last official release of OpenSUSE (42.3). So it isn't outdated. Computer is local only (so it will not updates until new OS release).

Finally, will be there docker-like release of Leela-zero (with CPU only too) for most people can develop it, or it still will be only 4(!) releases for "experts" only and 2 - for admins only?
Excuse me for my English, please...

**Comment by GD-fix** [comment]
From man gcc:
```
-std=
           Determine the language standard.   This option is currently only supported when compiling C or C++.
           The compiler can accept several base standards, such as c90 or c++98, and GNU dialects of those standards, such as gnu90 or gnu++98.  When a base standard is specified, the compiler accepts all programs following that standard plus those using GNU
           extensions that do not contradict it.  For example, -std=c90 turns off certain features of GCC that are incompatible with ISO C90, such as the "asm" and "typeof" keywords, but not other GNU extensions that do not have a meaning in ISO C90, such as
           omitting the middle term of a "?:" expression. On the other hand, when a GNU dialect of a standard is specified, all features supported by the compiler are enabled, even when those features change the meaning of the base standard.  As a result, some
           strict-conforming programs may be rejected.  The particular standard is used by -Wpedantic to identify which features are GNU extensions given that version of the standard. For example -std=gnu90 -Wpedantic warns about C++ style // comments, while
           -std=gnu99 -Wpedantic does not.

           A value for this option must be provided; possible values are

           c90
           c89
           iso9899:1990
               Support all ISO C90 programs (certain GNU extensions that conflict with ISO C90 are disabled). Same as -ansi for C code.

           iso9899:199409
               ISO C90 as modified in amendment 1.

           c99
           c9x
           iso9899:1999
           iso9899:199x
               ISO C99.  This standard is substantially completely supported, modulo bugs and floating-point issues (mainly but not entirely relating to optional C99 features from Annexes F and G).  See <http://gcc.gnu.org/c99status.html> for more information.
               The names c9x and iso9899:199x are deprecated.

           c11
           c1x
           iso9899:2011
               ISO C11, the 2011 revision of the ISO C standard.  This standard is substantially completely supported, modulo bugs, floating-point issues (mainly but not entirely relating to optional C11 features from Annexes F and G) and the optional Annexes K
               (Bounds-checking interfaces) and L (Analyzability).  The name c1x is deprecated.

           gnu90
           gnu89
               GNU dialect of ISO C90 (including some C99 features).

           gnu99
           gnu9x
               GNU dialect of ISO C99.  The name gnu9x is deprecated.

           gnu11
           gnu1x
               GNU dialect of ISO C11.  This is the default for C code.  The name gnu1x is deprecated.

           c++98
           c++03
               The 1998 ISO C++ standard plus the 2003 technical corrigendum and some additional defect reports. Same as -ansi for C++ code.

           gnu++98
           gnu++03
               GNU dialect of -std=c++98.

           c++11
           c++0x
               The 2011 ISO C++ standard plus amendments.  The name c++0x is deprecated.

           gnu++11
           gnu++0x
               GNU dialect of -std=c++11.  The name gnu++0x is deprecated.

           c++1y
               The 2014 ISO C++ standard plus amendments, tentatively planned for 2014.  Support is experimental, and will almost certainly change in incompatible ways in future releases.

           gnu++1y
               GNU dialect of -std=c++1y.  Support is experimental, and will almost certainly change in incompatible ways in future releases.

           c++1z
               The next revision of the ISO C++ standard, tentatively planned for 2017.  Support is highly experimental, and will almost certainly change in incompatible ways in future releases.

           gnu++1z
               GNU dialect of -std=c++1z.  Support is highly experimental, and will almost certainly change in incompatible ways in future releases.
```
So, there is bug in Leela-zero code (1y->14)...

**Comment by gcp** [comment]
>So, there is bug in Leela-zero code (1y->14)...

There is no bug, as you were already explained, your compiler it outdated. It says "1z" because they didn't know yet they would finish the standardization in 2014. That's how old it is!.
