### ISSUE TITLE
How to motivate donnors

### ISSUE THREAD

**Issue by kris-computer-go** [gcp/leela-zero#81]
I think it would be good idea to put some more statistics to zero.sjeng.org.
For this login for each user would be necessary. Then every user would see how many games he'd uploaded. Maybe people would like to have an individual rank (like folding@home for example).
Otherwise many clients will lose interest very soon i'm afraid, because they simple can't see their specific results.

**Comment by tux3** [comment]
Sounds like a good idea to me, people love getting do for imaginary internet points

**Comment by olbrichj** [comment]
It might be something to consider later on. There were suggestions to make it boinc compatible. So I guess a good working infrastructure has a higher priority right now.

On the other hand, I'm really glad to see how many clients are there now. :)

**Comment by roy7** [comment]
I doubt we'll do full logins, but I can report back how many games a client has uploaded when they check in based on IP. Dynamic IP people won't be able to rely on it long term. But it'll be something at least.

I'll try add more basic stats this weekend for people to enjoy. :)

**Comment by Marcin1960** [comment]
I posted info on couple of the main Facebook Go forums:

There is a very interesting project going on. Open source, community effort of following the example of AlphaGo Zero - the new idea of going beyond human input and limitations.

People can contribute programming, ideas and very important - donating time on the CPUs and GPUs (we do not have Google's resources, butwe still can manage).

You can learn details at:

https://github.com/gcp/leela-zero

**Comment by olbrichj** [comment]
instead of using the IP, maybe just use an UUID?

I like seeing how many clients worked in total, but maybe it's more useful to see how many uploaded games in the last 24h. This way, we have some kind of indicator how much capacity our network has at the moment.

**Comment by sthalik** [comment]
Contributors sharing GPU time would go a long way.

One thing is confusing here -- is each user deriving their own network, duplicating work, or do you split the resources appropriately? If there's too much inefficiency we might want to wait for better distributed coordination.

**Comment by roy7** [comment]
What's distributed is self-play games using the currently best known network at that time. Training can't be distributed and the author runs the training locally on his system. What takes the most time in the overall total process though is getting new game data. So the bottleneck is being offset via the distributed approach.

**Comment by zannet** [comment]
lets make a gocoin, a bitcoin alt...

**Comment by Marcin1960** [comment]
Perhaps to list the country/region (no IP) of the top 3 contributors (with number of games)?

**Comment by Marcin1960** [comment]
Or better yet - little table with regions breakup.

**Comment by TasmaniaKrama** [comment]
Make baduk cryptocurrency. You get rewarded for each game you post to the server calculated by pulling the current network. You would need to input your BadukCoin address in the terminal and get $$$.

**Comment by mmun** [comment]
How would you ensure that people are not submitting fake games to inflate their score?

**Comment by amirlb** [comment]
You could grant the reward for a better network instead of granting it for games, larger blocks but incentives exactly what you want

**Comment by lane-westlund** [comment]
>How would you ensure that people are not submitting fake games to inflate their score?

This was mentioned elsewhere by the project owner, but I thought I'd share here.  Summary: send one task to two clients, verify their output matches. 
http://boinc.berkeley.edu/wiki/How_BOINC_works

If I understand the current state of things, this is not quite possible in this project yet, due to some randomness known only to the client.

>You could grant the reward for a better network instead of granting it for games, larger blocks but incentives exactly what you want

Also, if I understand things correctly... this isn't possible, since you aren't submitting a new network, but rather we're all submitting a bunch of games payed with the same network.

**Comment by amirlb** [comment]
The BOINC verification idea is a very good one, I wonder why no blockchain does that.

Anyway, my suggestion for the hypothetical gocoin is to use a different protocol, which submits networks in order to mine a block.
Our community finds around 2 statistically significant improvements to the network per week. Google's cluster found an improved network every few minutes, which is completely reasonable for a blockchain.
If the altcoin motivates donors, we'll probably get to some point in the middle, say one in a few hours. That's slow but still kind of viable IMO. The only problem is that there might be only a small gap between AGZ performance and perfect play, at which the altcoin stops. We can overcome this by allowing networks for handicapped games and other board sizes to generate blocks.

**Comment by sthalik** [comment]
> The BOINC verification idea is a very good one, I wonder why no blockchain does that.

On a tangent, blockchain verification has no central component.

Submitting jobs can work if connection latency isn't a problem. As long as the job server can send short instructions for reproducible games (preset random seed, deterministic algorithm).

**Comment by OmnipotentEntity** [comment]
Blockchain requires problems that are hard to solve and easy to verify.

Currently, most coin systems require finding salts to make the hash of blocks have a certain amount of 0s at the beginning.  This is good because it's hard to solve and easy to verify.

Go is hard to solve, but it is not easy to verify.  If I show you a literally perfect Go game, you can't verify it's perfect without performing the same work I did to generate it.  (Just as if I showed you the solution to a tsumego, you would need to verify it by solving the tsumego yourself.)

If I gave you a better network, it still takes hours of computer time to verify that this network is better than the old one, and moreover, you still would not have an effective way signing a block of transactions.  If you simply included the better network in the block of transactions and signed it, it's still only a statistical gain, meaning it's not absolutely verifiable, only statistically verifiable.  If you have a network that only has a 50.1% win rate over the last network, you would need to play thousands of games to be confident to a few sigma that the network is indeed an improvement.

So a Leela coin idea is probably a non-starter.
