### ISSUE TITLE
games uploaded multiple times

### ISSUE THREAD

**Issue by alreadydone** [gcp/leela-zero#810]
@roy7 
Has the server been down for a while? When I woke up this morning I found the number of games in past hour was a lot less than I expected. Then I found that a lot of game data (curl_save*.bin, ~~*.sgf, *.train,~~ *.sgf.gz, *.txt.0.gz) files have accumulated under my autogtp directory, and my ~700 autogtp instances were all trying to upload these data instead of playing games; many of them (if not all) unsurprisingly were unable connect to the server.
```
Upload failed. Curl Exit code: 7
Network connection to server failed.
NetworkException: Curl returned non-zero exit code 7
Retrying when next game is finished.
```
(No games are actually played between two such blocks of error messages.)

I observed that many games were uploaded and shown to be stored in database multiple times by different autogtp instances (for example Game data 1c9f80668d303e9b1f3a9589bab05f5e8813d498cb381ed7539201b8c4c2ef80) and I hope you'll remove any duplicates from the database if this is not done automatically.

The current behavior of autogtp is undesirable at least in my use case (several hundreds of instances run from the same directory): I think in the last few hours it caused heavy burden on the server and wasted bandwidth and computing resource. I hope that changes will be made to ensure that game data dealt with by one autogtp instance won't be picked up by another instance.

**Comment by roy7** [comment]
We used to ignore duplicated uploads but people didn't like that since early game losses would only be included once.

autogtp stuff is all handled by @marcocalignano. Maybe your autogtp instances, since you run tons of them out of 1 directory, should make a subdirectory based on the pid and store things in that?

**Comment by roy7** [comment]
Wait, I think we solved "duplicates" which were played by different people by including the seed in the SGF comments. So the hashes are different. If you have the same hash being uploaded more than once, it won't be duplicated in the database so far as I can recall. So no harm to the data on our end. Just server isn't prepared to handle hundreds of simultaneous uploads I guess.

**Comment by alreadydone** [comment]
I think the resume feature now works well with multiple autogtp instances; one stored game will not be resumed twice. So I am thinking of a similar modification to autogtp that make sure one game is not uploaded twice.

**Comment by marcocalignano** [comment]
@alreadydone The problem is that the games are saved in file, loaded in memory before they are sent and deleted after the server acknowledge the reception of the data. if in the mean time one or more of your ~700 autogtp process pick up the same file, unless you have interprocess communication or like @roy7 said ~700 different subdirectories there is nothing I can really do. Having subdirectories is also not really the case with -t or -s option because the process might exit after saving the game and there will be no one left to pick it up and send it to the server.

**Comment by alreadydone** [comment]
After examining console outputs and reading the code, I can now pinpoint a problem that is easy to fix.
https://github.com/marcocalignano/leela-zero/blob/8c6fe0e1e9c12a8ea9bf39d09d63ee45fbcb641f/autogtp/Management.cpp#L602-L602
I suggest that you move the for loop inside the try...catch. Otherwise, sendAllGames will try to upload 50 times if there are 50 curl_save*.bin in the directory, even if uploading fails at the beginning. This fix should alleviate the problem a lot, since autogtp will temporarily stop trying connecting to server; giveAssignment or getResult will do getWork and start playing another game (although getWork will still try to connect to server three times to get a job; you may find a way to fix this, possibly by introducing a global variable indicating network connection failure that is reset at the beginning of sendAllGames).

**Comment by alreadydone** [comment]
@marcocalignano Made the changes myself and created a pull request https://github.com/marcocalignano/leela-zero/pull/5.
