### ISSUE TITLE
why these two  netwroks' win rates have so big difference?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#829]
Start Date | Network Hashes | Wins / Losses | Games | SPRT
-- | -- | -- | -- | --
2018-02-07 08:26 | d6f3a68b VS 54bfb7b8 | 57 : 38 (60.00%) | 95 / 400 |  
2018-02-07 06:18 | b0024388 VS 54bfb7b8 | 0 : 46 (0.00%) | 46 / 400 | fail

**Comment by odeint** [comment]
How can we know? Introspection into neural networks is hard, though we've seen some nice work on ladders and distant eyes here. The broader picture view would be that you have to go through a dip in playing strength if you want to change to a bigger maximum instead of just optimizing the peak you're at. That's pure speculation though.

**Comment by ihavnoid** [comment]
Looking at the games, I think b0024388 has a life-and-death problem.  In the dozen games I looked, it had big and small groups captured, and then after many plays it finally resigns.  Some games it resigns after 100+ more moves after the fate has been sealed.  I have a feeling that it un-learned something while trying to learn something else...

**Comment by l1t1** [comment]
un-learned something == forgot?
