### ISSUE TITLE
AlphaGo Teaching Tool

### ISSUE THREAD

**Issue by syjytg** [gcp/leela-zero#861]
https://alphagoteach.deepmind.com/

It gives us the probabilities of the common openings. From this, we know that Black's best opening move has a 47.1% chance of winning (at Q16), which probably means that perfect play is a White victory, given how strong AlphaGo is. Anyway, will knowing all these probabilities help us get AlphaGo's weights? Maybe we can hardcode these published probabilities into LZ and then train from there to get the AlphaGo's weights?

**Comment by jkiliani** [comment]
Those probabilities are from AG Master, not AG, so they may easily be biased from training data. Also, where is the sense into hardcoding any information into an engine with a neural net? At the moment LZ still has a much smaller net compared to AGZ, so you'll need some patience here. Once Leela Zero is really strong, its opening book will likely also converge to the one published by Deepmind. In cases where that doesn't happen it will simply mean that there's disagreement on what works best in the opening, which should not greatly surprise any strong Go players.

**Comment by wpstmxhs** [comment]
I think that idea seems not working.

1) That tool provides us what AlphaGo Master thinks on fuseki period. But best moves and winning rate informations from that are from AlphaGo Master. These are not compatible to us. If we try to train that info in supervised manner, -In fact, I also tried that already-, it will not work well. Also, it will cause overfitting problem because of very small dataset.

Leela Zero would play another move instead of AlphaGo moves, because that move's trained value from LZ self-play games is higher than winning rate that AlphaGo Master thinks.

2) Another approach is to embed that AlphaGo moves as an opening book. It's common in Chess engine world. but as we already know AG Zero beats AG Master finally, we knew AlphaGo Master's move is neither best move or God's move.

Also another problem we should think about is, Leela Zero is not AlphaGo Master. It means, AlphaGo Master opening book may spoil Leela Zero's strength if Leela Zero can't continue well from the position AlphaGo Tool info ended.
