### ISSUE TITLE
[Question] Why are all match games always starting at 4-4?

### ISSUE THREAD

**Issue by StanTraykov** [gcp/leela-zero#882]
A KGS user pointed out something interesting: all network match (not self-play) games always start the same way, with 4-4 points (and then standard 4-4 joseki).

I checked the file all_match.sgf on the site (only goes through Jan 30) and some random recent matches, and it's true. When I run Leela normally (no randomness, no switches), it starts with other moves as well, such as 4-3 points (in exactly the same situations).

Is this somehow connected to the limited number of playouts on match games or what could be the cause? Is it a normal/good/bad thing? Just a phase or to be expected to continue? (The earliest match games are obviously not all 4-4s).

**Comment by Eddh** [comment]
the 4-4 have a strong policy recommendation, so you need more playouts for other to rise above them, especially since there is apparently not much of an advantage to playing 4-3 rather than 4-4.
As to why it converged on 4-4 rather than 3-4, I think the reason is that there are four 4-4 on the board, while there are eight 4-3 (2 per corners). So the policy recommendation for 4-3 will be divided between all possible 4-3. Which lead to less policy for each. Maybe this wouldn't happen if we didn't use rotations/symmetries like in alphazero.

**Comment by roy7** [comment]
I do see in RoyalZero vs RoyalZeroSlow, RZS will somtimes open on a 4-3 point. Always fun when that happens. RZ pretty much sticks to 4-4. Like @Eddh said, it takes more playouts to move off 4-4 apparently.

**Comment by StanTraykov** [comment]
They do not anymore.
