### ISSUE TITLE
I run the latest gpu version of leelaz, why cpu is very hot

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#890]
C:\lz12>autogtp
AutoGTP v14
Using 1 thread(s) for GPU(s).
Starting tuning process, please wait...
net: 0fb68ccfbc643947bcac23c0aad4b9e43cfaa84cc01fe5da85ce06e843fabec5.
./leelaz --tune-only -w 0fb68ccfbc643947bcac23c0aad4b9e43cfaa84cc01fe5da85ce06e843fabec5
Using 2 thread(s).
RNG seed: 6886818340146206168
Detecting residual layers...v1...128 channels...6 blocks.
Initializing OpenCL.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2
Platform profile: FULL_PROFILE
Platform name:    Intel(R) OpenCL
Platform vendor:  Intel(R) Corporation
Device ID:     0
Device name:   Intel(R) Core(TM) i3-4010U CPU @ 1.70GHz
Device type:   CPU
Device vendor: Intel(R) Corporation
Device driver: 3.0.1.10878
Device speed:  1700 MHz
Device cores:  4 CU
Device score:  512
Device ID:     1
Device name:   Intel(R) HD Graphics 4400
Device type:   GPU
Device vendor: Intel(R) Corporation
Device driver: 10.18.10.3412
Device speed:  400 MHz
Device cores:  20 CU
Device score:  612
Selected platform: Intel(R) OpenCL
Selected device: Intel(R) HD Graphics 4400
with OpenCL 1.2 capability.
Loaded existing SGEMM tuning.
Tuning process finished
Starting thread 1 on GPU 0
{
    "cmd": "selfplay",
    "hash": "0fb68ccfbc643947bcac23c0aad4b9e43cfaa84cc01fe5da85ce06e843fabec5",
    "leelaz_version": "0.10",
    "options": {
        "noise": "true",
        "playouts": "1600",
        "randomcnt": "30",
        "resignation_percent": "1"
    },
    "options_hash": "16b7b7",
    "random_seed": "16414173401666685550",
    "required_client_version": "11"
}

Got new job: selfplay
net: 0fb68ccfbc643947bcac23c0aad4b9e43cfaa84cc01fe5da85ce06e843fabec5.
Engine has started.
Infinite thinking time set.
1 (B D16) ^C -- then the fan of cpu made noise and output very hot wind

**Comment by billyswong** [comment]
It's running the integrated GPU packaged in your CPU. So the whole package gets hot.

**Comment by Alderi-Tokori** [comment]
The GPU handles the network queries, and the CPU handles all of the MCTS (which feeds queries to the GPU), so both are working. Ideally, you want to balance your number of running game threads (through -g) so one of them (either GPU or CPU) is maxed out at 100% load, but of course if your cooling system isn't efficient enough, it won't be able to dissipate the heat generated from these components working at 100% and they'll eventually overheat (which reduces their lifespan).

Mind you, the fact that you're fan is accelerating and blowing out very hot air is a good sign of your cooling system doing its job properly, but you should monitor your components temperature to get a better idea of how hot they become. In order to preserve your computer's lifespan, you should avoid going above 80°C and, from personal experience, fans are usually not able to dissipate the heat from CPUs running at 100%.

**Comment by l1t1** [comment]
@Alderi-Tokori thanks

**Comment by gcp** [comment]
Selected platform: Intel(R) OpenCL
Selected device: Intel(R) HD Graphics 4400

He doesn't have a real GPU, it's using the GPU built-into the CPU, which will make it even hotter obviously.

**Comment by Alderi-Tokori** [comment]
@gcp Ah yeah, I didn't even notice that, this aggravates the problem of course.
