### ISSUE TITLE
Is the max steps of a game in latest version of leelaz modified?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#904]
I saw max steps is 359 from http://zero.sjeng.org/match-games/5a8e4e8162d50479ba4c4e5d.

**Comment by l1t1** [comment]
http://zero.sjeng.org/match-games/5a8ce0fdee16f468dedced8a still has some game over 400 steps, but that is very rare.

**Comment by barrtgt** [comment]
The maximum number of moves in a game should still be 722. It is very unlikely to reach that high in the match games due to resignation being enforced on all games and a decent evaluation of the board state, whereas self play games will have 10% of the games with it being disabled, so if you are lucky enough, you might see one be that long.

**Comment by wctgit** [comment]
I don't think so. It's more likely that the networks are getting more accurate at calculating low win rates and resigning, since matches all run with resignation happening when below 1% winrate. In self-play games with resignation at 0%, you still get long games.
