### ISSUE TITLE
train stronger weights

### ISSUE THREAD

**Issue by jqwel** [gcp/leela-zero#924]
If train 5b network weights with 6b self-play SGF data, a stronger 5b network results?

**Comment by jkiliani** [comment]
Very unlikely. Usually, the strongest weights for a given network size are obtained by reinforcement learning on games produced by that same network. It would probably be possible to train a stronger 5 block net now (even maybe with 6 block data), but that would be only because the shuffle buffer problem was discovered after we were already on 6 blocks.

**Comment by Dorus** [comment]
Try it. Test it. Any speculation on this subject is pointless.

However i do believe that our 5b net beat the 5b HBest net we tried to make. That would indicate it indeed does learn more from selfplay than from games from other nets.
