### ISSUE TITLE
Batchnorm Scale and Bias in the weights?

### ISSUE THREAD

**Issue by woodyzh** [gcp/leela-zero#925]
Hi there. From the description of the Weights Format, it says:
Batchnorm layers have 2 weight rows: 
batchnorm means
batchnorm variances

I'm just wondering if there also should be "Scale" and "Bias" parameters for each channel? Or does the program use 1.0 and 0.0 for those parameters?

Thanks!

**Comment by stevevista** [comment]
Right. means and variances have been adjusted to fit gamma =1.0 and beta = 0.0

**Comment by gcp** [comment]
Note that Scale is completely pointless for the network architecture used, due to the use of ReLU units it's fully redundant with the next weight layer.

Bias may not be redundant, but nobody has ever seen much if any benefit for it, and testing it on our data didn't show any real advantage either.

The Scale/Bias can be incorporated into mean/variance, but because of the above the training simply doesn't use them.
