### ISSUE TITLE
LZ distributed training effort = common training settings?

### ISSUE THREAD

**Issue by ThomasCabaret** [gcp/leela-zero#930]
Hi,
(I did not see any piece of information about this neither in the README or in open issues)
The training games are played with training specific settings:
-Nb playouts (1600)
-Noise (for exploration)

1) Are there any other training specific settings than these two?
2) Can we have more details about the noise used in training?
3) As a distributed-training-effort contributor have I control over/may I customize those training-specific-settings?

Regards,

**Comment by jkiliani** [comment]
1. There are two more settings specific to training: 
-d (dumbpass) which means the engine is allowed to pass if the neural net thinks it's smart, even if it is behind on the board and moves other than passing are legal, and
-m 30 (random count): For the first 30 moves, the selected move is decided proportionally based on the visit count, instead of always picking the one with highest visits. This allows weaker moves to be played in the opening, but creates much more variety in game positions.

2. The noise used in training means that at root state, moves are explored even when the neural net does not consider them candidate moves. This is essential for training, so the engine can discover better moves that the current neural net is unaware of, so these moves become part of the next generation neural net. Specifically, in training 75% of playouts use the policy priors (i.e. moves suggested by the neural net), and 25% use noise, to try if the net overlooked something important.

3. As a contributor you don't have control over the game settings used. You can control settings when playing Leela Zero on a bot, or on Sabaki, but not when running autogtp, for the simple reason that the training data used for producing better networks is supposed to be internally consistent.

**Comment by gcp** [comment]
>Specifically, in training 75% of playouts use the policy priors (i.e. moves suggested by the neural net), and 25% use noise, to try if the net overlooked something important.

No, they all use noise *on* the policy priors.

The 0.75 is just the weighting of the real prior vs the noise added.

**Comment by gcp** [comment]
>Can we have more details about the noise used in training?

Please read the original paper:
https://storage.googleapis.com/deepmind-media/alphago/AlphaGoNaturePaper.pdf

**Comment by gcp** [comment]
>Are there any other training specific settings than these two?

The resign threshold. Resigning is at 1% for 75% of the games, and disabled in the other 25%.

**Comment by gcp** [comment]
>-d (dumbpass) which means the engine is allowed to pass if the neural net thinks it's smart, even if it is behind on the board and moves other than passing are legal, and

dumbpass basically puts the network in total control of passing.

Without dumpbass, in addition to the above, the engine also knows that it should pass if this instantly wins the game. But as these are human knowledge that was added, it's disabled for the Zero training.

**Comment by ThomasCabaret** [comment]
Thx for your reply.
All those values have been decided based on something specific or is it just a guess? (I'll read the original paper, I did already but month ago)
Any plan on testing somehow different ones on some time windows to see the impact on the distributed training performance?
Related to your answer to 1 by example:
http://zero.sjeng.org/view/b5756f3074b5f340c7146e8f58bfdb5689b237471e555eb60b87ab98bc762b76?viewer=eidogo
See move 5 above.
http://zero.sjeng.org/view/351f0ff90465ee577e80babf51362e6883d4e7bd99ee4c0ffaf0998705f5c6fe?viewer=eidogo
See move 10 above.
In the above 2 examples, two things strikes me:
-first 4 moves are very rarely something else than quite standard corner moves.
-1 line moves can be see quite often in training game.
In your answer the 30 moves opening are "decided proportionally based on the visit count" which would mean either (in those 2 examples) than the network do not visit anything else than corner moves early, but paradoxically visits not that rarely 1st line moves a little later.
Are we confident this noise and opening exploration strategy are working as designed? openings of training games do not seem that diverse.

**Comment by jkiliani** [comment]
@gcp Thanks for the correction on the noise weighting, but I think you linked the wrong paper. Dirichlet noise is (afaik) only discussed in the Alphago Zero paper (https://www.nature.com/articles/nature24270.epdf?author_access_token=VJXbVjaSHxFoctQQ4p2k4tRgN0jAjWel9jnR3ZoTv0PVW4gB86EEpGqTRDtpIz-2rmo8-KG06gqVobU5NSCFeHILHcVFUeMsbvwS-lxjqQGg98faovwjxeTUgZAUMnRQ), not the original Alphago paper

**Comment by gcp** [comment]
Yes, it's the AlphaGo Zero paper.

>Any plan on testing somehow different ones on some time windows to see the impact on the distributed training performance?

No, the resource requirement to repeat the experiment is too prohibitive. We stick as closely as reasonable to what we know works.
