### ISSUE TITLE
Weird promotions

### ISSUE THREAD

**Issue by tterava** [gcp/leela-zero#932]
I've noticed sometimes a network gets promoted if it's close to the 55% winrate required. I'm assuming this is because the score fluctuates and games uploaded after the promotion drop the winrate a bit. While this is not a big deal, there's currently an issue where network a91721af managed to get promoted with less than 45% winrate against our strongest network. I believe this is the 2nd time where a clearly inferior network takes the top spot, and leads to lesser quality games until it gets replaced. What is the cause of such anomalies?

**Comment by pw31** [comment]
I noticed that, too, very curious.  92dd0397 got promoted contrary to the 55% rule
2018-02-26 03:38 | 92dd0397 VS 9ac646d7 | 230 : 191 (54.63%)
which still makes sense in a way, but now
2018-02-26 09:52 | a91721af VS 92dd0397 | 87 : 108 (44.62%)
a91721af got promoted with clearly inferior win percentage.

Is this a feature or a bug?

**Comment by jkiliani** [comment]
Just look at the match history (click on "vs"): a91721af had 11 wins to 1 loss in the beginning, enough to get an SPRT pass (and was promoted). Directly after this, it started losing most of its games, so now it failed even after it had promoted.

**Comment by pw31** [comment]
... OK, fine, a91721af was finally recognised to have failed.  But why was a91721af promoted anyway after it was established that it failed? That doesn't sound right to me.

**Comment by jkiliani** [comment]
Because promotion is never revoked. The point of SPRT is that it will only make a decision (pass or fail), when it is statistically highly unlikely that this decision will be overturned by more testing samples, i.e. later arriving results. Apparently, that still does happen occasionally though.

There is also the theory that some very early passing nets that end up lacklustre or even poor are the result of a net that's good at early game fighting, e.g. ladders, but poor at the endgame. Since short games tend to report back to the server first, this can skew the statistics.

**Comment by tterava** [comment]
I didn't know you can see the match history. It makes sense now.
I guess this network falls into the error margin of SPRT or is the result of bias towards fast wins. Maybe to combat this there should be a minimum 50 games played or so before promotion can happen?

**Comment by jkiliani** [comment]
@tterava I agree, and I proposed the same solution to @roy7. I hope it gets implemented this time, we had a similar occurrence a while back, with af4f49f1. It had an early pass, and then failed later (but not quite as fast as a91721af).

**Comment by gcp** [comment]
> Apparently, that still does happen occasionally though.

We expect about 1/20 FWIW, and there's a lot of test matches, so...

**Comment by MartinDevelopment** [comment]
Promoting a network that is slightly worse every so often won't really do any harm. It may even do good over the long term by adding things that it thinks is bad but is actually good.

**Comment by roy7** [comment]
@gcp Do you want me to implement a minimum # of games before the SPRT test will issue a success/fail? What # should I use?

The issue is that an overall weaker network which has a great early game, or maybe is great at ladders, can churn out early victories faster (since the games are shorter) and skew the early results before the losses start arriving. Individual games aren't independent events in this way.

**Comment by gcp** [comment]
Maybe set it to 100 before issuing a promotion?

Failing is much less a problem because a network can un-fail. But it cannot un-promote.
