### ISSUE TITLE
[Question] New best network weaker than previous

### ISSUE THREAD

**Issue by StanTraykov** [gcp/leela-zero#940]
How come the new best network (a91721af) is weaker than the previous one (92dd0397)? There were only 199 matches and it scored significantly below 50%:
   2018-02-26 09:52 | a91721af VS 92dd0397 | 89 : 110 (44.72%) | 199 / 400 | fail

If this was a manual override, why was it necessary?

**Comment by Heiseikiseki** [comment]
Please look at #932, #933 and #78 and then close this issue.

**Comment by alreadydone** [comment]
Instead of closing, should we stick one of these on top? :)

**Comment by StanTraykov** [comment]
I apologize for not having had a look at the 'closed' section and submitting a duplicate, but if this comes up so often, maybe it's worth a footnote on http://zero.sjeng.org/.

**Comment by tychota** [comment]
@Heiseikiseki is it what 
![image](https://user-images.githubusercontent.com/13785185/36757205-4742e7e0-1c11-11e8-801a-42dc79829cc4.png)
means because I don't think it is clear enough.

We can think that weaker networks can be trained, but the sentence it self does not apply that it ends up being promoted.

I suggest to rephrased it like this:

> Most of the time, weaker network that the current best one are trained. 
It sometimes happen that they ends up being promoted. One reason can be that the network can be good at early game / ladder thus won game are faster then it reach the points to be promoted faster. When longest game (games where the new network is bad at closing) comes, the new network is already promoted.
This has not that much influence on the overall training rate of the program as there is also a lot to learn from those "high quality short game - weak late game" networks and they will end up being replace by another networks anyway

@gcp what do you thing of that or something like this. i will happily PR this if needed :)

**Comment by Heiseikiseki** [comment]
No I think that sentence not means this situation. If you read other issue. It is because it lucky win too many in the beginning. Now it has been fixed. (need to play until 100 games) . So this problem has been solved.

**Comment by StanTraykov** [comment]
This is actually already addressed in the FAQ (section Why only dozens of games are played...) but it's not very clear and probably could use a rewrite after the update anyway (as at least 100 will be needed).

For the stats page, perhaps the replacement text should remain concise, something like:

Not each trained network will be a strength improvement over the prior one. Patience please. :)
->
Not every new network will be stronger that the previous one. Occasionally, even the new "best network" may turn out to be weaker, see FAQ.

**Comment by tychota** [comment]
@Heiseikiseki : you mean https://github.com/gcp/leela-zero-server/pull/12 right ? Nice solution to wait a bit :)

@StanTraykov @gcp : do you want me to propose the above chhange ?

> Not every new network will be stronger that the previous one. Occasionally, even the new "best network" may turn out to be weaker, see FAQ.
