### ISSUE TITLE
why 959ca800 is 4.461M+192k?

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#941]
not 256

**Comment by MaxMaki** [comment]
Because 256k comes after 192k?

**Comment by l1t1** [comment]
but prior ones are all 2^n

**Comment by jkiliani** [comment]
There's no law that it has to be a power of 2. @gcp just sets the testing checkpoints at values that seem like a good compromise between testing enough nets and not using too many resources to do so. It's not an exact science.

**Comment by wctgit** [comment]
Can I just borrow this issue to ask a second question? Suppose the current champ is `X0`, and the champ + 8k is `X1`, so we can give a pseudo equation that `X1 = X0 + 8k`. The next contender is `X2`, which corresponds to "+16k". Which of these pseudo equations is closer to the truth?:
- `X2 = X0 + 16k`
- `X2 = X1 + 8k`
- `X2 = X1 + 16k`

**Comment by zediir** [comment]
1. and 2. are equal but the training machine probably does 2. because it is unnecessary go back to X0 instead of just adding 8k more steps.

**Comment by wctgit** [comment]
1 may be (probably is) different than 2, in that it can a) use a different set of 8k for the first 8k, and/or b) use a different random seed for any randomness involved in the training process. gcp has confirmed earlier that running the same training process on the same starting network and training data will produce a different result because of (b) for sure, and I think by that he may also mean (a) (i.e. randomized shuffling).
