### ISSUE TITLE
do we need a match between proir and next when current best network winrate less than 0.5

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#944]
no.89 is 0.56 to no.88,
no.88 is 0.44 to no.77.
can we guarantee no.89 is stronger than no.87?

**Comment by StanTraykov** [comment]
Maybe adding a waiting period before network promotion (say half an hour), in addition to SPRT requirements, would be more the point, ensuring that promotion doesn't happen to networks that are just good at winning early (games with small number of moves that report earlier).

**Comment by jkiliani** [comment]
It's already taken care of now. @roy7 has pushed an update to the server which specifies a minimum number of 100 games in addition to SPRT pass in order for a promotion to occur. We may still have cases of passing nets failing with 50-55% in the end, but failing at below 50% has become much more unlikely now.

**Comment by l1t1** [comment]
I have a simple suggest, keep match playing until one of them got 181 lost, we can eusure he isn't the winnner in 400 games

**Comment by jkiliani** [comment]
No simple solution can ever exclude the possibility of matches first passing and then failing afterwards, since the testing process is distributed and has to include overhead ,i.e. it has to request more match games than 400 in order to receive 400 results. It will always be possible for a net to narrowly pass at 55% at 400 games, and then fails when later arriving results are included. We simply have to live with that, but the current fix should at least exclude nets passing that are actually below 50%.
