### ISSUE TITLE
hilarious game of LeelaZero against Leela 0.11 

### ISSUE THREAD

**Issue by pw31** [gcp/leela-zero#946]
If you're interested: https://online-go.com/game/11845631:
LeelaZero 92dd0397 (white, alias RoyalZeroSlow on OGS) against my Leela 0.11 (black, on 8 CPUs at 10sec/move ~ 30000-100000 visits).  Leela 0.11 performs a clean kill of a huge LeelaZero group as  early as move 47.o2!  Soon thereafter, game ends with a ladder. Feels like crying.

**Comment by wctgit** [comment]
:-D 
@roy7
If RoyalZeroSlow's using 80,000 visits, why does it rarely get close to 80,000? Time management or something?

**Comment by pw31** [comment]
I did set the time to 30sec/move, to RoyalZeroSlow accelerate a bit. She is using that time fully each move.

**Comment by OmnipotentEntity** [comment]
@wctgit I've noticed something recently where evaluation will stop early.  What's going on is in UTCSearch.cpp there's a function called `stop_thinking` and one of the things it does is estimate the number of playouts it has left to think.  If the best move has so many playouts that, if another move gets 100% of the playouts from this point forward, it will still have the most, then the evaluation aborts early.

It's designed to speed up moving when there is very little chance of the selected move changing.

**Comment by roy7** [comment]
Yeah that's the "timemanage" feature KillerDucky added. :)

For those interested, here's the full log from RoyalZeroSlow's side of that game. http://termbin.com/vvod

**Comment by wctgit** [comment]
> if another move gets 100% of the playouts from this point forward, it will still have the most, then the evaluation aborts early.
>
> It's designed to speed up moving when there is very little chance of the selected move changing.

Hmm, while it seems like a good idea on the surface, I think it may backfire a bit because spending more time even on the **best** move will still sometimes find out better responses to the opponent's responses, hence different PVs, for example.

Instead of stopping thinking altogether, it would be better just to devote all the remaining visits/playouts to the top move (since no other move will be able to displace it). **Those** playouts would not be wasted.
