### ISSUE TITLE
Is Alphago Master's approach better?

### ISSUE THREAD

**Issue by bailsman** [gcp/leela-zero#977]
It's possible that AlphaGo Master (starting from supervised learning) is much stronger than AlphaZero. I say this because of http://www.computer-go.org/pipermail/computer-go/2017-October/010357.html and because Pro Commentator Michael Redmond 9d thinks from playing style that Google used 'an updated version of AlphaGo Master' for the Ke Jie match. Suggesting google used their strongest program, not wanting to take any chances. In Redmond's opinion: AlphaGo Ke Jie > AlphaGo Zero > AlphaGo Master but Ke Jie version plays very similarly to Master, and AlphaGo Zero's style is different.

Would it make sense to try and make a program based on the AlphaGo master approach, rather than AlphaGo Zero? What about chess - was supervised learning tried there?

**Comment by jkiliani** [comment]
I think this will happen eventually. However, Master's style most likely isn't caused by the supervised learning, but by the additional features and the rollouts. Once zero style engines get really strong, they will be combined with other features such as Monte Carlo rollouts, to further push playing strength.

**Comment by wpstmxhs** [comment]
I think the title is wrong. AlphaGo Master was starting from supervised learning, but its strength is mainly from reinforcement learning. I suggest you to change the title as 'Is AlphaGo Master approach better?' or so.

**Comment by bailsman** [comment]
Is it possible that starting with supervised learning speeds up the training process? If it does, by how much? I think master has shown that you it doesn't *necessarily* limit the strength of the program.

**Comment by RavnaBergsndot** [comment]
Both the 5/64 network and the current 6/128 network are way stronger than what achieved with supervised learning. We are past the early stage when "speeding up" makes difference now.

**Comment by bailsman** [comment]
Roughly how strong is a network trained by supervised learning such as how AlphaGo Master was started - and how strong is Leela currently? Could it make a difference when the network sizes increase, or when we change the network inputs?

**Comment by Yoitsu36** [comment]
It would be very interesting to try running selfplay games with a supervised network and check how it compares with the zero version once both plateau, but there are many other experiments that could also be tried and it would just break with the main purpose of the project (a full zero run) so i dont expect it will be tested for now.

**Comment by bailsman** [comment]
Is there a list of experiments requiring hardware somewhere, with how much hardware they need and what the benefit is?

**Comment by wctgit** [comment]
@bailsman, I proposed a similar idea some days ago, but it got shot down. I still think it's a good idea, though.

**Comment by barrtgt** [comment]
According to the AGZ paper, the zero approach is supposed to be faster to get to AG Lee strength than the supervised approach. However, it is not known how fair of a comparison they presented.

**Comment by bailsman** [comment]
According to the mailing list the paper says the AGZ version never got to AGMaster level at all. Let alone faster...

**Comment by barrtgt** [comment]
As far as I know, Deepmind didn't publish the numbers of the 20 block zero, but they did show a chart. I tried to extract the numbers from the chart but it resulted in a ~120 elo mismatch for the 40-block, and my closest estimate for the 20-block is ~4345 elo after 70 hours. Master reached 4858 elo with 20 blocks, 40 block Zero is 5185 after 40 days. Check out the page https://deepmind.com/blog/alphago-zero-learning-scratch/. A link to the paper should be at the bottom with the charts described.

**Comment by gcp** [comment]
It's not entirely unambiguous from the paper, but it seems very likely that AG Master 20 blocks was stronger than AG Zero 20 blocks.

Whether this approach was "better" depends on your point of view. Would the difference between AG Master 40 blocks and AG Zero 40 blocks be as big? (Probably not). How much effort does it take to create AG Master? (quite a bit, and note the principal author had written a world-championship winning Go program before they started the Alpha Go effort).

I used the Zero approach because I think it's more interesting for a project like this:

1. We do not have to argue endlessly about which features are likely to help or not, or even run the experiments before being able to start. We just used the minimum.
2. A lot of intermediate data and play is generated, and it's possible to see the style evolution of a "clean", not "human biased" program, in more detail than just from the few games in the AGZ paper.
3. I think the "Zero" approach brings broader interest, which is important because it needs computing resources. Zero has gotten much wider contribution than, say, AQ, and there are much more clients than there are on fishtest. (I completely mis-estimated this early in the project and expected far less interest)

Will this necessarily generate the strongest program, especially with limited resources? Most probably not. But note the Zero data is usable for bootstrapping other efforts.

I am fairly sure, for example, that simply replacing classic Leela's network at this point with one trained from combined human+latest zero data would be a nice improvement. Probably the same is true for programs like AQ.

**Comment by luigio** [comment]
Doesn't AlphaGo Zero's 89-11 win over AlphaGo Master prove its superiority? Or is the debate about whether Master could have gotten better than Zero with enough training and a big enough network?

**Comment by gcp** [comment]
AFAIK it was confirmed when people asked or during other presentations. It's not 100% unambiguous, though.

**Comment by jkiliani** [comment]
@luigio No it actually doesn't. This was discussed in https://github.com/gcp/leela-zero/issues/591, a while ago.

**Comment by godmoves** [comment]
I try to let AQ use the weight of LZ, but it doesn't perform better than the original AQ. Maybe there are some bugs or the hand-crafted features have some conflicts with the judgement of LZ. I will  do more test in next weeks.

**Comment by gcp** [comment]
The level of the LZ data is only medium dan level, so it would make more sense to combine than replace, I think. Particularly for value networks I would expect LZ data to help.

**Comment by godmoves** [comment]
Yes, I think so and I am using this method to train a various sizes of networks to find the relationship between the network structure and performance, if it really gets some interesting results, I will let you know : )

**Comment by wpstmxhs** [comment]
I'm training new 20 block network started from @zediir 's supervised 20 block network.

My goal is to make stronger 20 block network than original supervised 20 block network.
I grabbed strong AI kifus(including AlphaGo games) from online go platforms or CGOS and used RN's self-play games (approximately 110K), so I collected about 215K games.
and now I started to train network more from @zediir 's completed 20 block network.

I will report the result if I have good result.
Anyway, is there anyone who can modify tensorflow training python code to support multi-GPU? 
I tried to make it support but eventually failed.
If someone modifies that, I would be happy.

**Comment by pangafu** [comment]
@gcp I want to train a model just as you said, and when we will update https://sjeng.org/zero/, the last update is 15 days ago.

**Comment by gcp** [comment]
Updated now. You can also download from #167 if you want the detailed MCTS probabilities.

**Comment by yufanyufan** [comment]
Is it possible to take the last 1M game or so, to train a network from ground up, without initialization from a previous network, and reach comparable strength?
If so, it is easy to switch master style anytime by adding handcrafted feature and rollout.

**Comment by pangafu** [comment]
@gcp thanks a lot!

**Comment by gcp** [comment]
>If so, it is easy to switch master style anytime by adding handcrafted feature and rollout.

Yes, you can always run the training data through something else. (There are some slight complications in practice, either you'd use the SGF and don't use the fined grained probability maps, or you'd use the raw training data, but have to compute the augmented inputs from the ones in there)
