### ISSUE TITLE
a question about choose 10b best file

### ISSUE THREAD

**Issue by l1t1** [gcp/leela-zero#984]
I notice net work ae205d8b is 4813+1.19M, while f1383525 is 4813+1.11M,
why first let ae205d8b play with old best ,and then let it play with f1383525 ?

**Comment by roy7** [comment]
They were uploaded out of order because it was done by hand, for the move to 10 blocks.

**Comment by roy7** [comment]
Because resign is now at 10% instead of 1%, and we moved to a visits cap instead of a playout cap that might also speed things up. The resign cutoff is probably the big reason.

**Comment by alreadydone** [comment]
Training has slowed down by a factor of 10/6. 16k steps for 10b needs 100min while for 6b it needed 60min.

**Comment by syjytg** [comment]
What is the difference between visit and playout?

**Comment by gcp** [comment]
>What is the difference between visit and playout?

If the tree is partly reused from a previous move (a feature introduced in LZ 0.11), then doing 1600 new playouts means that the tree might actually have much more than 1600 playouts in it. So instead of adding 1600 new playouts every move, we stop when the tree has 3200 visited nodes in total.

In practice, this means the self-play is much faster along forced variations. We measured that this increases the program efficiency a lot, while not requiring any kind of human input/knowledge.

**Comment by MathAndreas** [comment]
The question was: "why has the speed of generating new networkfiles increased?", that is, since using 10 block nets it takes less games to promote a new best net.

**Comment by alreadydone** [comment]
@MathAndreas https://github.com/gcp/leela-zero/issues/965#issuecomment-370724279

**Comment by alreadydone** [comment]
@gcp You said you lowered batch size (to what?) https://github.com/gcp/leela-zero/issues/965#issuecomment-369962394 and raised it again https://github.com/gcp/leela-zero/issues/965#issuecomment-370724279. Is it now 512 again? Are you considering raising it again? Do you think that would be advantageous (especially for AlphaZero approach)? If so, do you think my suggestion https://github.com/gcp/leela-zero/issues/591#issuecomment-369502264 is a good way to raise batch size?

**Comment by gcp** [comment]
I lowered batch size because the machine that trained the initial 128x10 net simply didn't have as much GPU RAM as the machine doing the real training.

There is no point in increasing batch size aside for computational efficiency, the ideal batch size is in fact 1. So the suggestion makes no sense.
